### ISSUE TITLE
Pilot Phase

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#1]
Lion Web Components are still in an early alpha stage; they should not be considered production ready yet.

The goal of our pilot phase is to gather feedback from a private group of users. Therefore, during this phase, we kindly ask you to:

- not publicly promote or link us yet: (no tweets, blog posts or other forms of communication about Lion Web Components)
- not publicly promote or link products derived from/based on Lion Web Components

Feel free to subscribe to this issue to be notified as soon as the Pilot Phase ends.

**Comment by thepassle** [comment]
Whats the status on this? Will there be some kind of communication around Lion or should it still be kept quiet? Are there plans?

**Comment by gerjanvangeest** [comment]
For now it is still in the `Pilot Phase`. We want to do some upgrades of our demos and documentation. We have a story high on our backlog to exactly identify the changes we want to do, and hopefully are able to do those fixes within this year. 

If you have any suggestions or time to help us to do some of these upgrades, please let us know!

**Comment by thepassle** [comment]
Mostly just curious on the status.

As for suggestions, demos/docs would be great, and probably an announcement blog at some point. Happy to help out with demos/docs, feel free to DM me on mattermost or slack if ya'll got some work that you can offload :)

**Comment by wsloth** [comment]
Yeah please let us know what we can do. I would like to contribute as well, also to the documentation and perhaps examples. Is there any low hanging fruit over there that can be picked up?

**Comment by daKmoR** [comment]
hey everyone,

the time has finally come - we are now officially ending the pilot phase 🎉 

Read the [announcement blog post](https://medium.com/ing-blog/ing-open-sources-lion-a-library-for-performant-accessible-flexible-web-components-22ad165b1d3d) for more details 🤗 

Does that now mean it's time to help spread the word about it? **YES**, definitely. 
Share the [blog post](https://medium.com/ing-blog/ing-open-sources-lion-a-library-for-performant-accessible-flexible-web-components-22ad165b1d3d), share/star the [ing-bank/lion](https://github.com/ing-bank/lion/) repo, show it to your friends/colleagues, share it on social media, print posters (😬) ... feel free to get creative 🤗

**Comment by Danny-Engelman** [comment]
Good work! (*been listening in here since my weekly 'component' search first reported the Repo in Google*)
