### ISSUE TITLE
[combobox] Focus state not always visible

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#1000]
## Expected behavior

When I tab into the textbox at any point, I expect to see a caret in there.

## Actual Behavior

Sometimes the textbox is empty when focussed. For example, when I enter the textbox, clear the value, tab out and back in, there is no visible focus. This might be possible to reproduce in more ways than this.

**Comment by tlouisse** [comment]
Interesting. We just use a browser input here. Can you make a gif for this?

**Comment by erikkroes** [comment]
Also on Safari

![Oct-07-2020 09-56-07](https://user-images.githubusercontent.com/10405024/95303353-5ed9c480-0883-11eb-8d0d-43bea61ba1af.gif)

**Comment by tlouisse** [comment]
Hmm, ee just leverage the platform for focus management here.
So when you 'tab back', `document.activeElement` is LionCombobox._inputNode, right?
If that is the case, it seems to be browser behavior. Does it happen on other browsers than safari as well?

**Comment by tlouisse** [comment]
Couldn't reproduce anymore.
Tested on Safari (with and without VoiceOver), Chrome (Chromium) and Firefox

I think it might be just an 'unlucky build' of Webkit back then. On top of this, it's probably not something we could have solved inside the combobox component
