### ISSUE TITLE
[combobox] Matched item not checked on [space]

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#1001]
## Expected behavior

When the content of the dropdown matches the textbox, I expect the value in the dropdown to be blue.

## Actual Behavior

When I type a "J", Jerusalem artichoke is put into the textbox and select in the dropdown. If I press a space after, and backspace to remove it, the content is the same as before but the dropdown is grey instead of blue.

<img width="773" alt="" src="https://user-images.githubusercontent.com/10405024/95295113-c5a4b100-0876-11eb-9f64-c8026369b616.png">

**Comment by tlouisse** [comment]
Yeah, I see what you mean now. Only happens on space indeed. Good find 👍

**Comment by tlouisse** [comment]
This is actually not related to [space], but just to the fact that you remove text (which on purpose does not inline autocomplete in textbox, but should select however) :)
Same issue here: https://github.com/ing-bank/lion/issues/998
