### ISSUE TITLE
[combobox][multiple-choice] Unable to remove first chip by itself

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#1004]
## Expected behavior

When multiple options have been selected, I would expect to be able to remove previous options while keeping the last one(s).

## Actual Behavior

I can not remove my first choice when a second has been added. Not with mouse and not with keyboard. Updating the text to only show the second (and not the first) actually removes the second.

I would like to repeat my advice to remove the multiple choice version as interactions have not been specified.

**Comment by tlouisse** [comment]
Yeah, this implementation is a demo of what would be possible (I think it states that if I'm right).

Can we maybe move this point to this discussion: https://github.com/ing-bank/lion/discussions/954 ?

**Comment by tlouisse** [comment]
Closing, discussion can be found on https://github.com/ing-bank/lion/discussions/954
