### ISSUE TITLE
Combobox needs additional inherited styles to allow styling

### ISSUE THREAD

**Issue by davidoff31** [ing-bank/lion#1007]
## Expected behavior

As explained in the component code, the .form-control element is wrapped in the slot's div and added inline styles to allow inherited styles from the slot.

![image](https://user-images.githubusercontent.com/63789961/95354958-51ddc500-08c5-11eb-9338-02c27ce36455.png)

## Actual Behavior

The current inline styles do not cover too many rules, so it is not possible to edit color, border-radius nor font rules except from size.

## Additional context

I would add at least the following rules set to 'inherit' to allow styling: color, font (generic rule), border-radius.
 It is probable we will have to extend the ruleset to make the component flexible enough for styling.

**Comment by tlouisse** [comment]
Makes a lot of sense. You could do a merge request if you want :)

**Comment by davidoff31** [comment]
I wil, briefly  ;)

**Comment by tlouisse** [comment]
Closed by https://github.com/ing-bank/lion/pull/1011
