### ISSUE TITLE
[combobox] Class form-control is applied to content rather than slot

### ISSUE THREAD

**Issue by davidoff31** [ing-bank/lion#1013]
## Expected behavior

Class form-control should be associated with the visible part of the component, as it is for all other components, to allow consistent styling.

## Actual Behavior

The class form-control is applied to the input inside the slot "input". This breaks the styling pattern which for all other elements uses ::slotted(.form-control) to style the input's appearance.

## Solution
Add the class to the slot element to align styling behaviour. Not sure about what to do with the class within the slot which is applied to the input tag, is it useful in any way?

**Comment by tlouisse** [comment]
@palash2601 faced the same issue :) Fixed by https://github.com/ing-bank/lion/pull/1012

@davidoff31 Will soon do a release for this

**Comment by davidoff31** [comment]
Great, thanks

**Comment by tlouisse** [comment]
@davidoff31 see https://github.com/ing-bank/lion/pull/982
