### ISSUE TITLE
[combobox][multiple-choice] chip doesn't replace text

### ISSUE THREAD

**Issue by Avocher** [ing-bank/lion#1038]
## Expected behavior

Show only the chip after a choice has been selected.

## Actual Behavior

It shows both the chip and the text for each choice added: 
https://lion-web-components.netlify.app/?path=/docs/forms-combobox--autocomplete-list#multiple-choice

**Comment by palash2601** [comment]
You can try adding `has-no-default-selected` attribute or setting `hasNoDefaultSelected`  to `true`

**Comment by tlouisse** [comment]
Happens here: https://github.com/ing-bank/lion/blob/master/packages/combobox/src/LionCombobox.js#L301

Could be solved via:

```js
    if (name === 'modelValue' && this.modelValue) {
      if (!this.multipleChoice) {
        this._setTextboxValue(this.modelValue);
      } else {
        this._setTextboxValue(''); // or last selected value?
      } 
    }
```

We should also refine a bit better what's the most accessible solution here. Maybe @erikkroes has some ideas about this. We also have a discussion section here: https://github.com/ing-bank/lion/discussions/954

**Comment by tlouisse** [comment]
@Avocher it would be fixed by https://github.com/ing-bank/lion/pull/1056 (only the last value gets synced to textbox and it's also possible to define your own behavior)

**Comment by Avocher** [comment]
Thank you once again @tlouisse I'll try it out.
