### ISSUE TITLE
[overlays] placementMode: 'local' and trapsKeyboardFocus: true not working

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#1065]
## Actual Behavior

Steps described in the snippet:

https://webcomponents.dev/edit/rdXftLTxlTioPnqiKCuZ

## Additional context

When the placement is local, the content of slot is in the shadowDom, the activeElement of the content should be taken on the root node of content slot instead of `document`

See here:
https://github.com/ing-bank/lion/blob/27e35b45755633849045efae4b0fdb5265391315/packages/overlays/src/utils/contain-focus.js#L119

## Possible fix

```javascript
rootElement.getRootNode().activeElement
```

instead of
```javascript
document.activeElement
```

**Comment by tlouisse** [comment]
Nice. Would it be possible to add a test for this as well?
