### ISSUE TITLE
lion-button: event target when used inside lion-form

### ISSUE THREAD

**Issue by palash2601** [ing-bank/lion#1069]
## Expected behavior

For below usage of lion-form and lion-button, Event target should be host element itself. i.e. lion-button

## Actual Behavior

event target is native button element

```html
<lion-form>
  <form>
    <lion-button @click=${ev => console.log('click handler', ev.target)}>Submit</lion-button>
  </form>
<lion-form>
```

Is this usage still valid?

This probably came after[this](https://github.com/ing-bank/lion/pull/1019/files#diff-ca4451dc93dc2f1a8099b58440d9613ff1755fb42bf9f3fe2eb60a31387d0310R211) latest changes

MR with failing test 
https://github.com/ing-bank/lion/pull/1068

**Comment by tlouisse** [comment]
@palash2601 would you be willing to revert this change in a merge request?
https://github.com/ing-bank/lion/pull/1019/files#diff-ca4451dc93dc2f1a8099b58440d9613ff1755fb42bf9f3fe2eb60a31387d0310L216
