### ISSUE TITLE
Not able to see any demo output under canvas tab

### ISSUE THREAD

**Issue by rajkeshwar** [ing-bank/lion#107]
I setup the lion project and ran using `npm run start` but not able to see output in chrome and safari. Here are the respective versions.

OS : MacOS 10.14.1
Chrome: Version 75.0.3770.100

Please see the screenshot below.

<img width="1042" alt="Screenshot 2019-06-18 at 7 00 27 PM" src="https://user-images.githubusercontent.com/5517744/59704341-2e889580-91fc-11e9-91fd-b1b0cab6c325.png">

**Comment by tlouisse** [comment]
I work on Chrome mac as well. Do you have any console errors? Does it help if you remove node_modules and run yarn again?

**Comment by rajkeshwar** [comment]
I have forked version of lion a month ago. Today I cloned it from the source and it worked fine. Now I am closing it.
