### ISSUE TITLE
Datepicker validators inconsistent behaviour

### ISSUE THREAD

**Issue by vlaraort** [ing-bank/lion#1076]
## Expected behavior

The minDate and maxDate validators should work as expected when the date is filled in the input field or the calendar

## Actual Behavior

If you pick the date in the calendar works fine, as the date is serialized properly

If you write the date in the input, it gives faulty validation error.

## Additional context

The date is validated here:

https://github.com/ing-bank/lion/blob/master/packages/form-core/src/validate/validators/DateValidators.js#L60

With the `normalizeDateTime`function, the value is compared with
`Wed Nov 04 2020 00:00:00 GMT+0100 (Central European Standard Time)` (note the 00:00:00 time)

If I select the date in the picker, the date is the same so the validator doesn't gives error

If I write the date in the input field, the date is parsed here

https://github.com/ing-bank/lion/blob/master/packages/input-date/src/LionInputDate.js#L34
https://github.com/ing-bank/lion/blob/master/packages/localize/src/date/parseDate.js#L59

And this line `new Date(Date.UTC(2020, 11 - 1, 4))`

Causes that my modelValue Date is 

`Wed Nov 04 2020 01:00:00 GMT+0100 (Central European Standard Time)` (Note the time)

Which is greater than the validator maxDate, even if they shouldn't be

**Comment by tlouisse** [comment]
@vlaraort Thanks for the report, and it would be great if you want to do a pull request for this 👍

**Comment by vlaraort** [comment]
Ok @tlouisse , do you think that normalizing both dates here:

https://github.com/ing-bank/lion/blob/master/packages/form-core/src/validate/validators/DateValidators.js#L60

Would be enough?

**Comment by tlouisse** [comment]
I mean we can apply  normalization consistently in all Validators:
- https://github.com/ing-bank/lion/blob/master/packages/form-core/src/validate/validators/DateValidators.js#L77
- https://github.com/ing-bank/lion/blob/master/packages/form-core/src/validate/validators/DateValidators.js#L43

(so for the isDate check it would not be needed)

Could you also add some tests if possible?

**Comment by vlaraort** [comment]
Sure, will do it
