### ISSUE TITLE
[overlays] Failed to remove node error on containFocus

### ISSUE THREAD

**Issue by alangdm** [ing-bank/lion#1153]
While implementing an overlay with OverlayController directly I found a bit of a quirk that I'm not sure if it could be considered a bug or not

## Expected behavior

Rendering content to contentNode after showing doesn't cause errors when the overlay hides.

## Actual Behavior

These are the steps to recreate the error:
1. Create an OverlayController instance with `trapsKeyboardFocus:true`
1. Show the controller
1. Render something to the contentNode using lit-html
1. Hide the controller
1. `Failed to execute 'removeChild' on 'Node'` error occurrs

As far as I could check this is because of the [ContainFocus helper](https://github.com/ing-bank/lion/blob/679d189ec4c8b6b568b13a0c9898a3b4e9feb4a7/packages/overlays/src/utils/contain-focus.js#L165) trying to remove the `tabDetectionElement` on disconnect when that element was removed when lit-html rendered content

Simple recreation:
https://webcomponents.dev/edit/1VLOBdgA9yjJ9e3JDjq6

## Possible Solutions

I was slightly hesitant to even file this issue because there are a couple of workarounds:

1. I think the lit-html@next will stop overwriting the content of the nodes it renders too so that should solve the problem
2. Adding a child to contentNode and using that child to render with lit-html also solves the problem

Even considering this, I think there are a couple of things that can be done to make the experience slightly nicer for OverlayController users:

1. Add the following code to control-focus's disconnect function

```js
if (rootElement.contains(tabDetectionElement)) {
  rootElement.removeChild(tabDetectionElement); 
} else {
  // just a random suggestion, thinking this is a utility the message might need to be less OverlayController-centric? 
  console.warn('Do not overwrite the contents of OverlayController\'s contentNode when using the trapsKeyboardFocus configuration option.'); 
}
```

2. Add the same warning from the code above to the docs for OverlayController

## Additional context

Version @lion/overlays v0.22.6

**Comment by jorenbroekema** [comment]
Hmmm tricky one. I am also not sure if it is a bug or if we say that you shouldn't overwrite / render to contentNode directly.

For possible solutions I believe solution `2. Adding a child to contentNode and using that child to render with lit-html also solves the problem` is the best solution for right now.

If you overwrite a trapsKeyboardFocus'd overlay controller's contentNode, you destroy the tabDetectionElement and some of the tab behaviour will stop working. @tlouisse  implemented this feature to make the contain focus behave properly in some edge cases.

If we indeed agree that users should not directly render to contentNode, but rather to a child, I definitely agree that we should create an error message for this. I'm not sure what the best place would be. Preferably, 
```js
render(
  html`<div>${snack.text}</div>`,
  contentNode
);
```
should then always cause an error throw, practically I'm not sure what the best way to accomplish this would be.

Maybe Thijs has some ideas about it, perhaps rendering to contentNode should just be fully allowed but then we need a mutation observer or something to listen to such events and restore the tabDetectionElement when needed.

**Comment by jorenbroekema** [comment]
Okay so we have this bug internally now as well and it happens essentially whenever you re-render your contentNode's inner template.

E.g.

```html
<lion-dialog>
  <my-content-node slot="content"></my-content-node>
</lion-dialog>
```

If you use LitElement and re-render your template, lit-html will remove the tab detection element, and then if you disconnect (e.g. close the dialog) you already get the error.

So one way to solve this is to create a MutationObserver that observes the contentNode, and re-inserts the tab detection element if it's missing. That would not require anything from our users and would prevent us having to put a rather weird arbitrary restriction on our users by saying they shouldn't render to their contentNode. 

We could also use MutationObserver to solve another bug in the process, which is that when you change your contentNode's content, we should rerun the containFocus util to re-compute focusable elements within the contentNode, which we currently are not doing. That would solve this bug as well at the same time. I will experiment with this and get back to you if we have something here.

**Comment by jorenbroekema** [comment]
Ah I forgot to close this one, we solved this now in the latest lion dialog / overlays :). Indeed uses a MutationObserver to reinsert the tab detection element when necessary.
