### ISSUE TITLE
[form-core] add meta info 'isTriggeredByUser' to model-value-changed event

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#1165]
Sometimes it can be helpful to detect whether a value change was caused by a user or via a programmatical change.
It would be helpful to have a normalized way of all types of FormControls to detect this.

### Use cases
A use case in which we need this info: https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html
(we need to detect whether the boxes where clicked by a user, in that case we want to store the previous indeterminate state, so we can restore that later).
https://github.com/ing-bank/lion/pull/1154

#### Other use cases:
Consumers sometimes listen to the (not publicly documented) `user-input-changed` event, but it was not designed for public consumption.

**Comment by jorenbroekema** [comment]
Also, what kind of meta data would you want to add? Is knowing that it was fired programmatically or with dispatchEvent through the isTrusted property not enough information?

**Comment by tlouisse** [comment]
By meta data I mean the detail object of a CustomEvent.
The `isTrusted` could be indirectly used for providing this (if the modelValue change was derived from a native event like 'input'/'change'/'click'), 
but that would break our tests (like `mimicUserInput()` etc.)

So the relevant distinction for us is between events fired ('change'/'input'/'click') and values set programmatically (`formControl.modelValue = 'xyz'`).

If we want to really make a distinction between events fired 'synthetically' and those triggered by a user from within the browser, we might want to add `isTrusted` later as well...

**Comment by tlouisse** [comment]
> Yeah would be helpful as an enhancement. Although for checkbox indeterminate, don't we want to do the same behaviour regardless of whether child checkboxes were triggered by a user or programmatically? I think we want to store state in both cases in most use cases. But perhaps there are use cases in design systems where they do something differently depending on user vs not user.

If we taje this example: https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html
Then if you select or deselect all checkboxes, the group toggle leads to all boxess toggling between all checked and all none checked (there is no indeterminate state).
If we do have indeterminate state and toggle between all, indeterminate and none (leading to programmatic changes of the subCheckboxes) then we would always lose the previous indeterminate state.

I hope the explanation is clear, or else you need to checkout my branch and remove this line: https://github.com/ing-bank/lion/blob/feat/checkbox-indeterminate-enhancements/packages/checkbox-group/src/LionCheckboxIndeterminate.js#L35

**Comment by jorenbroekema** [comment]
I still don't see why isTrusted isn't enough information already. What would the metadata contain and why would it be helpful? I see isTriggeredByUser as a polar opposite of isTrusted, making it completely redundant, since isTriggeredByUser is always the opposite of isTrusted?

For the checkbox, you just need to write a line that catches when the indeterminate was toggled (`ev.detail.formPath[0] === this`), and then when you toggle the subcheckboxes as a consequence, don't save state, knowing the event came from the indeterminate checkbox itself. 

I don't see how the suggested isTriggeredByUser meta data is going to help here. Also, if you toggle the indeterminate state programmatically you want the same behaviour: don't save state of the subcheckboxes because they were toggled through the parent indeterminate. So you want this behavior of not storing state even if it wasn't triggered by the user.

**Comment by jorenbroekema** [comment]
I suppose my confusion is centered around this question https://github.com/ing-bank/lion/pull/1167/files#r552442368

**Comment by tlouisse** [comment]
> I still don't see why isTrusted isn't enough information already. What would the metadata contain and why would it be helpful? I see isTriggeredByUser as a polar opposite of isTrusted, making it completely redundant, since isTriggeredByUser is always the opposite of isTrusted?

- `model-value-changed` is the SSOT wrt informing state changes of the internal form(Control) model. Currently it does not discriminate between state changes originating from user or developer interaction. Hence, the need for `isTriggeredByUser`.
(We don't want people to listen to `input`, `change`, `user-input-changed` (latter should be considered private), since they are not consistent through all FormControls (especially those completely built from aria widgets) and browsers) 
- the only difference between `isTrusted` and `isTriggeredByUser` is that the latter will be true for events dispatched programatically (I would not consider them polar opposites). 
For our use cases, this is what we want. We would have to go through great (hacky) lengths to make our tests work otherwise, plus `isTrusted` is not supported by IE.


> For the checkbox, you just need to write a line that catches when the indeterminate was toggled (ev.detail.formPath[0] === this), and then when you toggle the subcheckboxes as a consequence, don't save state, knowing the event came from the indeterminate checkbox itself.

I would have to run your example to see what you mean exactly, but my guess is that if you click the indeterminate checkbox, it will sync its state with all its subCheckboxes. It will then lead to all subCheckboxes firing their events. You will need to listen to those events to set the saved indeterminate state for all checkboxes, but **ONLY** when they originate from user interaction.
So it's not about knowing the event came from a child or not, but about how that event came to be.
In this whole story it is irrelevant whether the checkbox-indeterminate was triggered programatically or by a user.

So imagine:
**A.**
```
[-]
  [x]
  [x]
  []
```
The captured indeterminate state for the toggle would be [x,x,]

Now the user clicks on the indeterminate checkbox (or it's toggled programatically):
**B.**
```
[x]
  [x]
  [x]
  [x]
```
Events are sent up from the checkboxes, but they should not affect the captured indeterminate state.
After two more toggles we end up with **A** again.

But what if we start again from **A** and now click the bottom checkbox? We will end up with **B** again.
The difference this time is that it does affect the captured indeterminate state (since it was a user action).
If we now toggle the checkbox-indeterminate, it will ignore the captured indeterminate state alltogether.

See: https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html

**Comment by jorenbroekema** [comment]
Yea that makes it a little more clear.

My approach was that state is stored on the indeterminate checkbox only when model-value-changed event originates from child checkboxes (which you can check on ev.detail.formPath). If it originates from the indeterminate checkbox itself it will indeed sync its children which will then again fire model-value-changed events and you don't want that to cause a state-store. The way I fix that currently is by setting a flag "this.settingOwnState" to true, and setting it back to false after this.updateComplete has resolved. But your method will also work indeed, I'm not sure which method is cleaner.

**Comment by tlouisse** [comment]
Yeah indeed, you can also add some state, but `__settingOwnState` basically means  `!isTrigeredByUser`.
And adding this info is something that benefits multiple cases, I think it's very valuable information for App Developers.
I would use the event info inside the checkbox-indeterminate, so we have one single method of solving these things, incorporated into the core.
But this is actually something I felt was missing for a long time. So the main use case is a normalization layer:
- use `model-value-changed` as a single source of truth event. 
There should be no use cases for (inconsistently implemented (cross browser)) events like 'input'/'change'/'user-input-changed' etc.


Rethinking the polar opposites thing: I think you're actually right there:) Mentioning the `isTrusted` as an anology does not make it clearer ('the lens I was looking through' only covers some edge cases). I will update thar in the docs.

**Comment by tlouisse** [comment]
Updated the docs and changelog:

```
'isTriggeredByUser' meta data in model-value-changed event
  Sometimes it can be helpful to detect whether a value change was caused by a user or via a programmatical change.
  This feature acts as a normalization layer: since we use `model-value-changed` as a single source of truth event for all FormControls, there should be no use cases for (inconsistently implemented (cross browser)) events like 'input'/'change'/'user-input-changed' etc.)
```

**Comment by jorenbroekema** [comment]
Looks good to me then :) will review the PR and then after it's merged we can rebase and update the checkbox branch to use it 👍

**Comment by tlouisse** [comment]
Thanks 💪
