### ISSUE TITLE
[localize] The € sign is put after the number in Dutch

### ISSUE THREAD

**Issue by bverhoef** [ing-bank/lion#117]
In the current situation the formatNumber displays the amount of 200.000 euro in Dutch:

- 200.000 EUR (this is correct)
- 200.000 € (this is incorrect, it should be € 200.000)

**Comment by bashmish** [comment]
Side question since we also have a MR to support negative numbers: what should be the negative version of `€ 200.000`?

**Comment by bverhoef** [comment]
It should be this. € -200.000

https://www.reference.com/business-finance/euro-sign-before-after-number-13773f16a6f25d98

**Comment by bashmish** [comment]
Will you be willing to provide a merge request for this?

**Comment by bverhoef** [comment]
> Will you be willing to provide a merge request for this?

See #119

**Comment by Jules700m** [comment]
I found this regarding the isocode: 

https://en.m.wikipedia.org/wiki/ISO_4217 
https://english.stackexchange.com/questions/124797/how-to-write-negative-currency-in-text 

indicating it should be - €6.680

**Comment by bverhoef** [comment]
I think that it is different per language:

See:
https://nl.wikipedia.org/wiki/Euroteken 
https://taaladvies.net/taal/advies/vraag/1178
https://taaladvies.net/taal/advies/vraag/1198/euro_12_12/

Enkele speciale gevallen in het Standaardnederlands:

negatieve bedragen: € –2,00 (This should be done default by the localize function)
Positieve bedragen: € +2,00 (This should be done default by the localize function)
Korting: –€ 2,00 (I think this should be handled by the programmer itself in his page.)
Bijkomende kosten: +€ 2,00.  (I think this should be handled by the programmer itself in his page.)
