### ISSUE TITLE
[form-core] enhance isTriggeredByUser for arrow navigation

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#1173]
## Expected behavior

When I press arrow up/down/left/right in listbox (descendants), `isTriggeredByUser` should be true.
Enter and space should be covered as well (I think they trigger a click and therefore should be covered already, but we should add tests)

**Comment by jorenbroekema** [comment]
Not having it here can probably be considered as a bug, I think most users would expect this meta info to also work for other interactions than just 'click'.
