### ISSUE TITLE
Tabs - selectedIndex doesn't work as an attribute

### ISSUE THREAD

**Issue by georges-gomes** [ing-bank/lion#1182]
## Expected behavior

In tabs 0.3.1 I used to do
`<lion-tabs  selectedIndex="2">`
`selectedIndex` as attribute.

## Actual Behavior

In latest
```
    "@lion/core": "^0.13.7",
    "@lion/tabs": "^0.5.13",
```
Doesn't work anymore.

Is it only properties now?

Thanks

**Comment by jorenbroekema** [comment]
Hey, I think this may have worked as a side-effect of Lit perhaps? I remember doing some workshops before and saying "hey look this attribute will not reflect to the property" and then I noticed that it actually did reflect to the property, confusingly so.

I'm still not really sure why that worked the way it did, but it sure seemed like unintended behaviour. 

Either way, from `lion-tabs` version 0.5.0, the `selectedIndex` property now reflects to the `selected-index` attribute, so:

```html
<lion-tabs selected-index="2">
```

should work 👍  I probably should have added that more explicitly in the changelog.

**Comment by georges-gomes** [comment]
But I tested 0.5.13 and it doesn't work with attribute.

Am I missing something?

**Comment by jorenbroekema** [comment]
Yeah, in your code snippet you do `selectedIndex` but the attribute you need is `selected-index`

**Comment by georges-gomes** [comment]
🤦‍♂️of course ! Thanks for your help!
