### ISSUE TITLE
[comobobox]: Registration could not finish when used in dialog

### ISSUE THREAD

**Issue by palash2601** [ing-bank/lion#1216]
## Expected behavior

Combobox component should not throw any error when used in dialog and all APIs should work as expected

## Actual Behavior

When combobox component is plugged into dialog component, below error is thrown
```
ChoiceGroupMixin.js:143 Uncaught (in promise) Error: Registration could not finish. Please use await el.registrationComplete;
    at ChoiceGroupMixin.js:143
```
Since this error is thrown, `model-value-changed` event is not fired
Issue recreated in this pull request
https://github.com/ing-bank/lion/pull/1215

**Comment by palash2601** [comment]
While debugging I found that the same flow works for `radio-group`

`radio-group` extends `FormGroupMixin` which resolves the registration promise in connectedCallback.
https://github.com/ing-bank/lion/blob/78df6e7181f0c882f6520dffd8b69e1b44ae8a3e/packages/form-core/src/form-group/FormGroupMixin.js#L170

Doing so in LionCombobox component also fixes this issue. But I am not sure if this is the correct solution.

**Comment by tlouisse** [comment]
Seems to be related to https://github.com/ing-bank/lion/issues/1064

A quick look shows me:
- ChoiceGroupMixin executes in connectedCallback:
```js      
      // Double microtask queue to account for Webkit race condition
      Promise.resolve().then(() =>
        Promise.resolve().then(() => this.__resolveRegistrationComplete()),
      );
```
      
- FormGroupMixin executes in connectedCallback:
```js
Promise.resolve().then(() => this.__resolveRegistrationComplete());
```

There are three categories of components:
1. listbox/selectRich/combobox depend on **ChoiceGroupMixin**
2. fieldset/form depend on **FormGroupMixin**
3. radioGroup/checkboxGroup depend on **ChoiceGroupMixin and FormGroupMixin**

If FormGroupMixin is applied, the promise will always be resolved one microtask sooner, before the disconnectedCallback rejects the promise.
Thus, the problem most likely occurs in all components of category 1.
If we would resolve the Promise there 1 microtask sooner inside ChoiceGroupMixin, there would be a race condition in Webkit according to the comment, so adding the line you suggested in LionCombobox would create this race condition again (which is apparently only a problem in category 1 components).
I never worked on this latest version of registration logic myself, but maybe @daKmoR knows a solution for this?

**Comment by jorenbroekema** [comment]
We do:

```js
disconnectedCallback() {
  super.disconnectedCallback();

  if (this.registrationComplete.done === false) {
    this.__rejectRegistrationComplete();
  }
}
```
I am actually not entirely sure why we go out of our way to throw a fatal error when disconnectedCallback happens before registration is complete. We don't have a test for this error being thrown so I don't really understand its purpose.

We could:
- Just not reject registration here, since it seems to not do anything other than throw.. perhaps just remove the reject entirely if it has no purpose.
- Await registration in the disconnectedCallback, but again I don't see the purpose.
- Delay by a promise (microtask) like we do in connected, again, not sure what the purpose would be.

**Comment by jorenbroekema** [comment]
Small note: whatever the fix we do, we should align FormGroupMixin's logic as well.

**Comment by palash2601** [comment]
Any updates on this issue?
