### ISSUE TITLE
Error messages not displayed when they are in a dialog

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#1220]
## Expected behavior

When you have a form in a dialog, validation does not seems to be applied.

## Actual Behavior

All reproduction is in this snippet:

https://webcomponents.dev/edit/2f3BG1dwJEr0Y4C7kiZD/

## Additional context

dialog 0.10.0 and input 0.11.0

**Comment by jorenbroekema** [comment]
Thanks for the repo. It actually has `submitted` state set correctly, as well as `hasFeedbackFor` but it does not set `showsFeedbackFor` correctly. Need to investigate why.
