### ISSUE TITLE
[Comobox]: ShowAllOnEmpty property doesn't work on focus

### ISSUE THREAD

**Issue by akhudiakov97** [ing-bank/lion#1226]
## Expected behavior

When the showAllOnEmpty property is set to true, all dropdown options in the Combobox component should be visible.

## Actual Behavior

Dropdown options in the Combobox component are visible only after typing in the search field

https://lion-web-components.netlify.app/?path=/story/forms-combobox--show-all-on-empty

## Additional context
@lion/combobox version 0.1.24

**Comment by tlouisse** [comment]
It's currently implemented in such a way that it only stays opened after user interaction (except for focus) has taken place.

Here you see an example that has the behavior you are looking for:
https://lion-web-components.netlify.app/?path=/story/forms-combobox-extensions--google-search

You can achieve this in your extension via:

```js
  /**
   * @enhance LionCombobox
   */
  _showOverlayCondition(options) {
    return this.focused || super._showOverlayCondition(options);
  }
```
See: https://github.com/ing-bank/lion/blob/master/packages/combobox/docs/google-combobox/google-combobox.js#L447

I think it makes sense to make this behavior the default for `showAllOnEmpty ` 👍

**Comment by akhudiakov97** [comment]
Thanks a lot for your help, it works, and I also think it will be great to make this behavior the default for `showAllOnEmpty`.

Have a nice day !)

**Comment by tlouisse** [comment]
No problem, you too :) 

I will leave this issue open, so we can decide to make it the default behavior.

**Comment by jorenbroekema** [comment]
I also think it makes sense, are we okay with committing to that decision and making this "open for contributions" :)? then I'll move it to discussions
