### ISSUE TITLE
ing-form - prefilled radiogroup is set to dirty

### ISSUE THREAD

**Issue by tush** [ing-bank/lion#1241]
## Expected behavior

dirty flag in ing-form should be 'false' even when initialised with pre-filled value in lion-checkbox-group or  lion-radio-group via serializedValue. 

## Actual Behavior

dirty flag in ing-form is set to 'true' even when initialised with pre-filled value in lion-checkbox-group or  lion-radio-group via serializedValue. 

https://webcomponents.dev/edit/kpZmz1CJN580OaXsk56f?pm=1

* In example above, notice that the form has **dirty** flag set to 'true'. This happens if we pass pre-filled data (serializedValue) to form especially when using **lion-checkbox-group** or **lion-radio-group**.

* In example above, if we remove 'serializedValue', notice that the form has dirty flag set to 'false'

```javascript
<lion-form .serializedValue=${this.initialData}>
```

## Additional context

Link above can be used to view the behavior.

**Comment by tlouisse** [comment]
Hi @tush is this still an issue?

In the link, `.serializedValue` was already removed. When I add: 
```html
<lion-form .serializedValue="${{"full_name":{"first_name":"","last_name":""},"datepicker":"2020-12-12","bio":"","money":"","iban":"","email":"","checkers":[],"dinosaurs":"","lyrics":"1","range":2.3}}"
```
I still see that the form does not initialize as `dirty`...

I also added this test: https://github.com/ing-bank/lion/pull/1313/files#diff-e3ef11b14acc5fb8afe1ae5515dfc5d2c409766985fa544cc4060a3fa6be7978R674

**Comment by tlouisse** [comment]
After speaking to @tush and further investigation: it fails for radio (groups): https://github.com/ing-bank/lion/pull/1313/files#diff-ed5b84d0b04e88508b30acb7e205f20c2609f7e36896c8e178a386f7316aca90R72

**Comment by tlouisse** [comment]
Fixed by https://github.com/ing-bank/lion/pull/1313
