### ISSUE TITLE
Documentation of overlays configuration is incorrect

### ISSUE THREAD

**Issue by AndreeaMoise** [ing-bank/lion#1259]
It seems that the first part of the description of "isBlocking" is copied from the "hasBackdrop" section.

![image](https://user-images.githubusercontent.com/24620946/111159476-6cfde080-8599-11eb-9acf-07d9f7a34282.png)

**Comment by jorenbroekema** [comment]
Aah good catch, interesting that no one saw this before, we've had this situation since forever. I went back in history and we never actually had any explaining docs for isBlocking.

If someone wants to create a pull request to add some docs, happy to accept!

**Comment by tlouisse** [comment]
I don't know who we should thank, but this has been solved in the meantime: https://lion-web.netlify.app/docs/systems/overlays/configuration/#isblocking
