### ISSUE TITLE
lion-checkbox-group examples not displaying correctly - Chrome on Mac

### ISSUE THREAD

**Issue by JEAxero** [ing-bank/lion#1269]
Just started using the new site for Lion documentation. (While you work out the issues, it would be great if we could have a fallback to the old storyboard...)

Anyway, when I look at this page:
https://lion-web.netlify.app/components/inputs/checkbox-group/features/

I don't see running examples (though the code does show when I click on "Show code"). 

See screenshot.
![Screen Shot 2021-03-16 at 3 46 46 PM](https://user-images.githubusercontent.com/4666698/111371463-d18b6f00-866f-11eb-93bb-f4ccc45c9325.png)

**Comment by jorenbroekema** [comment]
Hey, we missed marking a side effect so it didn't get bundled.

We prefer not having a fallback, incentivises people more to report bugs on the static site, and reduces the amount of netlify build time we use to stay within the budget of our netlify plan.

**Comment by JEAxero** [comment]
Thanks for fixing the new site! I can understand wanting to give us incentive to use (and report issues) with the new site. Thanks for the quick fix!
