### ISSUE TITLE
[lion-checkbox-group]: Defining .serializer does not works

### ISSUE THREAD

**Issue by palash2601** [ing-bank/lion#1275]
## Expected behavior

When serializer is defined on `checkbox-group` it should get called

## Actual Behavior

serializer defined on `checkbox-group` it NOT getting called 

## Additional context
This issue is there for all the components which extends ChoiceGroupMixin, like check-box-group and combobox.

The serlialedValue getter defined in this Mixin does not makes call to serializer
https://github.com/ing-bank/lion/blob/master/packages/form-core/src/choice-group/ChoiceGroupMixin.js#L68

Proposed solution: Add below code in serializedValue getter
```js
  if(this.serializer) {
    return this.serializer(this.modelValue);
  }
```

**Comment by tlouisse** [comment]
Nice @palash2601 . You could do the proposal we discussed.
What we should also keep in mind is that we need to support a separate `deserializer` as well.

So modelValue < = > serializedValue

**Comment by tlouisse** [comment]
Closing, see: https://github.com/ing-bank/lion/pull/1277
