### ISSUE TITLE
[core] Error importing @lion/core when using Skypack

### ISSUE THREAD

**Issue by jdelight** [ing-bank/lion#1296]
## Expected behavior

It should be possible to import Lion components using Skypack CDN. Specifically using something like:

```js
import { LionButton } from 'https://cdn.skypack.dev/@lion/button';

export class MyButton extends LionButton {...}
```

## Actual Behavior

When importing a Lion component, an error is thrown from the @lion/core package (see below):

https://webcomponents.dev/edit/unVMnXuNtEP7u7GxV3Ei/src/index.js

The error thrown is:  
```
This is not a valid import according to the package.json "exports" field. (Imported by "@lion/core").
```

## Additional context

Although the error references the lit-html package, I'm raising this here as opposed to on lit-html because importing lit-html via Skypack seems to work as expected (see below).

https://webcomponents.dev/edit/eXiqlfRlCw0dlVLJmpXP/src/index.js

**Comment by tlouisse** [comment]
Apparently `lit-element` does not have export maps and `@lion/core` does. Maybe it helps to look into this solution: https://polymer.slack.com/archives/CJGFWJN9J/p1617818449082900?
(if it does not really needs to be Skypack)

**Comment by jdelight** [comment]
Thanks @tlouisse - that's lead me to this example from @jorenbroekema : https://codepen.io/Falx/pen/BapwYgK?editors=1000 
Which is pretty much what I was hoping to explore - zero bundle approach. Thanks.

**Comment by tlouisse** [comment]
Nice, glad we could help :)
