### ISSUE TITLE
Strange race condition on ChoiceGroupMixin

### ISSUE THREAD

**Issue by tblaisot** [ing-bank/lion#1308]
## Expected behavior

I want to use lion webcomponents insode angular, especially the forms becauses they are awesome.
Once done the mapping beetween Angular forms internals and lion checkbox groups, I expect no errors.

## Actual Behavior

Even if i am reporting this bug in angular i could imagine other framework or vanilla JS can lead to the same race condition...

I got the following error just during form initialization
```
core.js:6162 ERROR TypeError: Cannot read property 'includes' of null
    at HTMLElement._setCheckedElements (ChoiceGroupMixin.js:290)
    at HTMLElement.set modelValue [as modelValue] (ChoiceGroupMixin.js:61)
```

I have tracked the bug to this code in ChoiceGrounpMixin.js L54:

```
if (this.__isInitialModelValue) {
        this.__isInitialModelValue = false;
        this.registrationComplete.then(() => {
          this._setCheckedElements(value, checkCondition);
          this.requestUpdate('modelValue', this.__oldModelValue);
        });
      } else {
        this._setCheckedElements(value, checkCondition);
        this.requestUpdate('modelValue', this.__oldModelValue);
      }
```

What append is that the `__isInitialModelValue` is set the false and the first request update is delayed, but before it can be resolved the else part is called and model is set correctly and some time after, the model is changed back to the original value.

I can prevent the error stack bug by changing this code in `_setCheckedElements(value, check)` this lead to inconsistent behaviour. 
```
let valueIsIncluded = value?.includes(this.formElements[i].modelValue.value) || false;
``` 

Here is a example project. You MUST use yarn to install.

https://github.com/tblaisot/lion-form-demo-angular

```
yarn install
yarn run start
```

## Additional context

    "@lion/button": "^0.10.1",
    "@lion/calendar": "^0.14.1",
    "@lion/checkbox-group": "^0.15.3",
    "@lion/combobox": "^0.4.2",
    "@lion/core": "^0.15.0",
    "@lion/fieldset": "^0.17.3",
    "@lion/form": "^0.9.3",
    "@lion/form-core": "^0.10.2",
    "@lion/input": "^0.12.3",
    "@lion/input-amount": "^0.11.2",
    "@lion/input-date": "^0.10.3",
    "@lion/input-datepicker": "^0.20.3",
    "@lion/input-email": "^0.11.3",
    "@lion/input-iban": "^0.13.3",
    "@lion/input-range": "^0.7.3",
    "@lion/input-stepper": "^0.3.3",
    "@lion/listbox": "^0.6.3",
    "@lion/radio-group": "^0.14.3",
    "@lion/select": "^0.10.3",
    "@lion/select-rich": "^0.23.3",
    "@lion/switch": "^0.14.3",
    "@lion/textarea": "^0.10.3",

**Comment by tblaisot** [comment]
This morning I tried to remove the async part of the updates.

I found such code in ChoiceGroupMixin and FormGroupMixin.

With thoses modifications i have no errors and the form have the propers values :tada: .

I can't understand if this is necessary or not for lit-element usage ? I have done some tests in angular with async update of the form after 3 seconds and I have found that the values are properly passed to the component but the second update with a value is wiped by the first which as no value (because au angular form...)

I must say that i don't use lion-form because i don't have an usage for it, because i will use angular forms and validations (but i use the feedback for error reporting because of your amazing work for a11y)

Here are my patches to better explain my modifications:
```
--- node_modules/@lion/form-core/src/choice-group/ChoiceGroupMixin.js 1985-10-26 09:15:00.000000000 +0100
+++ node_modules/@lion/form-core/src/choice-group/ChoiceGroupMixin.js 1985-10-26 09:15:00.000000000 +0100
@@ -53,10 +53,10 @@

       if (this.__isInitialModelValue) {
         this.__isInitialModelValue = false;
-        this.registrationComplete.then(() => {
+        // this.registrationComplete.then(() => {
           this._setCheckedElements(value, checkCondition);
           this.requestUpdate('modelValue', this.__oldModelValue);
-        });
+        // });
       } else {
         this._setCheckedElements(value, checkCondition);
         this.requestUpdate('modelValue', this.__oldModelValue);
@@ -89,10 +89,10 @@

       if (this.__isInitialSerializedValue) {
         this.__isInitialSerializedValue = false;
-        this.registrationComplete.then(() => {
+        // this.registrationComplete.then(() => {
           this._setCheckedElements(value, checkCondition);
           this.requestUpdate('serializedValue');
-        });
+        // });
       } else {
         this._setCheckedElements(value, checkCondition);
         this.requestUpdate('serializedValue');
@@ -116,9 +116,9 @@

       if (this.__isInitialFormattedValue) {
         this.__isInitialFormattedValue = false;
-        this.registrationComplete.then(() => {
+        // this.registrationComplete.then(() => {
           this._setCheckedElements(value, checkCondition);
-        });
+        // });
       } else {
         this._setCheckedElements(value, checkCondition);
       }
@@ -286,6 +286,6 @@
     _setCheckedElements(value, check) {
       for (let i = 0; i < this.formElements.length; i += 1) {
         if (this.multipleChoice) {
-          let valueIsIncluded = value.includes(this.formElements[i].modelValue.value);
+          let valueIsIncluded = value?.includes(this.formElements[i].modelValue.value) || false;

           // For complex values, do a JSON Stringified includes check, because [{ v: 'foo'}].includes({ v: 'foo' }) => false
           if (typeof this.formElements[i].modelValue.value === 'object') {

```
```
--- node_modules/@lion/form-core/src/form-group/FormGroupMixin.js        1985-10-26 09:15:00.000000000 +0100
+++ node_modules/@lion/form-core/src/form-group/FormGroupMixin.js      2021-04-02 10:56:48.340492873 +0200
@@ -88,9 +88,9 @@
     set modelValue(values) {
       if (this.__isInitialModelValue) {
         this.__isInitialModelValue = false;
-        this.registrationComplete.then(() => {
+        // this.registrationComplete.then(() => {
           this._setValueMapForAllFormElements('modelValue', values);
-        });
+        // });
       } else {
         this._setValueMapForAllFormElements('modelValue', values);
       }

```

**Comment by tlouisse** [comment]
Hi,

Great to hear that your enthousiastic about Lion 🦁 

Really appreciated that you took the time to look into the root cause.
Getting rid of the pending `registrationComplete` is not feasible I think, since we need to know when all child options have registered.

I think the problem partly lies in the fact that `ControlValueAccessor` (that is implemented by `LionWcModelValueAccessorDirective`, you ngModel directive) sets the value `null` on init. I think our FormControls should be able to handle `null` and `undefined` values, so 
```js
let valueIsIncluded = value?.includes(this.formElements[i].modelValue.value) || false;
```
would be a good way to mitigate this (or maybe we should even uncheck all children when these values are provided)

Then for the other problem, maybe we could do:

```js
      if (this.__isInitialModelValue) {
         // Ideally, cancel pending requests (waiting for Promise below) here
         this.registrationComplete.then(() => {
           this._setCheckedElements(value, checkCondition);
           // This will make sure that the else branch is not hit before the modelValue is actually initialized
           this.__isInitialModelValue = false;
           this.requestUpdate('modelValue', this.__oldModelValue);
        });
       } else {
         this._setCheckedElements(value, checkCondition);
         this.requestUpdate('modelValue', this.__oldModelValue);
     }
```

I didn't test wether this works. I will continue looking into this next Tuesday :)

**Comment by tblaisot** [comment]
Thanks for responding.

I have tried your solution and it work for me (in angular) but i didn't tested it in lit-element.

I also tried to implement a solution to cancel pending promise but doing so i found this in connectedCallback of ChoiceGroupMixin:
```js
      // Double microtask queue to account for Webkit race condition
      Promise.resolve().then(() =>
        Promise.resolve().then(() => this.__resolveRegistrationComplete()),
      );
```
It may explain why I wasn't able to simply solve the problem by delaying the angular writeValue, I think I should try to use a similar technique :)

**Comment by tlouisse** [comment]
Nice that it works :) It works in our code base as well. I added this pull request: https://github.com/ing-bank/lion/pull/1312. See the tests for more info.

By canceling the pending promise was actually meant that it shouldn't handle all pending values, only the last.

```js
// before registrationComplete
el.modelValue = null; // pending
el.modelValue = ['x']; // pending

// after registrationComplete
// [1] handles pending modelValue null
// [2] handles pending modelValue ['x']
```

So in the example above, it only has to set the latest pending modelValue ([2]).
We could later do a small perf improvement for this. Currenlty, the fact that it first handles pending [1] doesn't have functional implications.

**Comment by tlouisse** [comment]
@tblaisot A question btw: would it be possible to also couple the validation in a similar way you did with `[(ngModel)]`?
I really like how you integrated that in Angular, maybe it would be possible to do something similar for validation?

At least, there's quite some work involved in making validation accessible as well:
- aria-invalid on the right dom element (input/textbox/select or element with a certain role)
- aria-required on the right dom element
- aria-describedby relations from the input to the validation message
- aria-live="polite/assertive" on the validation message

**Comment by tblaisot** [comment]
@tlouisse I think we can connect the 2 using the Validator interface to push up the errors if there is event for validations in @lion I will need this for component with internal validation, like date, iban, email....

To make the information go down I need to make some tests but I suppose I can at least create a custom lion validator to pass the status down to the component, but not sure it will be enough.

At first I was thinking about declaring error messages only in angular for simplicity, using the <lion-validation-feedback> to have the aria-live and aria-describedby, but i wasn't thinking about the other two.

I will try all thoses ideas and update my sample if it work :)

**Comment by tlouisse** [comment]
Nice :)

There's also a small edge case (an upcoming fix) wrt aria-live: https://github.com/ing-bank/lion/issues/1161

Assuming you want to use template driven forms with validator directives, you could try something like the code below that wraps Angular validators.
I'm by no means an Angular expert, so the code below should be regarded as pseudo code :)

```js
import { Validator as LionValidator } from '@lion/form-core';

/**
 * @param {function} angularValidatorFn
 * @param {array} args
 * @param {string} message
 */
export function createLionValidator(angularValidatorFn, args, message) {
   // https://angular.io/api/forms/Validators#minlength
   const validationFn = angularValidatorFn(...args);
   return class extends LionValidator {
      execute(modelValue) {
        return validationFn(modelValue);
      }
      
      static _getMessage() {
         return message;
      }
   }
}
```

```js
import { Directive, ElementRef } from '@angular/core';
import { Validators } from '@angular/forms';
import { createLionValidator } from './createLionValidator.js';

@Directive({
  selector: '[myValidator]'
})
export class MyValidatorDirective {
    constructor(el: ElementRef) {
       const myMinLengthValidator = createLionValidator(Validators.minlength, 4, 'Please provide a minimum of 4 chars');
       el.validators.push(new myMinLengthValidator());
    }
}

```
