### ISSUE TITLE
[switch] registration failing

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#1317]
## Expected behavior

lion-switch should end up in `.formElements` after registration
See https://github.com/ing-bank/lion/pull/1316

**Comment by daKmoR** [comment]
huh I thought a switch is not supposed to be part of a form? 

we have this on our docs page
> Switch is not a Checkbox in disguise and should not be used as part of a form.

is that no longer true? 🤔

**Comment by tlouisse** [comment]
I think that's more a usage recommendation, because it's usually used in setting pages etc. that are not submitted to a backend via a form.
But I think more (probably most) controls can be used outside a form (listbox, select etc.).

I think a switch is a control (see https://github.com/WICG/open-ui/issues/81) that is usually placed outside (but should not be disallowed to be used within) a form.

Since it extends LionField/FormControl it gets all the interaction behaviors as described in the link and is thus compatible with the form.

**Comment by tlouisse** [comment]
This was a false alarm, everything works fine... Forgot to import the wc definition :)
