### ISSUE TITLE
[input-datepicker] formatter does not work for pre-filled inputs 

### ISSUE THREAD

**Issue by CigdemGurdal** [ing-bank/lion#1349]
## Expected behavior

When modelValue is set with a default value, formatting should work.

## Actual Behavior

Formatter is not applied for the default value when the screen is rendered for the first time. 

https://webcomponents.dev/edit/VN1AKgpTlGmjVhBfDShH/src/index.stories.js

## Additional context

input-datepicker - "0.19.1"

**Comment by tlouisse** [comment]
Thanks for the issue. The formatting properties are not 'order indepent' yet.

Here, I defined the formatter before the modelValue and then it works:
https://webcomponents.dev/edit/LtIxk2Ewk1i0pGqQWSE7/src/index.stories.js

**Comment by tlouisse** [comment]
Closing this one and added **member order independence** here: https://github.com/ing-bank/lion/discussions/787
