### ISSUE TITLE
[ajax] Race condition in cache

### ISSUE THREAD

**Issue by ruphin** [ing-bank/lion#1368]
There is currently a race condition in the caching mechanism that can leak cached responses after the cache is cleared. 

## Expected behavior

If the `cacheIdentifier` changes, the cache is reset, and all new requests will not be served data from previous requests.

## Actual Behavior

If the `cacheIdentifier` changes while a request is in-flight (it is already on the network, but has not returned a response yet), the response will be stored in the new cache using the new cacheIdentifier.

This creates a security issue, if the `cacheIdentifier` is associated with user sessions. If a request is submitted with credentials from user session A, and while the request is in-flight, the system changes to user session B, the response from the request will be cached with the `cacheIdentifier` of user session B. If user B will make the same request again in the future they will be presented with the data from user A.

## Proposed solution

The requestInterceptor should use the `getCacheIdentifier()` function to obtain the identifier that is current at the time the request is made. It should store this `cacheIdentifier` on the request itself. The responseInterceptor must then use the `cacheIdentifier` that was stored with the request.

I am working on a fix for this issue.

**Comment by daKmoR** [comment]
closed via https://github.com/ing-bank/lion/pull/1385
