### ISSUE TITLE
[combobox] Expected behaviour different than the one shown in docs

### ISSUE THREAD

**Issue by VilleFTW** [ing-bank/lion#1383]
I'm trying to use the <lion-combobox> in a blank project, however, the expected behaviour is much different than the one being shown in the docs.

## Expected behavior

![image](https://user-images.githubusercontent.com/18228750/118501042-a1705300-b728-11eb-9061-c4d7b22950c7.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/18228750/118501580-2a878a00-b729-11eb-8434-3b4dead3f5ba.png)

Not getting the expected behaviour. The code used looks roughly the same as the one shows in  the docs

`   <lion-combobox
              label="Vegetable"
              name="veggie"
              autocomplete="inline"
              matchMode="all">
             <lion-option .choiceValue=${'Apple'}>Apple</lion-option>
             <lion-option  .choiceValue=${'Artichoke'}>Artichoke</lion-option>
             <lion-option .choiceValue=${'Asparagus'}>Asparagus</lion-option>
             <lion-option .choiceValue=${'Banana'}>Banana</lion-option>
             <lion-option .choiceValue=${'Beets'}>Beets</lion-option>
</lion-combobox>`

**Comment by tlouisse** [comment]
Can you maybe make a faling reproduction. For instance on webcomponents.dev or stackblitz?

**Comment by VilleFTW** [comment]
> Can you maybe make a faling reproduction. For instance on webcomponents.dev or stackblitz?

Should be available [here](https://webcomponents.dev/edit/osBDE1E8y0QHaEx6rn2k)

**Comment by VilleFTW** [comment]
My apologies. The reason it wasn't working so far it's because I was not  importing `<lion-option>` as well. Perhaps it should be pointed out in the docs.

**Comment by tlouisse** [comment]
> My apologies. The reason it wasn't working so far it's because I was not importing `<lion-option>` as well. Perhaps it should be pointed out in the docs.

Ah. Apologies accepted :)
Yeah, you need to import the webcomponent defintion indeed. Would be good to add to the docs.
Any place you would expect it? 
We could maybe add it here: https://lion-web.netlify.app/components/inputs/combobox/overview/#installation?

**Comment by VilleFTW** [comment]
That would be great indeed!

Kind Regards,
Sorin Bighiu
