### ISSUE TITLE
Prettier config doesn't seem to be applied

### ISSUE THREAD

**Issue by MatthieuLebigre** [ing-bank/lion#1388]
For the sake of simplicity, I narrow down my example to a specific piece of code, but this applicable across all the repository:

In *packages\combobox\src\LionCombobox.js* :

``` js
  get _listboxNode() {
    return /** @type {LionOptions} */ ((this._overlayCtrl && this._overlayCtrl.contentNode) ||
      Array.from(this.children).find(child => child.slot === 'listbox'));
  }
```

You can run the following command to facilitate the test:

`npx prettier "**/LionCombobox.js" --write`

## Expected behavior

When running `npx prettier "**/LionCombobox.js" --write` on master branch, I expect to have no changes

## Actual Behavior

When running `npx prettier "**/LionCombobox.js" --write` on master branch, prettier is changing the code into:

```js
  get _listboxNode() {
    return /** @type {LionOptions} */ (
      (this._overlayCtrl && this._overlayCtrl.contentNode) ||
        Array.from(this.children).find(child => child.slot === 'listbox')
    );
  }
```

I believe the prettier configuration is somehow not correctly applied in the CI and maybe locally for some contributors.

If you try this specific piece of code on the prettier playground, it formats the code as my second snippet. See [here for the playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAID0AVIbgAIwCeADnLsADICW0A8lTM1AM4C+uh+XAAohMABaMuAOgD6EAG5xUAGwCGFAMIwVuAGS7c4ybIVK1m7cqmRYCGADkIAEzgBKXAB8PAHTy5cAIKoqOpSAGaoEAC2ohLSYBLKTuhQruGMUE5CCYxJuAC8AHy4OUlSXMoQMAX5+bgA5MqSMABGEAAe9a6uANy+-iAANCAQ7JxcyKCqwRAA7gAK0wgTKKryEIxOQyAtIWAA1hgAylSqYBkA5sjamHDDcFEtcE4uTvSqUBeYqhdwAGIQVBRVQwDifZAgVSYGAQbZiGBRZQAdQk8C4pzAcCOy0YHHkuIoELAXAmwwyXCUMHmIQuwOQYVUygpwwAVlx2gAhPaHGBHVRROBMKBwemM5kgNntI6XZRwACKmCqIqQDKZdxAp1QFNQEJaqieym2VFQGRgSM24mQAEYAAw24bGiAUpEhKgQ41wbWKbYAR0V8GpoxWkK4AFphc9ntt0H7GOhqT86SqxeqKVFGNdULdhlwZfL-cqbuqYPrzU5LUgAEzDbSqXKXDTRJOQ5SG4aYCkAFX1K1V4vktwAkpk7EcwCb2AFMkdKLLRWqeDwgA)

**Comment by tlouisse** [comment]
I think this commit made everything in sync again: https://github.com/ing-bank/lion/commit/72067c0d195d448afa2516c0a39ccbc0283e18cc

Maybe the difference was introduced by a newer version of Prettier somehow.
Do you think we can close this or do you see an action point here (like docs about how to configure vscode or smth else)?

**Comment by MatthieuLebigre** [comment]
> I think this commit made everything in sync again: [72067c0](https://github.com/ing-bank/lion/commit/72067c0d195d448afa2516c0a39ccbc0283e18cc)
> 
> Maybe the difference was introduced by a newer version of Prettier somehow.
> @MatthieuLebigre Do you think we can close this or do you see an action point here (like docs about how to configure vscode or smth else)?

All good now ! I just pulled master and don't have the issue anymore ! I don't think it requires any doc as it's working "out of the box" now :) The VS code plugin wasn't the cause of this issue.
I think we can close the issue

**Comment by tlouisse** [comment]
Awesome. Thanks for checking 👍
