### ISSUE TITLE
Device simulation not working

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#1394]
## Expected behavior

Device simulation working ;)

## Actual Behavior

![image](https://user-images.githubusercontent.com/9367152/119190282-23bf8680-ba4b-11eb-8f12-82d8e5084f22.png)

1. Go on https://lion-web.netlify.app/components/inputs/radio-group/overview/
2. Click on Enable device simulation (or open simulation in new window)

**Comment by tlouisse** [comment]
Hey, thanks for reporting. Should be fixed by https://github.com/ing-bank/lion/pull/1393 (we apply a patch until rocket is updated to lit 2)
