### ISSUE TITLE
[form-core] lion-validation-feedback isn't registered

### ISSUE THREAD

**Issue by alangdm** [ing-bank/lion#1408]
## Expected behavior

When using a form component with validation, the `lion-validation-feedback` component displays its content correctly.

## Actual Behavior

For some reason, the lion-validation-feedback component is never registered so even if the component status changes to `shows-feedback-for="error"` and the validation system assigns the properties corrected the validation feedback never displays

You can see this happening easily in the official docs validation demo (the checkbox one is the easiest to check)

https://lion-web.netlify.app/docs/systems/form/validate/#checkbox-validator

### Rendered Content

![Screen Shot 2021-06-02 at 15 20 18](https://user-images.githubusercontent.com/6799159/120433598-6459c100-c3b6-11eb-91db-782455e199bc.png)

### Chrome Inspector 

![Screen Shot 2021-06-02 at 15 20 50](https://user-images.githubusercontent.com/6799159/120433642-7471a080-c3b6-11eb-8298-e76d9292c86b.png)

(As you can see, the shadow root node doesn't appear in the inspector)

## Additional context

- This happened when updating from form-core v0.12 to v0.14
- Adding the following import to extending classes serves as a workaround

```js
import '@lion/form-core/define-validation-feedback';
```

**Comment by tlouisse** [comment]
Should be fixed by https://github.com/ing-bank/lion/pull/1412
