### ISSUE TITLE
[lion-input] disabled attribute does not work as expected

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#1409]
## Expected behavior

Use the disabled attribute to change the state of the input.

## Actual Behavior

When you use the attribute to disable a lion-input, the state of the input is not disabled.

In the example on codesandbox, click on toggle disabled attribute, then Shift+Tab, you will be focused in the input. With the toggle disabled property, it will work as expected

https://codesandbox.io/s/lion-input-disabled-88578?file=/index.html

## Additional context

It could to be related to the `requestUpdate` overriden in the `DisabledMixin`:
https://github.com/ing-bank/lion/blob/2b73c50f6e7ff9ef96122a74536e7c4df9b8553b/packages/core/src/DisabledMixin.js#L59

In `lit@2`, the function signature changed with a third parameter for options:
https://github.com/lit/lit/blob/20b4dd3fbfc3b8313be8fb98af61d222a82f96d1/packages/reactive-element/src/reactive-element.ts#L924

There is other places in the lion code where `requestUpdate` is overidden without this third parameter.

**Comment by DannyMoerkerke** [comment]
This was fixed in @lion/ui
