### ISSUE TITLE
[Safari] Tab key does not work to navigate between input fields

### ISSUE THREAD

**Issue by ovgu12** [ing-bank/lion#1429]
## Expected behavior

Use tab key to navigate between input fields works again

## Actual Behavior

When you change some input field for example  "First Name" under

https://lion-web.netlify.app/components/inputs/form/overview/

and then use tab key to move to "Last Name", it does not work. You need to press the tab key again.

**Comment by gerjanvangeest** [comment]
This is a duplicate of: https://github.com/ing-bank/lion/issues/1415
