### ISSUE TITLE
iOS 15 lion-dialogs: Hidden URL bar turns into a black bar 

### ISSUE THREAD

**Issue by Joel-Levi** [ing-bank/lion#1505]
The new iOS 15 update ships a version of safari that has the url bar at the bottom of the screen. When interacting with the page, that bar disappears. When opening a lion-dialog while that bar is hidden, a big black bar appears.

## Actual Behavior

In the following image you can see the black bar under the features heading
![black bar bug](https://user-images.githubusercontent.com/43135922/135644240-c5ec73f3-f750-4fbc-b515-714b8a28d57f.jpeg)

Before opening the dialog:
![WhatsApp Image 2021-10-01 at 17 08 25](https://user-images.githubusercontent.com/43135922/135644521-5309a008-4da8-43ce-92b9-85c49e568a27.jpeg)

## Reproduction

1. Go to the lion documentation page on a iOS 15 device
2. Hide the url bar by scrolling the page
3. Open the dialog

**Comment by Joel-Levi** [comment]
#1526

**Comment by tlouisse** [comment]
Solved by https://github.com/ing-bank/lion/pull/1526
