### ISSUE TITLE
[localize] As a developer I want to be able to provide preloaded translation data

### ISSUE THREAD

**Issue by askbeka** [ing-bank/lion#154]
In cases when translations are loaded from external api, applications already have some logic to handle other endpoint requests, 

ex: showing progress, error handling, error parsing, GraphQL, batch loading

**Comment by bashmish** [comment]
Looking at the title: we covered this use case [here](https://github.com/ing-bank/lion/blob/%40lion/localize%400.4.2/packages/localize/test/LocalizeManager.test.js#L87-L120).

Transforming the test into the real world code you'll need smth like:

```html
<!-- app-index.html generated on the server -->
<script type="module">
  import { localize } from '@lion/localize';
  localize.addData('%my-locale%', '%my-namespace%', '%my-preloaded-data%');
</script>
```

But looking at the description I'm not sure if you meant that. Does the provided example fit into your use-case?

**Comment by askbeka** [comment]
Cool. That's what I needed. Thanks
