### ISSUE TITLE
Please expose this function so users can test the isTriggeredByUser option

### ISSUE THREAD

**Issue by JitzePieter** [ing-bank/lion#1563]
https://github.com/ing-bank/lion/blob/d449515960bd8358d8a03893bc42b0f603147592/packages/form-core/test-suites/FormatMixin.suite.js#L42

Hi team, 
Can you please expose the function mimicUserInput so users can easily use this function to test code behind the isTriggeredByUser. 

if (ev.detail.isTriggeredByUser) {
// code to test
}

I tested this function for my code and saw that it does not format the modelValue if you have formatters on your input.
mimicUserInput(postalCode, '9051DE');
expect(postalCode.value).to.equal('9051 DE');
This expect fails because the modelValue is not updated yet.

**Comment by tlouisse** [comment]
Hey @JitzePieter , thanks for the report.

We will expose these as test-helpers in the near future.

Then you could do:

```js
mimicUserInput(postalCode, '9051DE');
// formattedValue stored, not synchronized with viewValue (.value)
expect(postalCode.formattedValue).to.equal('9051 DE');
postalCode.blur();
// formattedValue synchronized with viewValue (.value)
expect(postalCode.value).to.equal('9051 DE');
```

**Comment by daKmoR** [comment]
potentially even better would be to not simulate the input but to let the browser actually do the input... that was not possible in the past but with the sendKeys command in web test runner it's a viable option now

https://modern-web.dev/docs/test-runner/commands/#send-keys

**Comment by gerjanvangeest** [comment]
It's exporteed from `@lion/ui/form-core-test-helpers.js`
