### ISSUE TITLE
Improve accessibility Ordered List

### ISSUE THREAD

**Issue by Jirodica** [ing-bank/lion#1577]
## Actual Behavior

In Safari icm VoiceOver list numbers and list text are read out separately. for SR users it is more convenient to group list number and text.

See: https://www.w3.org/WAI/tutorials/page-structure/content/#ordered-list

## Additional context

Which component and version of it are you using > https://webdemos.feature-testing.ing.net/p00019-oj-sun-sun/components/content/list/overview/index.html

by the way: When dark-mode is turned on in web demos the text is hard to read when platform = web and size = inline

**Comment by tlouisse** [comment]
> ## Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ## Actual Behavior
> In Safari icm VoiceOver list numbers and list text are read out separately. for SR users it is more convenient to group list number and text.
> 
> See: https://www.w3.org/WAI/tutorials/page-structure/content/#ordered-list
> 
> ## Additional context
> Which component and version of it are you using > https://webdemos.feature-testing.ing.net/p00019-oj-sun-sun/components/content/list/overview/index.html
> 
> by the way: When dark-mode is turned on in web demos the text is hard to read when platform = web and size = inline

Hi Rob, thanks for the issue.

This one applies to  the docs of our internal extension of Lion, so could you please make an issue in our git repo? 
Then we can continue the conversation there :) 
For details about where to add the issue, feel free to contact me or @gerjanvangeest.
I will close this issue, as it does not apply to Lion...
