### ISSUE TITLE
[Feature Request] Event bubbling out of Overlays

### ISSUE THREAD

**Issue by DavidDuwaer** [ing-bank/lion#1599]
I'm running into the fact that events generated inside of a Dialog do not bubble up to the parent component (in my source HTML) of that Dialog. I guess this makes sense, since the contents of the `content` slot of Dialog are mounted elsewhere in the document DOM, inside the global-overlays div. Since in my source HTML the contents of the Dialog `content` slot appear as direct children however, it would be more natural to "me, the programmer" if the events would bubble directly Dialog and its parents.

I can bridge this gap myself by putting a listener for the event in the overlay's content (the child element of the `content` slot of Dialog in my case) and "re-emitting" a copy of that event on a lit-parent of the overlay component (`Dialog` in my case). I can even stop the event propagation along its originally intended route (from the global-overlays div upward) with e.stopPropagation.

Would it be nice/possible to build the re-routing of events generically into the popover/Dialog component? Perhaps with an option to opt out of it if needed?

**Comment by tlouisse** [comment]
Hey, we make use of the top layer functionality of a native `<dialog>` since recently (no need to move nodes to the body).
This should fix this event issue
