### ISSUE TITLE
[select-rich] modelValue is empty string

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#1601]
`choiceValue` works as expected, `modelValue` does not for select-rich component. 

This means that the model-value-changed event also never fires when changing selection, meaning syncing the selected option's HTML to the invoker also isn't happening. You can see this here https://lion-web.netlify.app/components/inputs/select-rich/features/ , try the first demo, change options, you will see the selectedIndex changes, the selection as well, but not the modelValue nor the invoker's `selectedElement`.

## Expected behavior

`.modelValue` of rich select to not be an empty string, but to be `{ value: 'red' | 'hotpink' | 'teal', checked: true | false }` in that demo.

## Actual Behavior

`.modelValue` is empty string.

https://lion-web.netlify.app/components/inputs/select-rich/features/

**Comment by jorenbroekema** [comment]
https://lion-web.netlify.app/docs/systems/form/features/ in this page something different is going wrong with the rich select in the umbrella form

**Comment by gerjanvangeest** [comment]
For quite some time the modelValue is always just a string `'red' | 'hotpink' | 'teal'`. This issue is not relevant anymore.
