### ISSUE TITLE
<ing-input-date>gives inconsistent result for IsDate validation

### ISSUE THREAD

**Issue by PawarSwati** [ing-bank/lion#1615]
## Expected behavior

for en-GB locale it should always allow dd/mm/yyyy format.

## Actual Behavior
![Capture](https://user-images.githubusercontent.com/100700797/156186915-fee618e9-06df-4b35-8abd-801b3e37467d.PNG)

for en-GB locale - it sometimes allows dd/mm/yyyy format while sometimes mm/dd/yyyy format.
validation is not consistent.

## Additional context

Ing web v2

**Comment by gerjanvangeest** [comment]
This bug occurs when the lang attribute is set to "en" and not "en-GB" as the picture suggests.

**Comment by PawarSwati** [comment]
Resetting of locale to en has been fixed now. its working as expected. thanks 

![image](https://user-images.githubusercontent.com/100700797/156342313-5435ff80-705a-4eee-a902-cae7ffdd8ffb.png)

**Comment by PawarSwati** [comment]
date format validation works as expected as per given locale.
