### ISSUE TITLE
[form-core] Using next version of ScopedElementsMixin error

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#1638]
Hi! 👋 
      
The next version of `ScopedElementsMixin` will not load the scoped registry polyfill by default which means `this.shadowRoot.createElement` will not be defined all the time

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@lion/form-core/src/validate/ValidateMixin.js b/node_modules/@lion/form-core/src/validate/ValidateMixin.js
index ea18839..c4bfde2 100644
--- a/node_modules/@lion/form-core/src/validate/ValidateMixin.js
+++ b/node_modules/@lion/form-core/src/validate/ValidateMixin.js
@@ -103,8 +103,8 @@ export const ValidateMixinImplementation = superclass =>
       return {
         ...super.slots,
         feedback: () => {
-          // @ts-ignore we load a polyfill to support createElement on shadowRoot
-          const feedbackEl = this.shadowRoot.createElement('lion-validation-feedback');
+          const root = this.shadowRoot.createElement ? this.shadowRoot : document;
+          const feedbackEl = root.createElement('lion-validation-feedback');
           feedbackEl.setAttribute('data-tag-name', 'lion-validation-feedback');
           return feedbackEl;
         },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by daKmoR** [comment]
same thing in `listbox`

**Comment by tlouisse** [comment]
Maybe the ScopedElementsMixin should provide this abstraction? (`createScopedElement(tagName:string)`)?

**Comment by daKmoR** [comment]
hmmm I'm not sure 🤔
abstracting those 2 lines of code may make it feel more complicated than it is...

**Comment by daKmoR** [comment]
actually, it's already there `this.defineScopedElement()` 🤣

**Comment by daKmoR** [comment]
will be solved via https://github.com/ing-bank/lion/pull/1647
