### ISSUE TITLE
[localize] add `currencyDisplay` to  FormatNumberOptions types

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#1651]
https://github.com/ing-bank/lion/blob/master/packages/localize/types/LocalizeMixinTypes.d.ts#L33

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

(apparently this info got lost in TS 4.5)

**Comment by tlouisse** [comment]
closing, error seems to be bound to specific TS version only

**Comment by gerjanvangeest** [comment]
`currencyDisplay` is part of `Intl.NumberFormatOptions` which `FormatNumberOptions` extends.
So no need to add it manually.
