### ISSUE TITLE
[Type] Wrong type when ScopedElementsMixin is used

### ISSUE THREAD

**Issue by MatthieuLebigre** [ing-bank/lion#1661]
## Expected behavior

Exported types for components using ScopedElementsMixin  are now wrong since https://github.com/ing-bank/lion/pull/1647/files has been merged.

Impacted components:

* LionSelectRich
* LionSwitch

If you inspect the published type for those component, we have this: `import("@open-wc/dedupe-mixin").Constructor<import("@lion/core/node_modules/@open-wc/scoped-elements/types/src/types").ScopedElementsHost>`

This leads to type error when you inherit from those components.

## Actual Behavior

The import `"@lion/core/node_modules/@open-wc/scoped-elements/types/src/types"` should be `"@open-wc/scoped-elements/types/src/types"`

## Additional context

I did a fresh install of Lion dependencies (after deleting yarn lock file), and the types generated are correct (`"@open-wc/scoped-elements/types/src/types"` instead of `"@lion/core/node_modules/@open-wc/scoped-elements/types/src/types"`).

So it's probably an inconsistency in yarn.lock file

**Comment by tlouisse** [comment]
Hey, thanks for reporting this. Any idea which packages are responsible? (you would expect @open-wc/scoped-elements, but that is already on latest).
When you run `node  ./scripts/yarn-lock-diff.mjs --versions-back 1 ` it should compare your lock yarn.lock against the last committed in git...

**Comment by MatthieuLebigre** [comment]
I've opened a MR with the yarn lock file freshly generated (https://github.com/ing-bank/lion/pull/1663).
When I run the command against my branch, this is the result:

```
{
  "removed": [],
  "changed": [] 
}
```

**Comment by MatthieuLebigre** [comment]
I have no idea what package causes this issue :( I noticed with the current state of yarn lock, you have a sub folder node_modules inside packages/core/

**Comment by MatthieuLebigre** [comment]
You can close the issue, I confirm it doesn't appear anymore with all recent changes

**Comment by gerjanvangeest** [comment]
Thanks for checking
