### ISSUE TITLE
[input-date] IE11 incorrectly reformats dates

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#168]
Use IE11 and enter a date like 15/06/17, with the year consisting of 2 digits. Tab out of the field. The information in the field becomes 06/05/1916, instead of the expected 15/06/2017.

- 12/12/01 becomes 12/01/1912. 
- 12/01/12 becomes 01/12/1912. 
- 01/12/12 becomes 12/12/1901.

**Comment by bashmish** [comment]
We expect a full date. I don't think we ever supported or wanted to support such a shortcut, did we? cc @tlouisse 

The other thing is that it does not mark it as invalid, but tries to reformat and present some wrong date. Probably we should think about fixing that.

**Comment by gerjanvangeest** [comment]
Input-date says dates with a year of 2 digits, are already not valid. So closing this issue.
