### ISSUE TITLE
Accordion incorrect focus handling

### ISSUE THREAD

**Issue by gerjanvangeest** [ing-bank/lion#1697]
## Expected behavior

Accordion incorrect focus handling. The focus should jump from header to panel content, before going to the next header.
example: https://www.w3.org/WAI/teach-advocate/accessible-presentations/

## Actual Behavior

The focus order first goes to all accordion headers, before going into the panels.

[example](https://studio.webcomponents.dev/edit/2CnalpcSc7LxxfzGjFkI/README.md?p=README.md)

**Comment by ffoodd** [comment]
Is there any way to make invokers & contents keep their respective DOM order, instead of melting all of them in `invoker` and `content` single slots and using CSS `order`?

That's the root cause of this issue, and it affects focus but also content navigation.

**Comment by ffoodd** [comment]
Might relate to #1724 at some point, I guess.

**Comment by gerjanvangeest** [comment]
fixed in: https://github.com/ing-bank/lion/pull/1883
