### ISSUE TITLE
Support for native focus method in lion field

### ISSUE THREAD

**Issue by palash2601** [ing-bank/lion#1701]
lion field components should support native `focus()` method

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

**Comment by tlouisse** [comment]
Should be covered by this? 
https://github.com/ing-bank/lion/blob/master/packages/form-core/test/FocusMixin.test.js#L77

**Comment by daKmoR** [comment]
you are right it seems to work fine

https://user-images.githubusercontent.com/24378/169268974-d32a30fb-7122-42d1-9047-4b2580a1d7ac.mp4

@palash2601 I'm closing this if you have a way to reproduce the issue feel free to reopen or creating a new issue 🤗
