### ISSUE TITLE
Cannot type anymore on @lion/combobox input

### ISSUE THREAD

**Issue by riccardoperra** [ing-bank/lion#1704]
## Expected behavior

The input text doesn't change on key down event. Only special characters like - / $ are allowed on typing. Is something changed with the updates?  

## Actual Behavior

Input text doesn't change on key down event.

With Solid
https://codesandbox.io/s/solid-1-4-1-web-components-dom-events-issue-uwbsyq

With your playground
https://studio.webcomponents.dev/edit/ClPWao26DBBMJWy5rYnb/

## Additional context

Using latest versions

It seems that removing the dom events that attach _listboxOnKeyDown it works, but I'll lose all listbox feature

**Comment by gerjanvangeest** [comment]
I believe [this PR](https://github.com/ing-bank/lion/pull/1674) is the cause of the bug. Probably didn't battle test it enough, sorry!

Will work on a fix today.
