### ISSUE TITLE
[switch][switch-button] setting the "role" attribute inside the constructor produces an Uncaught DOMException

### ISSUE THREAD

**Issue by JackWithOneEye** [ing-bank/lion#1740]
## Expected behavior

LionSwitch and LionSwitchButton should be able to initialise without throwing errors.

## Actual Behavior

LionSwitch and LionSwitchButton  both cannot initialise and render as an `Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes"` is thrown.

This is because the `role` attribute is assigned inside the constructor of both components. Attributes should instead be set in `connectedCallback` at the earliest ([see HTML standard](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance)).

```
constructor() {
    super();
    this.role = 'switch';
    this.checked = false;
    /** @private */
    this.__handleButtonSwitchCheckedChanged = this.__handleButtonSwitchCheckedChanged.bind(this);
  }
```

## Additional context

I should add that this has not been an Issue in my project until about a week ago although my dependencies not changed for the last two months. I have not been able to figure out why all of a sudden this has become a problem.

**Comment by riovir** [comment]
Until resolved, here is a workaround and minimal reproduction:
```js
class TheProblem extends HTMLElement {
	constructor() {
		super();
		this.role = 'switch';
	}
}

class AWorkaround extends TheProblem {
	constructor() {
		super();
	}

	connectedCallback() {
		super.connectedCallback();
		this.setAttribute('role', 'switch');
	}
	set role(_) { /* XXX: Ignore as a workaround to prevent the Lion's constructor from blowing up. */ }
	get role() { return this.getAttribute('role') || undefined; }
}

customElements.define('my-component', AWorkaround);

const el = document.createElement('my-component');
document.body.appendChild(el);

```

**Comment by tlouisse** [comment]
@JackWithOneEye the proposal from @riovir sounds good. Mind to do this as a pr?

**Comment by Theo-Steiner** [comment]
@tlouisse would it be alright if I took a stab at making a PR for this one?
