### ISSUE TITLE
[form][validation] getMessage() returns only a Promise

### ISSUE THREAD

**Issue by AndreeaMoise** [ing-bank/lion#1753]
### Expected behaviour

I can use the Validator getMessage as exemplified in the lion docs to return a string: `Required.getMessage = () => 'Please enter a value';`

### Actual behaviour
Because of the function's signature `static getMessage(data?: Partial<import("../../types/validate").FeedbackMessageData> | undefined): Promise<string | Element>;`, I can only return a promise.

**Comment by tlouisse** [comment]
Hey @AndreeaMoise.

So your goal is to change the type to `Partial<import("../../types/validate").FeedbackMessageData> | undefined): Promise<string | Element> string | Element;`

Makes sense to support this api. Do you want to do a pull request for this?

**Comment by tlouisse** [comment]
closed by https://github.com/ing-bank/lion/pull/1756
