### ISSUE TITLE
Switch: A11y issue on Safari with Voiceover

### ISSUE THREAD

**Issue by steffchep** [ing-bank/lion#1772]
### Reproduction:

visit https://lion-web.netlify.app/components/switch/overview/

Enable Voiceover on Macintosh Safari 15.6

Navigate to the switch with the keyboard

 

### Expected:
 * state is read correctly (activated/deactivated, or checked/unchecked or any variation thereof)
 * state change is communicated by reading out the new state

### Observed
 * no matter what, the state is always read as "deactivated" - state change is not evident in the voice (the switch does visibly change state)
 * When changing the state, voiceover does not re-read the text and state (and tabbing away from it and back still reads "deactivated"

## On iPad
When using an iPad (also 15.6) I get the same behaviour where the Switch always reads "deactivated" or "unchecked" regardless of state. 
Furthermore, double-tapping it to change state does nothing

**Comment by Sciurus7** [comment]
I have also observed the double-tap issue on android when using TalkBack. TalkBack will intially focus the switch-button and the label. Contrary to ios it will read the state correctly, but it will state that double-tapping will activate the switch which it does not. Swiping one element further will focus the switch button at which point double tapping will switch the state. So it is still operable, again, contrary to ios.
