### ISSUE TITLE
[helpers] Invalid customElements field in package.json

### ISSUE THREAD

**Issue by justinfagnani** [ing-bank/lion#1789]
## Expected behavior

`"customElements"` points to a file in the package.

## Actual Behavior

No such file. See https://unpkg.com/browse/@lion/helpers@0.12.1/

**Comment by gerjanvangeest** [comment]
We moved to a single package `@lion/ui` which has the `customElements` file including helpers.
https://unpkg.com/browse/@lion/ui@0.2.0/
