### ISSUE TITLE
[providence-analytics] Absent configuration file leads to a NodeJS exception

### ISSUE THREAD

**Issue by THETCR** [ing-bank/lion#1805]
`npx providence --help`  cannot be run without a config being present in the current working directory.

`get-providence-conf.mjs` states:

> let confPathFound;
  try {
    if (fs.existsSync(`${confPathWithoutExtension}.js`)) {
      confPathFound = `${confPathWithoutExtension}.js`;
    } else if (fs.existsSync(`${confPathWithoutExtension}.mjs`)) {
      confPathFound = `${confPathWithoutExtension}.mjs`;
    }
  } catch (_) {
    throw new Error(
      `Please provide ${confPathWithoutExtension}.js or ${confPathWithoutExtension}.mjs`,
    );
  }
  if (!confPathFound) {
    return null;
  }
  
 That statement will never result in an error being thrown when the configuration is absent.
 Which subsequently leads to `const { providenceConf } = await getProvidenceConf();` throwing a TypeError because you can't destructure a property from null.

**Comment by tlouisse** [comment]
Thanks for the bug report: will be solved by https://github.com/ing-bank/lion/pull/1920
