### ISSUE TITLE
LionInputDatePicker enters an endless loop on InvalidDate modelValue

### ISSUE THREAD

**Issue by thematho** [ing-bank/lion#1812]
## Expected behaviour

When an InvalidDate value is passed to the `modelValue` property, the `lion-validation-feedback` error message should appear
```javascript
      <lion-input-datepicker 
          label="Date" name="date"  
          .modelValue=${ new Date('30/01/2022')}> // Invalid Date or new Date('wrong format')
      </lion-input-datepicker> 
```
## Actual Behaviour

The component enters an infinite loop and freezes the window.

To reproduce, uncomment the commented code in the following example:
https://studio.webcomponents.dev/edit/wjSZwkmBdLlH9qEdBIbu/src/index.js

## Additional context

_If the date value obtain from an API or formatter or date library is incorrectly configured, the datepicker could show the validation feedback as error._

**Comment by gerjanvangeest** [comment]
Issue was solved in: https://github.com/ing-bank/lion/pull/1984
