### ISSUE TITLE
LionInputDatePicker error from OverlayContorller when unit tests are executed

### ISSUE THREAD

**Issue by dancarlocanlas** [ing-bank/lion#1828]
## Expected behavior
The unit tests for a component that utilizes the datepicker should not expect any errors

## Actual Behavior
An error is thrown when unit tests are executed, coming from the `OverlayController`:
`Error: [OverlayController] Could not find a render target, since the provided contentNode is not connected to the DOM. Make sure that it is connected, e.g. by doing "document.body.appendChild(contentNode)", before passing it on.`

## Additional context

@lion/input-datepicker v0.26.1

**Comment by tlouisse** [comment]
Hi, thanks for the report. This will most likely be fixed by https://github.com/ing-bank/lion/pull/1712

**Comment by tlouisse** [comment]
Closing, since indeed fixed by https://github.com/ing-bank/lion/pull/1712
