### ISSUE TITLE
[Overlays] adopted stylesheets are attached to body instead of document

### ISSUE THREAD

**Issue by MatthieuLebigre** [ing-bank/lion#1880]
## Expected behavior

Since this PR **https://github.com/ing-bank/lion/pull/1854**, adopted stylesheets are now attached to the body instead of document.
But correct me if I'm wrong but adopted stylesheets is only supported on document (and shadow roots).

I'm experiencing this issue with @lion/ui v0.0.12

## Actual Behavior

Adopted stylesheets are attached to the body and not actually applied

## Additional context

@lion/ui v0.0.12

**Comment by tlouisse** [comment]
You're completely right, now that I look deeper into it...

This was tested in a context where adoptedStylesheets were not working/disabled.
In that case, this line would break if you attach styles to the document via `adoptStyles` from lit:
https://github.com/lit/lit/blob/main/packages/reactive-element/src/css-tag.ts#L185

So, the actual fix would be in lit:
```ts
export const adoptStyles = (
  renderRoot: ShadowRoot,
  styles: Array<CSSResultOrNative>
) => {
  if (supportsAdoptingStyleSheets) {
    (renderRoot as ShadowRoot).adoptedStyleSheets = styles.map((s) =>
      s instanceof CSSStyleSheet ? s : s.styleSheet!
    );
  } else {
    const adoptRoot = renderRoot === document ? document.body : renderRoot;
    styles.forEach((s) => {
      const style = document.createElement('style');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const nonce = (global as any)['litNonce'];
      if (nonce !== undefined) {
        style.setAttribute('nonce', nonce);
      }
      style.textContent = (s as CSSResult).cssText;
      adoptRoot.appendChild(style);
    });
  }
};
```
