### ISSUE TITLE
[lion-input-amount] Turns edited negative numbers to positive

### ISSUE THREAD

**Issue by riovir** [ing-bank/lion#1890]
Using the latest (@lion/ui v0.1.0) LionInputAmount enter "-42" then press enter. This will turn it into "−42.00". Pay close attention to the '-' character becoming a '−', which looks more "minusey" I guess. Then edit the number, eg. remove 2 and press enter again.

## Expected behavior

The number becomes "−4.00".

## Actual Behavior

The number turns into a positive one: "4.00".

## Additional context

The fancy '−' character seemingly gets ignored during parsing a number.

**Comment by riovir** [comment]
The most primitive workarounds we are:
a) using a preprocessor of `value => value.replaceAll('−', '-')`
b) replacing the parser with a custom `(value, options) => parseAmount(value.replaceAll('−', '-'), options)`

**Comment by tlouisse** [comment]
Thanks for the report! For the preprocessor, you can also return the correct caretIndex like here:
https://github.com/ing-bank/lion/blob/e08b6bec580bdd65468cb9f4cf802f4d73e6ade0/packages/ui/components/form-core/test-suites/FormatMixin.suite.js#L646

**Comment by riovir** [comment]
Sure thing! Some additional context. The use of the fancy '−' may be questionable. I grabbed a "−42" and pasted it into Google Sheets (a colleague did so with Excel as well). We each applied a simple numeric formula on the cell and ended up with an error. The cell was not recognized as a number. Then proceeded to swap out the formatter to coerce the '−' back to a regular '-' sign. 

Repeated the experiment and both apps correctly recognized the cells as numbers. Am I missing a case why the '−' was introduced in the first place?

**Comment by gerjanvangeest** [comment]
The change to Minus-Sign was 3 years ago for a better Screen reader experience. See: https://github.com/ing-bank/lion/pull/279

I created a fix, see PR: https://github.com/ing-bank/lion/pull/1891

**Comment by riovir** [comment]
_Sorry for the off-topic._ I saw that `@lion/ui` has entered beta a few hours ago with the `0.1.x` version range. Is the legacy structure also in beta? In other words, is this a good time to start migrating our design system, that's in production or there are plans for a more stable version soon?
