### ISSUE TITLE
[FormControlMixin] custom label is overwritten by changedPropertiesCall

### ISSUE THREAD

**Issue by nbamfordcirium** [ing-bank/lion#1892]
## Expected behavior

I attempted to create a custom label in a Custom Field which inherited from LionRadioGroup by overriding the `get slots()` call like so:

```javascript
override get slots() {
    return {
      ...super.slots,
      label: () => {
        const div = document.createElement('div');
        const label = document.createElement('label');
        const span = document.createElement('span');
        span.textContent = this.label;
        span.appendChild(label);
        div.appendChild(span);
        return div;
      },
    };
  }
```

When the component rendered, I expected to inspect the label slot and find `<div><span><label>*labeltext*</label></span></div>`

## Actual Behavior
Inspecting the label slot, I find only `<div>*labeltext*</div>`.

 I notice in `FormControlMixin.js` in the `updated()` method, the following lines:

```javascript
 if (changedProperties.has('label') && this._labelNode) {
        this._labelNode.textContent = this.label;
      }
```

This call replaces the inner nodes of my custom label with the text content of the class label member.

https://studio.webcomponents.dev/edit/84yxydo9qcCn2wqkMI0E

## Additional context

Using LionRadioGroup, though I've verified this happens with other controls using `FormControlMixin` 

`@lion/form-core` is 0.18.3
`@lion/radio-group` is 0.21.1

**Comment by tlouisse** [comment]
Hey @nbamfordcirium , thanks for the issue. We actually require the `_labelNode` to be a `<label>` with no children indeed.

Would this work for you?

```
class MyInput extends LionInput {
    /**
     * @return {TemplateResult}
     * @protected
     */
    _labelTemplate() {
      // you can place any html you want here, as long as it contains `<slot name="label"></slot>`
      return html`
        <div>
          <span>
            <slot name="label"></slot>
          </span>
        </div>
      `;
    }
}

```
