### ISSUE TITLE
[button] programmatic clicks don't work on mobile browsers when combined with polymer

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#19]
The polymer gestures modules prevents programmatic clicks on mobile browsers. This is due to the fact that their event detection mechanism doesn't correctly detect the click events.

There is an open issue https://github.com/Polymer/polymer/issues/5289 but I don't know if it will be solved anytime soon.

The lion project doesn't officially have anything to do with polymer, but we use lion-web and polymer in hybrid applications.

Possible solutions I can think of:

- Call `window.Polymer.Gestures.resetMouseCanceller();` before calling `.click()`;
- Ensure that the button we call `.click()` on is a child of `ing-button`, so that the detection works properly
- Fire `input.dispatchEvent(new MouseEvent('click', { bubbles: false }))` instead of a click

Any other ideas?

**Comment by LarsDenBakker** [comment]
Fixing this in Polymer would be the proper fix. Let's see if this gets accepted: https://github.com/Polymer/polymer/pull/5533

**Comment by bashmish** [comment]
Since the fix [has been merged](https://github.com/Polymer/polymer/pull/5533#event-2334414965) in Polymer, I'm closing this. Thanks for fixing this for everyone 🌞

**Comment by bashmish** [comment]
Small update: the fix for 2.x [was merged on 13 May](https://github.com/Polymer/polymer/pull/5536#pullrequestreview-236774802) and [was released in Polymer 2.8.0 on 24 June](https://github.com/Polymer/polymer/blob/2.x/CHANGELOG.md#v280-2019-06-24).
