### ISSUE TITLE
[Overlays]  Scroll to the top when the Overlay is closed on iOS

### ISSUE THREAD

**Issue by hyakt** [ing-bank/lion#1905]
## Expected behavior

The scroll position should keep when the Overlay is closed even if use iOS.

## Actual Behavior

The scroll position move to top when Overlay is closed on iOS

**Comment by tlouisse** [comment]
Hi. This is actually a tradeof. IOS requires position:fixed to avoid issues with inputs.

```js
// iOS and safari for mac have issues with overlays with input fields. This is fixed by applying
// position: fixed to the body. As a side effect, this will scroll the body to the top.
```

See: https://github.com/ing-bank/lion/blob/master/packages/ui/components/overlays/src/OverlaysManager.js#L189

It would be welcome to have a PR that fixes this:
- on`@before-open` of overlayCtrl:
  - store variable `activeElBeforeOpen` via `document.activeElement` (preferably also search recursively in shadow roots)
  - store variable `yOffsetViewportOfActiveElBeforeOpen` via `getBoundingClientRect()`
- on`@hide` of overlayCtrl:
  - find the y offset from **document** of the stored activeElement 
  - subtract `yOffsetViewportOfActiveElBeforeOpen` from the last value and store in variable `restoredWindowY`
  - set `window.scroll(0, restoredWindowY)`

**Comment by hyakt** [comment]
Thank you for checking.

I tried it in a clean environment and you are right, the scroll position is back when the overlay is closed 🙇‍♂️

https://studio.webcomponents.dev/preview/oKnhaNEsxIP8zmwxqWPM

Perhaps there is a problem with my application.
