### ISSUE TITLE
[calendar] Remove aria-live from heading

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#191]
Currently, the `<h2>` has `aria-live="polite"` set to it. This makes sure that when people using assistive technology navigate with the next and previous button, they know which month they navigated to. When these people navigate in the calendar area, they get this same update. But this time, it is duplicate information as the month is also included in the date they navigate to.
My suggestion is to remove `aria-live` and to add information to the button labels. If the currently visible month is July 2019. The buttons could be labeled "Previous month, June 2019" and "Next month, August 2019".

**Comment by bashmish** [comment]
I like the suggested fix! 👍
