### ISSUE TITLE
[@lion/ui]: Missing sideEffects declaration causes bloated bundles

### ISSUE THREAD

**Issue by riovir** [ing-bank/lion#1915]
## Expected behavior

```
import @lion/core; // Tree-shaken to blank bundle
import @lion/[other-exports]; // Tree-shaken to blank bundle
````
The `sideEffects` declaration is filled out in the `package.json`.

## Actual Behavior

```
import @lion/ui/core.js; // Includes about 20KB 
import @lion/ui/[other-exports].js; // Includes varying sizes of imports
````

The `sideEffects` declaration is missing from the `package.json`.

## Additional context

In our case after migrating our design system to the `@lion/ui` package we observed all the bundle size tests failing. Zero-import cases were resulting builds around 190KB, while importing just one component was somewhere around 220-260KB.

**Comment by riovir** [comment]
I'd be happy to send a PR to address this in principle, but I'm somewhat concerned that I could miss something and cause some nasty bugs that only appear when the tree-shaking goes overboard.

**Comment by tlouisse** [comment]
Hey, good that you point these out.

We should definitely bring back the sideEffects in package.json of @lion/ui.

From the top of my head, we have:
- exports/localize.js
- exports/overlays.js
- exports/icons.js 

The rest should not be side-effectful, I think.

No clue what could cause this 20kb for `@lion/ui/core.js` for instance: https://github.com/ing-bank/lion/blob/master/packages/ui/exports/core.js

A PR would be highly appreciated!

**Comment by tlouisse** [comment]
fixed: https://github.com/ing-bank/lion/pull/1917#issuecomment-1436625221
