### ISSUE TITLE
Typescript can't find the types 

### ISSUE THREAD

**Issue by laczor** [ing-bank/lion#1921]
## Expected behavior

When importing a component it should find it's types

## Actual Behavior
When a component is imported, nor the compiler or the local typescript server can find the types for the component.
![image](https://user-images.githubusercontent.com/27684062/219320180-4bfe5236-84ee-4ac7-a8ad-8a9afe8111c6.png)

## Additional context

There is a sample repo, with reproduction recipe.
https://github.com/laczor/lion-ui-ts-error

Can i ask what was the reason to move the types to **dist-types folder**, without a main bundle for declaration?
Since in the package.json, on a single bundle of types can be referenced via **types** or **typings**, there is no other way to tell typescript where the types are living.

```json 
{
  "types": "./dist-types/index.d.ts",
  //or
  "typings": "./dist-types/index.d.ts",
}
```
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

or what is the reason for not putting the declaration files next to the js files in the exports folder?
![image](https://user-images.githubusercontent.com/27684062/219322802-763f4ac8-6a35-49c3-8ff2-482fe2587270.png)

Thank you for your response

**Comment by tlouisse** [comment]
Maybe @daKmoR can jump in here?

In our own extension layer, this config works for us:

```js
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "lib": ["es2017", "dom"],
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "noImplicitThis": true,
    "composite": true,
    "emitDeclarationOnly": true,
    "alwaysStrict": true,
    "types": ["node", "mocha", "chai", "sinon"],
    "esModuleInterop": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "incremental": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  }
}
```

**Comment by laczor** [comment]
Hello,
Thank you for your quick response and for the ts config!

So the sollution is to set  in **package.json** to **type:module**.
However there is a problem with this.
I am able to tell rollup to work with es6 modules, while working in a commonjs enviroment,  however since @lion/ui started to use ****exports** in package.json**, **it can only work in type:module** and even if i can tell rollup how to treat es6 modules, i can't configure typescript to use the commonjs resolution strategy.
https://www.typescriptlang.org/docs/handbook/module-resolution.html

Thus the whole project has to be converted to es6 modules.

I have one question, can you please tell me, why the declaration files have been moved to a separate dist-types instead of having them next the the original js files?

Thank you for your work!
