### ISSUE TITLE
[calendar] Date pronounced twice in NVDA

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#193]
Using NVDA and Firefox, when you navigate the calendar grid, dates get pronounced twice. For example:
> 13 July 2019 Saturday  not selected  row 3  Saturday  column 7
> 13 July 2019 Saturday  button

This is rather verbose and not preferred. 

The first part seems to be the accessible name of the cell, even though the "not selected" comes from an aria attribute on the button.

It gets less verbose when `role="gridcell"` is applied but it's not a solution. Also because the role is there for a reason. Removing `role="application"` might also help, but removal would creates issues with keyboard navigation. Further investigation is needed.

This pronounciation might be a bug or design choice from NVDA. I think it would be an improvement for the component if it would be able to circumvent this and be less verbose.

**Comment by tlouisse** [comment]
Did quite some testing here (also tried to render everything to light dom, like in the [w3c grid example](https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html)) and had same foundings as @erikkroes 

Maybe we can get rid of the button and apply tabindex="0" and all aria attributes on the element with [role=gridcell]?
It supports `aria-pressed` and `aria-current`:
https://www.w3.org/TR/wai-aria-1.1/#gridcell

**Comment by daKmoR** [comment]
after many more tests I'm pretty confident that it's actually a bug in NVDA 🙈

Raise an issue there
https://github.com/nvaccess/nvda/issues/12392
