### ISSUE TITLE
WebKit's test failed because of formatNumber

### ISSUE THREAD

**Issue by Farzannajipour** [ing-bank/lion#2004]
`AssertionError:` expected 'US$123,456.79' to equal '$123,456.79' only for Webkit. It works for Firefox and Chromium.

## Expected behavior

US$123,456.79

## Actual Behavior

+$123,456.79

## Actual Behavior

To reproduce this error, use the following step:
 `npm run test`

## Additional context

The error was observed in the "formatNumber" test under the "localize" component. The issue appears to be related to a mismatch between the expected value and the actual value. The test code and implementation should be reviewed to find the root cause of the issue.

**Comment by gerjanvangeest** [comment]
We have the same code to correct this for Australia: https://github.com/ing-bank/lion/blob/master/packages/ui/components/localize/src/number/utils/normalize-format-number-to-parts/forceENAUSymbols.js

Let me check this with our colleagues in the Philippines, which one is the correct way of writing.

**Comment by gerjanvangeest** [comment]
fixed with: https://github.com/ing-bank/lion/pull/2011
