### ISSUE TITLE
lion switch missing super call in disconnectedcallback

### ISSUE THREAD

**Issue by iceicerickert** [ing-bank/lion#2045]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@lion/switch@0.16.5` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@lion/switch/src/LionSwitch.js b/node_modules/@lion/switch/src/LionSwitch.js
index b5b755e..e197147 100644
--- a/node_modules/@lion/switch/src/LionSwitch.js
+++ b/node_modules/@lion/switch/src/LionSwitch.js
@@ -94,6 +94,7 @@ export class LionSwitch extends ScopedElementsMixin(ChoiceInputMixin(LionField))
   }
 
   disconnectedCallback() {
+    super.disconnectedCallback();
     if (this._inputNode) {
       this._inputNode.removeEventListener(
         'checked-changed',
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by gerjanvangeest** [comment]
Sorry for the slow reaction :(

This has been fixed in `@lion/ui` some time ago.
