### ISSUE TITLE
[LionCalendar]: Disabled dates can be selected with keyboard navigation

### ISSUE THREAD

**Issue by gyulus3** [ing-bank/lion#2057]
## Expected behavior

Disabled dates cannot be selected by navigating with the arrow keys to them and hitting enter or space.

## Actual Behavior

Disabled dates can be selected only with keyboard navigation.

**Comment by gerjanvangeest** [comment]
Hi @gyulus3, sorry for the slow response due to holiday period.

I agree the dates should not be selectable, only focusable. We'll have to look into how we can create this behaviour.
If you have time, feel free to try it out as well 💪!

**Comment by gyulus3** [comment]
Hey @gerjanvangeest! Well, I've already created a pull request linked to this issue. Take a look at that solution, I believe that's the expected behavior.

**Comment by gyulus3** [comment]
I will take a look at that. That looks interesting indeed.
