### ISSUE TITLE
Listbox multiple choice: screen reader reading out 'selected' after every option

### ISSUE THREAD

**Issue by michielpauw** [ing-bank/lion#2069]
## Expected behavior

When using Screen Reader with Listbox, it should read out options, and add 'Selected' when an option is selected, and nothing when not selected.

## Actual Behavior

Biggest issue occurs in Listbox with multi-select (https://lion-web.netlify.app/components/listbox/use-cases/). When Screen Reader is activated here, and we navigate through the options of the listbox, we see the following behaviour:

- When an option is not selected it will read out 'Asparagus not selected, selected, (3 of 10)', should be 'Asparagus, (3 of 10)'
- When an option is selected, it will read out 'Asparagus selected, selected, (3 of 10)', should be 'Asparagus selected, (3 of 10)'

## Additional context

See netlify app to reproduce behaviour.

**Comment by bagherani** [comment]
@michielpauw I believe reading out `Asparagus selected, selected, (3 of 10)` & `Asparagus not selected, selected, (3 of 10)` is normal behavior by the Reader, As a matter of fact, if you try it by a simple `<select multiple><option>Asparagus</option></select>` you would see that it acts the same.

**Comment by tlouisse** [comment]
As it is the same behavior as the native select, we're closing this issue.
@michielpauw feel free to let us know if you think it should be re-opened.
