### ISSUE TITLE
[field] form registry system breaks when element never connects and creates a memory leak

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#215]
The `FormRegistrarMixin` registers itself in the constructor. This creates two issues:

If the element never connects to the page, all forms on the page break because `all-forms-open-for-registration` is never fired. This can be observed simply by creating a lion form without connecting it: https://stackblitz.com/edit/lit-html-btb2i8

If you uncomment `document.createElement('lion-form');` the form will work.

The other problem is that the manager is creating a memory leak by holding forms (and their subtrees) on the page in memory. A WeakMap would be best to use here.

This is breaking all our tests because for some reason it's creating forms without connecting them. It works fine in the demo, so it seems to be something in the tests. Looking into why that's happening.

**Comment by LarsDenBakker** [comment]
Turns out this is also affecting non-test code. We have a component with multiple steps, if you switch steps very quickly elements are created before they reach `firstUpdated`. This will break all forms on the page, as they're all waiting for that one element to reach `firstUpdated`.

**Comment by daKmoR** [comment]
makes sense - we originally put it on constructor to minimize the delay... but yeah for these cases that's a no go 🙈 
Weakmap also sounds like a good idea 👍 

do you already have a fix?

**Comment by tomherni** [comment]
Submitted a PR, hope it helps https://github.com/ing-bank/lion/pull/223
