### ISSUE TITLE
renderLitAsNode breaks when using @webcomponents/scoped-custom-element-registry

### ISSUE THREAD

**Issue by NingenJanai** [ing-bank/lion#2192]
## Expected behavior

renderLitAsNode renders the components correctly when using scoped custom element registry.

## Actual Behavior

When using the scoped custom element registry renderListAsNode rendering is broken.

https://studio.webcomponents.dev/edit/ONdXLvnhfIY59QPAqqwb/src/index.js?p=README.md

## Additional context

Which component and version of it are you using.

**Comment by wessamzaghloul** [comment]
`renderLitAsNode` is expecting a single node, by wrapping the content of your HTML in a div this is working as expected
https://studio.webcomponents.dev/edit/z4tcbD6IH0OKjRYwBfz4/src/index.js?p=README.md

**Comment by NingenJanai** [comment]
thanks a lot 👍
