### ISSUE TITLE
Migrating to @lion/ui 0.52 from @lion/core 

### ISSUE THREAD

**Issue by niallriddell** [ing-bank/lion#2197]
Hi - wondering if there was any best practice advice on how to migrate from older version of @lion that is not part of the @lion/ui package.

I don't see anything obvious in the docs - so I'm thinking it's a full refactor.

**Comment by gerjanvangeest** [comment]
All breaking changes concerning the switch from `@lion` UI components to `@lion/ui` can be found in the `[changelog](https://github.com/ing-bank/lion/blob/master/packages/ui/CHANGELOG.md#010)`.

All other packages stayed the same as far as i can remember.
