### ISSUE TITLE
[field] values switching from invalid to valid are not formatted (and vice versa)

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#22]
## Problem
Fields containing valid modelValues should be run through a formatter, whereas invalid modelValues should not. 
Values switching from invalid to valid are not formatted (after [this pull request](https://github.com/ing-bank/lion/pull/15/files#diff-8a0f76e26a132ed6bb832fc7ff0518c8R273
) is merged they are) and values switching from valid to invalid will be formatted (but should not).

The pr mentioned provides a temporary workaround, but a proper solution is needed.

### Current flow
Setting of modelValue triggers observers for:
 - computation of 'formattedValue'
 - validation (and thus computation of 'errorState')

Observers will be handled in above order. Since computation of formattedValue depends on 'errorState' (erroneous inputs should not be formatted), the formatter is handled with a not yet updated errorState.
 
### Solution
Rewrite to a flow handling observers in this order: `modelValue -> errorState(validation) -> formattedValue`.
Important: in the referenced pr, a situation where a value changes from valid to invalid will still lead to formatting when not required.
Since the flow above involves two mixins (FormatMixin and ValidateMixin) and ValidateMixin should have no knowledge about FormatMixin, think of a proper way to do this.

It might be as easy as changing the order of mixins applied within LionField: if the ValidateMixin runs before the FormatMixin, the errorState should be computed by the time the formatter runs.

**Comment by bashmish** [comment]
Can we close this now after [this fix](https://github.com/ing-bank/lion/pull/84)? @tlouisse @gerjanvangeest

**Comment by tlouisse** [comment]
If you're 100% sure that the issue is gone (or more importantly doesn't have side effects.) Maybe add the tests as Joren suggested, merge everything to master and then close?

**Comment by bashmish** [comment]
@tlouisse it's been merged by @jorenbroekema already and I assumed that [this is the test](https://github.com/ing-bank/lion/pull/84/files#diff-8589890f1ad950710df0434b24582b97R331) Joren was talking about

**Comment by tlouisse** [comment]
Ah, missed that. The test 'title' has a small 'typo', but test looks good, so this issue can be closed
