### ISSUE TITLE
select-rich when [read-only] it still works with keyboard interaction

### ISSUE THREAD

**Issue by gerjanvangeest** [ing-bank/lion#2208]
## Expected behavior

- Keyboard interaction to be blocked
- also the active state button is still there

## Actual Behavior

Via the arrow keys another option can still be selected.
https://lion-web.netlify.app/components/select-rich/use-cases/#read-only-prefilled

**Comment by wessamzaghloul** [comment]
active state behaves the same as in the 'Single Option', would this be then working as expected?
