### ISSUE TITLE
[@lion/ui/localize.js] parseNumber('--42') is parsed as NaN

### ISSUE THREAD

**Issue by riovir** [ing-bank/lion#2227]
## Expected behavior

Calls of `parseNumber('--blah42blah')` or `parseNumber('--42')` would only return with a `type === 'number'` that's a usable number.
Based on `parseNumber('++++blah42blah')` and `parseNumber('++++42')` returning `42`. I'd expect the same to work with multiple minus signs.

## Actual Behavior

The `parseNumber('--blah42blah')` or `parseNumber('--42')` calls return with a `NaN`.

## Additional context

Considering how `NaN !== NaN` this turned out to be the source of an infinite update loop that froze the browser tab if the customer accidentally tapped the '-' sign twice when entering a number. 

Note that the loop is not directly caused by Lion, but is prone to happen when the LionInputAmount is used together with a LionForm in some apps.

**Comment by riovir** [comment]
I'm planning on posting a PR for this line: https://github.com/ing-bank/lion/blob/master/packages/ui/components/localize/src/number/parseNumber.js#L118

```
const cleanedInput = matchedInput.join(''); // Instead of this
const cleanedInput = dropExtraMinuses(matchedInput.join('')) // This where dropExtraMinuses() keeps the first '-' and wipes the rest of the occurrences from the string. So '---42' -> '-42'
```

**Comment by tlouisse** [comment]
@riovir Thanks for proposing the fix!

Which component causes the infinite loop if I may ask? LionInputAmount?

**Comment by tlouisse** [comment]
Thanks for the good explanation 👍

Maybe we are also able to catch this here:
https://github.com/ing-bank/lion/blob/master/packages/ui/components/form-core/src/FormatMixin.js#L81
(probably using the [notEqual](https://github.com/lit/lit/blob/main/packages/reactive-element/src/reactive-element.ts#L376) from lit here, would also fix it)

**Comment by riovir** [comment]
One question though: when the value of LionInputAmount is resulting in a `NaN` wouldn't a `new Unparseable(this.value)` work better? In our apps we type the modelValue as `number | null | Unparseable`. What 95% of app teams don't do is to write code that defends against `NaN` after they checked that the `typeof modelValue === 'number'`.

One possible approach here was my change to the `parseNumber` which is not enough, as we also got a reported bug about the LionInputAmount not handling a value like "999999999999999999999999999999934.42" well also resulting in a `NaN`. (In fact this was the original value that triggered the infinite loop: a customer pasting a waaay too big number)

**Comment by tlouisse** [comment]
> One question though: when the value of LionInputAmount is resulting in a `NaN` wouldn't a `new Unparseable(this.value)` work better? In our apps we type the modelValue as `number | null | Unparseable`. What 95% of app teams don't do is to write code that defends against `NaN` after they checked that the `typeof modelValue === 'number'`.
> 
> One possible approach here was my change to the `parseNumber` which is not enough, as we also got a reported bug about the LionInputAmount not handling a value like "999999999999999999999999999999934.42" well also resulting in a `NaN`. (In fact this was the original value that triggered the infinite loop: a customer pasting a waaay too big number)

Really good point, Unparseable would be a way better fit (also for giving better feedback in the validation).
Would you mind to do a PR for this? :) Or otherwise create an issue?

**Comment by riovir** [comment]
Created issue: https://github.com/ing-bank/lion/issues/2233
I either will be able to submit a PR this afternoon or won't be able for some time.

**Comment by tlouisse** [comment]
The best way to incorporate the `hasChanged` check (accommodating for NaN === NaN as well) in sync updates inside FormatMixin, would be wrapping up this wip PR: https://github.com/ing-bank/lion/pull/1914/files#diff-34fc2e999d85288efe2f26617206b27c1b6ccf878fb1464f02109b46c74d63b5L78
