### ISSUE TITLE
[LionInputAmount] uses `NaN` where `Unparseable` would be preferred

### ISSUE THREAD

**Issue by riovir** [ing-bank/lion#2233]
## Expected behavior

The LionInputAmount `modelValue` being a safe-to-use number if `typeof modelValue === 'number'`.

## Actual Behavior

Values such as '--42' or '9999999999999999999999999999999999,42' result in the component's `modelValue` to become `NaN`.

## Additional context

This would make it safer for apps to process the value, as most devs arguably don't account for `NaN` values. This can become especially problematic if some form of infinite loop prevention relies on a basic equality check, since `NaN !== NaN`.

**Comment by riovir** [comment]
I'm thinking of editing `parseAmount` to double check the amount before returning.

```
export function parseAmount(value, givenOptions) {
	// ...

	// round() is caught off-guard by something like 42e30 and sometimes returns with NaN if maximumFractionDigits is defined
	const amount = round(number, options.maximumFractionDigits); // Note that for large number this returns NaN
	if (isNaN(amount)) { return; }
	return amount;
}
```

**Comment by riovir** [comment]
I'm not yet quite sure if `round()` can salvage a case with numbers using e-notation (huge or, very small). What would you expect happening if I call `parseAmount('99999999999999999999.123', { maximumFractionDigits: 2 })`? Just skip the rounding if `String(number).includes('e')`?

**Comment by gerjanvangeest** [comment]
Hi @riovir,

That sounds like a good plan. We also have a task on our board to set it to `Unparseable` is any letter is used.
Currently we ignore them and filter them out. So i guess we can combine these together in 1 fix.
