### ISSUE TITLE
[calendar] It should be possible to select date equal to maxDate and not beyond.

### ISSUE THREAD

**Issue by TvBrandenburg** [ing-bank/lion#224]
Hi all, 

Please find a description of the behaviour I observed while using the LionInputDatepicker with a maxDateValidator.
If you:
    use the validator with a date set in the future you can see that the supplied date is greyed out and cannot be selected.
    use the validator with a date set to today or a date in the past I can see that the focus is on the max date -1, however you are able to select today's date! 

The max date that is provided to the validator allows for selecting dates up to and including the max date when the max date is in the past or set to today. If the max date is set to a date in the future you can select dates up to and NOT including the max date.

**Comment by tlouisse** [comment]
Not sure if I understand you correctly, but am I right that you would expect to see this error:
- a max date in the future (let's say `2018/06/24`) results in `2018/06/23` being selectable and `2018/06/24` **not** being selectable.

If the above assumption is right, then I can't reproduce it. See: https://codesandbox.io/s/sad-mayer-6zl1b

Can you tell me if my assumption is right. And if not, fork this example with and add a failing case?

**Comment by tlouisse** [comment]
Spoke to @TvBrandenburg and can reproduce the issue by removing the `.modelValue`: updated the codesandbox and now `2018/06/24` is not selectable
