### ISSUE TITLE
NPM library does not have the latest code 

### ISSUE THREAD

**Issue by NeelSinha** [ing-bank/lion#2260]
The PR https://github.com/ing-bank/lion/pull/2248 is merged but the code does not reflect on the npm package, the code is merged to master though

## Expected behavior

Latest master code should be served to npm library.

## Actual Behavior

The npm library still has the older code.
Might be there was a failed step in the build pipeline.

## Additional context

version: 0.6.1

**Comment by gerjanvangeest** [comment]
Yes indeed i am already looking into it.

**Comment by NeelSinha** [comment]
This is resolved
