### ISSUE TITLE
[LionSwitch]: Clicking on label tiggers checked-changed twice

### ISSUE THREAD

**Issue by gyulus3** [ing-bank/lion#2284]
**Expected behavior**

Clicking on the label changes the checked value of the switch.

**Actual Behavior**

Clicking on the label doesn't change the checked value of the switch, because event `checked-changed` is triggered twice, so it changes back to the original value.

**Comment by gerjanvangeest** [comment]
The expected behavior is that it only should focus the switch.

But indeed ideally it should not send the `checked-changed` event at all.

@gyulus3 are you willing to dive into this and and create a fix PR?

**Comment by gerjanvangeest** [comment]
@gyulus3 you are indeed correct. I answered without double checking the code. And we even have a test saying so:

```js
it('clicking the label should toggle the checked state', async () => {
```

[./packages/ui/components/switch/test/lion-switch.test.js#L42](https://github.com/ing-bank/lion/blob/c34eb6c7824547f52fb44fa3ef180cf12ac72141/packages/ui/components/switch/test/lion-switch.test.js#L42)

So only the duplicate clicking should be fixed.

**Comment by gyulus3** [comment]
Issue is solved by a closed pull request.
