### ISSUE TITLE
Providence analytics failing to install

### ISSUE THREAD

**Issue by nathan-collins** [ing-bank/lion#2307]
https://www.npmjs.com/package/providence-analytics
According to the documentation on npm this should be installed with `npm i --save-dev providence-analytics`, we are receiving a request to login to npm before installing.

![image](https://github.com/ing-bank/lion/assets/748681/2f6f7849-8f1b-4453-8e7d-a54c8216244f)

**Comment by gerjanvangeest** [comment]
Resolved this issue one on one.
