### ISSUE TITLE
[LionOverlays]: Doesn't close when clicking outside of iframe

### ISSUE THREAD

**Issue by gyulus3** [ing-bank/lion#2315]
## Expected behavior

Overlay closes when clicking outside of iframe.

## Actual Behavior

Overlay stays open when clicking outside of iframe.

**Comment by tlouisse** [comment]
Hi @gyulus3 it's hard to detect for us what happens outside an iframe (we can only detect that an iframe loses focus, not whether a parent document is clicked).

In this case the parent document probably has to communicate to the iframe (child document) that a click was triggered.
In the child document, you can then close the relevant overlays based on that

**Comment by gyulus3** [comment]
Hi @tlouisse! I've already created a PR for this issue where it basically listens for the blur event on the window. Please check this out: https://github.com/ing-bank/lion/pull/2316
