### ISSUE TITLE
[LionOverlays]: Close Button ('x') causes growing margin-right on body element

### ISSUE THREAD

**Issue by ka9de** [ing-bank/lion#2323]
## Expected behavior

I expect the dialog/overlay to not add margin on my body element when I open and close it, if using the x-button.

## Actual Behavior

When I use a dialog with x-button in the header, **hovering** this button causes a growing **margin-right** on the body element. So if you open and close the dialog repeatedly (using the x-button and waiting 3 seconds after opening), your body element will get smaller and smaller, causing the background (white) to appear on the right side.

This is caused by the x-buttons **tooltip**, which is calling the _keepBodySize method of OverlayController.js and interfering with the values that have been set by the OverlayManager before.

**Comment by tlouisse** [comment]
Likely solution:

We should add on top of https://github.com/ing-bank/lion/blob/master/packages/ui/components/overlays/src/OverlayController.js#L790
 
```
if (!this.preventsScroll) return;
```

And then we need a test for this

**Comment by ka9de** [comment]
Hi @tlouisse 
I created a PR https://github.com/ing-bank/lion/pull/2331 but I am really not familiar with Github and changesets, obviously something did now work correctly.

**Comment by tlouisse** [comment]
closed by https://github.com/ing-bank/lion/pull/2331
