### ISSUE TITLE
[lion-form] resetModelValue doesn't update if number of inputs changes

### ISSUE THREAD

**Issue by mihaisavezi** [ing-bank/lion#235]
## What happens

1.  I have a form with 10 input controls, set dynamically based on a config.
2. On changing the config and providing 9 input controls, it renders correctly,
3. I need to reset the modelValue for every control in the form, calling ```resetGroup``` on formElement
4. But the resetModelValue properties do not update to reflect the fact that I have 9 input controls now.
5. This triggers an error, and the form tries to set a modelValue on a non-existing property.

## What I've tried

1. Tried first triggering the ```updateComplete``` lifecycle method to update the form and then calling resetGroup. But the result is the same.

## Bug sample reproduction

https://codesandbox.io/s/lion-form-dynamic-controls-ppfog

**Comment by tlouisse** [comment]
@mihaisavezi thanks for the bug report. It should be fixed here: https://github.com/ing-bank/lion/pull/241/commits/4cae67955ba4c0d964d288b4a7f88025c0197748#diff-ede1fc987c4e048330c6e79d1dba5324R675
