### ISSUE TITLE
Remove SlotMixin Test with wrong assumption about polyfill being loaded

### ISSUE THREAD

**Issue by aghArdeshir** [ing-bank/lion#2358]
## Expected behavior

There is a test with title: `does not scope elements when polyfill not loaded` in context of `SlotMixin - Scoped Registries`, and there is a polyfill being loaded in the `web-test-runner.config.mjs`: 
```
    <script src="/node_modules/@webcomponents/scoped-custom-element-registry/scoped-custom-element-registry.min.js"></script>
```

So I believe this test is having wrong assumption. 

## Actual Behavior

I created this draft PR as a proof: https://github.com/ing-bank/lion/pull/2357

This test fails when polyfill is not loaded, but passes as soon as you add back the polyfill in the web-test-runner.config file.

## Additional context

I really don't understand the context of these scoped elements really that much, so these changes are kinda done blindly, based on the obvious facts I observed (title of the test for instance)

I faced this blocker when trying to run every test with both polyfill loaded and without polyfill loaded for this PR: https://github.com/ing-bank/lion/pull/2353

What I want to ideally achieve is to be able to get rid of this test. Remove it completely.

**Comment by tlouisse** [comment]
closed by https://github.com/ing-bank/lion/pull/2407
