### ISSUE TITLE
FocusHost type is not exported + PR

### ISSUE THREAD

**Issue by riovir** [ing-bank/lion#2366]
This issue is similar to https://github.com/ing-bank/lion/issues/1903.

## Expected behavior

`import type { FocusHost } from '@lion/ui/types/form-core.js';` would work.

## Actual Behavior

Type error, as the type is not exported.

## Additional context

This blocks a bundler from generating a valid `index.d.ts` for components directly using the `FocusMixin`.

**Comment by riovir** [comment]
Submitted PR here: https://github.com/ing-bank/lion/pull/2367

**Comment by tlouisse** [comment]
Fixed by https://github.com/ing-bank/lion/pull/2367
