### ISSUE TITLE
[LionCalendar] recent fix causes TypeScript error due to firstUpdated signature

### ISSUE THREAD

**Issue by riovir** [ing-bank/lion#2378]
## Expected behavior

The type signature of the LionCalendar matches Lit's and super is called.

## Actual Behavior

Using the LionCalendar from @lion/ui breaks type definition generation via Rollup + typescript.

## Additional context

The following fix (which my team also appreciates very much) unfortunately missed two details:
- super hasn't been called
- the type signature was incorrect (see: https://github.com/ing-bank/lion/blob/96b09e56d1e85c9bb9743a886051ff12db7f4ba0/packages/ui/components/steps/src/LionStep.js#L93 for a correct example)

/** @param {import('lit').PropertyValues } changedProperties */
  firstUpdated(changedProperties) {
    super.firstUpdated(changedProperties);

**Comment by tlouisse** [comment]
fixed by https://github.com/ing-bank/lion/issues/2378
