### ISSUE TITLE
[lion-form] resetModelValue gets the last updated Modelvalue when additional inputs are added dynamically

### ISSUE THREAD

**Issue by zanfirandra** [ing-bank/lion#239]
### Context
Have a from with initially 3 inputs
1. modelValue changes dynamically for one of them
2. inputs in form are also added dynamically

I want to reset the modelValue of the entire form group so I call resetGroup function

###  What happens
Always getting the previous modelValue instead of initial values

### What should happen
When adding another input field dynamically and changing the modelValue, when the resetGroup function is called, modelValue should reset to the initial values.

### Bug sample reproduction 
https://codesandbox.io/s/3yeyj

**Comment by tlouisse** [comment]
@zanfirandra : thanks for the bug report 👍 It should be fixed here: https://github.com/ing-bank/lion/pull/241/commits/4cae67955ba4c0d964d288b4a7f88025c0197748#diff-ede1fc987c4e048330c6e79d1dba5324R689
