### ISSUE TITLE
[lion-form]/[lion-button] Submit on `enter` keypress is triggered twice

### ISSUE THREAD

**Issue by dancarlocanlas** [ing-bank/lion#240]
## Steps to reproduce
1. Create a form using `lion-form`
2. Add a submit button using `lion-button`
3. Submit form by pressing `enter`
4. The `submit` event is dispatched twice

I did some checking and it seems that the root cause lies within the `lion-button` element, specifically in the click handler / redispatching of the click event. The default click event does not stop propagating, or might have reached the `form` element before the propagation was stopped.

**Comment by jorenbroekema** [comment]
Confirmed, have reproduced this in Google Chrome
