### ISSUE TITLE
Reporting bug on "reporting bug" 📟 

### ISSUE THREAD

**Issue by takrishna** [ing-bank/lion#2403]
## Expected behavior
The link in "Actual Behavior" section for "live code reproduction" is not rendering anything.

e.g., opening the below URL results in a "empty" render
https://studio.webcomponents.dev/edit/OJTxKWU06xEJGaI2AFSG

![image](https://github.com/user-attachments/assets/c7ae7a19-d7f4-4cec-b396-975d95aac801)

## Actual Behavior

Describe what happens instead. Best via a live code reproduction.
To create one click the link below and edit away.
Once the error is reproduced fork/safe and link it.

https://studio.webcomponents.dev/edit/OJTxKWU06xEJGaI2AFSG

## Additional context

Which component and version of it are you using.

**Comment by rajithaeyee** [comment]
@takrishna You're absolutely right! The given sandbox is indeed missing a few important things:
1. dependencies for the lion tooltip in package.json 
2. relavant esmodule import in index.js

working example here-> https://studio.webcomponents.dev/edit/4TFVd8JS6lCLMZL3KghI/src/index.js?p=README.md

**Comment by tlouisse** [comment]
Thanks both, for pointing this out 👍 
The second example still fails for me @rajithaeyee.

We can maybe move to this Stackblitz example: https://stackblitz.com/~/github.com/Knorgias/lion-demo

**Comment by tlouisse** [comment]
Thanks for reporting this @takrishna and @rajithaeyee 
I updated the issue template in this pr: https://github.com/ing-bank/lion/pull/2413
