### ISSUE TITLE
[localize] Error when retrieving the group separator for 'es-ES'

### ISSUE THREAD

**Issue by jcperea** [ing-bank/lion#244]
After the last update on Chrome (V8 7.6.303.29), it seems they have followed the rule to avoid the space separator to isolate a single digit, at least in es-ES. This makes the code you are using at `lion/packages/localize/src/number/getGroupSeparator.js` return a '0' as separator when the locale is `'es-ES'`. You can avoid this behaviour by formatting the number 10000 and returning the third character:

```
...
  }).format('10000');
  return normalSpaces(formattedNumber[2]);
}
```
[](url)
You can see the link to this rule at [wikipedia](https://en.wikipedia.org/wiki/Decimal_separator#Exceptions_to_digit_grouping) pointing to the International Bureau of Weights and Measures... :-/

**Comment by tlouisse** [comment]
It is probably a Chrome bug.
Could you do a merge request to fix it?
Would be a matter of adding this line here:https://github.com/ing-bank/lion/pull/230/files#diff-c415b3c1e169f89335d4e3b1a5d82194R27

But then for locale `es-ES`, with a small test that checks this fix.

**Comment by jcperea** [comment]
I can do the merge with this change, but I need this behavior to be also present at `getGroupSeparator.js` since I'm using a library that uses it. What do you think about updating the code at `lion/packages/localize/src/number/getGroupSeparator.js` for 

```js

  }).format('10000');
  return normalSpaces(formattedNumber[2]);
}
```

**Comment by tlouisse** [comment]
Yeah, then it seems like we need to do the normalization on different layers (currently it's only used in formatNumberToParts). 
@jorenbroekema  might have time to look into this in the coming weeks, a proposal (leading to a mr) would also still be welcome :)

**Comment by jcperea** [comment]
https://github.com/ing-bank/lion/pull/245

**Comment by tlouisse** [comment]
Thanks for the contribution of the tests 👍 
Should the separator be a comma ([this list](https://en.wikipedia.org/wiki/Decimal_separator#Exceptions_to_digit_grouping
) says Spain uses a comma separator) or a dot (like [your test](https://github.com/ing-bank/lion/pull/245/files#diff-8a77a31cf274d13e5c51f8b2fb174491R10) suggests).

**Comment by jcperea** [comment]
The comma is the decimal separator; the dot is used as a group separator as I say on the test. (it is also on the link you sent)

**Comment by gerjanvangeest** [comment]
Was fixed in: https://github.com/ing-bank/lion/pull/245
