### ISSUE TITLE
[lion-button] IE11 - submit event not called on enter keypress when there are multiple inputs

### ISSUE THREAD

**Issue by zanfirandra** [ing-bank/lion#249]
### Context
Browser: IE11.
Have a simple form with initially one input and submit event on the form.
I want to submit the form by pressing the enter key.

### Steps to reproduce
1. For the inital form, press the enter key to submit form.
2. Add another type of field, e.g one radio group.
3. Submit form by pressing the enter key.
2. Add another input in the form.
3. Submit form by pressing the enter key.

### What happens
Submit event is working for a form with one input and another type of field, but when adding another input, submit event listener is not called.

**Comment by jorenbroekema** [comment]
I cannot reproduce this in the same way you have it.

What version of @lion are you running? Did you try it on the latest version?
If so, can you show me your code that reproduces the issue?

**Comment by jorenbroekema** [comment]
Update: seems to be related to lion-button

**Comment by jorenbroekema** [comment]
Update: 

Can be reproduced by just:
```js
const submitForm = () => console.log('hey');
return html`
  <form id="form" @submit=${submitForm}>
    <h3>Details</h3>
    <input name="input1" />
    <input name="input2" />
    <input name="input3" />
    <lion-button>Submit</lion-button>
  </form>
`;
```
Changing it to a regular button works fine on Chrome at least

**Comment by jorenbroekema** [comment]
Aaand another update. This is not related to lion-button, because I can reproduce this issue with just:

```js
const submitForm = () => console.log('hey');
return html`
  <form id="form" @submit=${submitForm}>
    <h3>Details</h3>
    <input name="input1" />
    <input name="input2" />
  </form>
`;
```
Will investigate further, see if this is related to lit-html in IE11.
