### ISSUE TITLE
[select-rich] Shows incorrect option as selected when new option is added

### ISSUE THREAD

**Issue by littletv** [ing-bank/lion#265]
## Steps to reproduce

1. Create a select using `select-rich`
2. Select any option (i.e option with index=1)
2. Add new option at selectedItem index
3. Open & close select
4. Newly added option is auto selected

I have created a new story book, to reproduce it.

https://github.com/littletv/lion/tree/select-rich-issue

**Comment by jorenbroekema** [comment]
I see, I don't think we thought of this edge case while making this, we certainly don't test for it. Perhaps you could contribute a failing test through a PR or even also fix it 🤗 ?

**Comment by rodrigo-garcia-leon** [comment]
Hey, is this issue still relevant? and if so can I work on it? 🧐

**Comment by gerjanvangeest** [comment]
> Hey, is this issue still relevant? and if so can I work on it? 🧐

Yes, that would be great

**Comment by rodrigo-garcia-leon** [comment]
Perfect ✨
