### ISSUE TITLE
[lion-radio-group] Getting serializedValue when no radio is selected throws an error

### ISSUE THREAD

**Issue by SantiEspada** [ing-bank/lion#266]
## Steps to reproduce
1. Create a lion-radio-group with no value pre-selected
```js
<lion-radio-group id="dinosRadioGroup" name="dinosGroup" label="What are your favourite dinosaurs?">
    <lion-radio name="dinos[]" label="allosaurus" .choiceValue=${'allosaurus'}></lion-radio>
    <lion-radio name="dinos[]" label="brontosaurus" .choiceValue=${'brontosaurus'}></lion-radio>
    <lion-radio name="dinos[]" label="diplodocus" .choiceValue=${'diplodocus'}></lion-radio>
</lion-radio-group>
```
2. Try to call `serializedValue` on `lion-radio-group`, it fails
```js
console.log(dinosRadioGroup.serializedValue);
// Uncaught TypeError: Cannot read property 'serializedValue' of undefined
```
3. Select any radio input
4. Calling again `serializedValue` on `lion-radio-group` works as expected
```js
console.log(dinosRadioGroup.serializedValue);
// {value: "allosaurus", checked: true}
```

I don't know what could be the best value for `serializedValue` when no choice is selected, but in my opinion it definitely shouldn't thrown an error.

**Comment by jorenbroekema** [comment]
https://github.com/ing-bank/lion/pull/255 fixes that I believe.
