### ISSUE TITLE
[localize] formatNumber function returns 'č' when the currency is 'CZK'

### ISSUE THREAD

**Issue by revoul** [ing-bank/lion#272]
Hi guys!

I'm using the formatNumber function of @lion/localize and I think it has an unexpected behavior.

```html
<html lang="cs-CZ">
```
```js
const myNumber = formatNumber(1000, {
    style: 'currency',
    currencyDisplay: 'symbol',
    currency: 'CZK',
});
```
The return value is 1 000,00 `č`, when I hope to receive 1 000,00 `Kč`.

Example: https://codesandbox.io/embed/magical-banzai-70smm

**Comment by jorenbroekema** [comment]
Thanks for the codesandbox, makes it pretty clear the difference between Intl and our own formatter.

From first glance I'm not sure what the cause is.

Perhaps you can do a PR for a fix?
