### ISSUE TITLE
[checkbox-group] checkedValues API feature specs

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#277]
For radio-group, it is possible to get the property `.checkedValue` which will return a string: either empty if nothing is selected, or the string value of the checked radio element within the radio group.

We have discussed already that we want the same thing for checkbox-group, but the API will be slightly different because you can select multiple options:
`checkboxGroup.checkedValues` which returns an array of strings (or an empty array if nothing is selected).

We also want a setter for .checkedValues where you can do something like: `checkboxGroup.checkedValues = ['diplodocus', 't-rex']` where the strings need to correspond to actual values of existing checkboxes in the checkbox-group. 

This has been on our backlog for a bit but I'm opening this issue now to ask if someone feels up for making this feature. Needs to be tested of course as well :).

**Comment by NioniosSpeed** [comment]
Hey @jorenbroekema can I pick this up? :-)

**Comment by gerjanvangeest** [comment]
> Hey @jorenbroekema can I pick this up? :-)

Yes that would be great!!

**Comment by jorenbroekema** [comment]
Hey Dio, just closing this issue as per our new way of handling feature requests. We will still of course review your pull request for this as soon as we are able!! :) sorry for taking long on it

**Comment by jorenbroekema** [comment]
https://github.com/ing-bank/lion/pull/507 will tackle the need for getting / setting the array of values that are checked, through the modelValue directly.
