### ISSUE TITLE
[input-amount] Should accept all different minus sign unicode variations

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#280]
There is only a few sensible things a user can input in an input-amount: digits, group seperators, decimals and finally, minus sign. For the minus sign however, lots of different characters look like a minus sign.

- Hyphen-minus
- Figure dash
- En dash
- Em dash
- Small Em Dash
- Small hyphen-minus
- Hypen
- Non-breaking hyphen

Right now we only seem to support 1 variation: Hyphen-minus
```js
const regexMinusSign = /[-]/;
```

Should we support all? I think the parser should be powerful enough to accept at least the most common ones :). 

More background http://jkorpela.fi/dashes.html 

Marking as bug, because using − (&minus;) in input-amount atm is bugged, it removes it completely.

**Comment by gerjanvangeest** [comment]
Fixed in: https://github.com/ing-bank/lion/pull/279
