### ISSUE TITLE
[localize] date formatting forced

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#296]
Formatting options for year, month and day are forcibly set. It's not possible to format a date without a year right now. See: https://github.com/ing-bank/lion/blob/master/packages/localize/src/date/formatDate.js#L22

For example with native Intl this prints the date of today without the year:
```
new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'long' }).format(new Date());
```

Passing the same options to `parseDate` forcibly adds the year.

**Comment by daKmoR** [comment]
how would you like to do it? with `false`?
```js
formatDate(new Date(), { year: false }); // return 10/30 // depending on locale and date
```

**Comment by LarsDenBakker** [comment]
I expect `formatDate` to accept the same options as `Intl.DateTimeFormat`. So to leave out the year we don't pass an option.

**Comment by r4zorgeek** [comment]
@LarsDenBakker Hey I am new to open source. Can I take this issue?

**Comment by gerjanvangeest** [comment]
> @LarsDenBakker Hey I am new to open source. Can I take this issue?

I know @LarsDenBakker is busy with a lot of other issues as well. So I am quite sure he doesn't mind if you add this feature.

**Comment by LarsDenBakker** [comment]
Yeah go aheae

**Comment by r4zorgeek** [comment]
@LarsDenBakker @gerjanvangeest  Hey can you explain the issue in detail. Sorry for the inconvenience new to open source.
According to my understanding of the problem, we want a date without year for that to happen we will not pass the year in options. Correct me if I am wrong.

So basically to solve I removed line no. 23 from formatDate.js

**Comment by r4zorgeek** [comment]
@LarsDenBakker @gerjanvangeest 
also if we remove these lines i think dates formatting would not be forced.
if (options && !(options && options.year)) {

  }

**Comment by gerjanvangeest** [comment]
> @LarsDenBakker @gerjanvangeest
> also if we remove these lines i think dates formatting would not be forced.
> if (options && !(options && options.year)) {
> 
> }

Yes, and also the lines for `day` and `month`.

Please also add some tests and fix where needed. And add an example to the storybook demo.

**Comment by r4zorgeek** [comment]
@LarsDenBakker @gerjanvangeest Fixed the issue. Please review it. Also added test cases and demo in storybook.
