### ISSUE TITLE
[LionCalendar] month navigation wrong when minDate is end of a month

### ISSUE THREAD

**Issue by phasic** [ing-bank/lion#302]
# Issue 1: MinDate is last day of previous month

## Given

```lion-input-datepicker``` with the following data:

- selected date: 2019/09/15
- minimum date: 2019/08/31
- maximum date: 2019/12/31 

## Expected behaviour

When opening the datepicker, we are able to click to the previous month (August) and select the 31st.

## Actual behaviour

The 'previous month' button is enabled, but the navigation behind it does not happen. We are unable to go to August

## Origin of the issue:

The issue is within the method ```__findBestEnabledDateFor``` in ```LionCalendar.js```;

Here the ```futureDate``` is set correctly ( 31st of August, which is the minDate ).

But once we start looping from this date until 2 years in the future to get a suitable date, the first thing that happens is: + 1 day —> which is 1st of September

## Proposed solution
```
 __findBestEnabledDateFor(date, { mode = 'both' } = {}) {
    let tmpMinDate = new Date(this.minDate);
    tmpMinDate.setDate(tmpMinDate.getDate() -1);	//Get the minDate and go back one day, so we assure the minDate is also a valid date to have
    const futureDate =
      this.minDate && this.minDate > date ? tmpMinDate : new Date(date);
    const pastDate = this.maxDate && this.maxDate < date ? new Date(this.maxDate) : new Date(date);

    let i = 0;
    do {
      i += 1;
      if (mode === 'both' || mode === 'future') {
        futureDate.setDate(futureDate.getDate() + 1);	//The bug got introduced here. The first day he really checks is minDate + 1 and not minDate. So the check starts from September 1st
        if (this.__isEnabledDate(futureDate)) {
          return futureDate;
        }
      }
      if (mode === 'both' || mode === 'past') {
        pastDate.setDate(pastDate.getDate() - 1);
        if (this.__isEnabledDate(pastDate)) {
          return pastDate;
        }
      }
    } while (i < 750); // 2 years+

    const year = date.getFullYear();
    const month = date.getMonth() + 1;
    const day = date.getDate();
    throw new Error(
      `Could not find a selectable date within +/- 750 day for ${year}/${month}/${day}`,
    );
  }
```

This solution made me discover a second bug:

# Issue 2: When coming from last day of month the next month is skipped

## Given

```lion-input-datepicker```with the following data:

- selected date: 2019/08/31
- minimum date: 2019/08/31
- maximum date: 2019/12/31 

## Expected behaviour

When 31st of August is selected, when I press next month: I expect that September is visible.

## Actual behaviour:

When clicking on next month, September is skipped and October is shown.

## Origin of the issue

The issue is within the method ```__modifyDate``` in ```LionCalendar.js```

In the following line:

```    tmpDate[`set${type}`](tmpDate[`get${type}`]() + modify);```

variables at this moment:

- tmpDate : Sat Aug 31 2019 00:00:00 GMT+0200 (Central European Summer Time)
- modify : 1
- type : Month

So what happens is we increment August 31st with 1 month 

—> tries to go to September 31st 

—> does not exist, so we go to October 1st.

What should happen that he falls back to September 30th.

## Conclusion

If there is any other information needed on how to reproduce it, let me know. 
I also can shoot in a pull request on a later time with the proposed fixes. But I prefer to align on it beforehand, so I am sure I'm following the guidelines and I am sure the solution does not introduce any new bugs.

**Comment by gerjanvangeest** [comment]
Issue 1 is solved in: https://github.com/ing-bank/lion/pull/286/files

I believe it could also have been fixed by switching the order:

```js
if (this.__isEnabledDate(futureDate)) {
  return futureDate;
}
futureDate.setDate(futureDate.getDate() + 1);
```

For issue 2 we have to check how to fix that.

**Comment by CubLion** [comment]
@phasic can you confirm that both reported issues work with the changes we made?
@gerjanvangeest when should we close this issue?

**Comment by gerjanvangeest** [comment]
The bugfix is merged, so we can close it. @phasic please reopen if you still have questions.
