### ISSUE TITLE
fieldset do not show feedback if the first validation fails

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#305]
Fieldset does not show validation message of its validator if first validation of child component fails

How to reproduce the error:
```
let fakeValidator = (...factoryParams) => [
  (...params) => ({'validator': isFakeValidator(...params)}),
  ...factoryParams
];

function isFakeValidator() {
  return false;
}

return html`
  <lion-fieldset
    id="test-fieldset1"
    name="test-fieldset1"
    .errorValidators=${[fakeValidator()]}
  >
    <lion-input-amount name="input1"></lion-input-amount>
  </lion-fieldset>
`;
```
If you click on input1 and enter ther for example letter 'b' validator of input-amount display error. Then fakeValidator will run but fieldset thase not show error feedback becaouse of roule: "touched && dirty && !prefilled". Input1 will be touched when you click outside component and blure event will be produced. In this case, the only chance to display the error for fieldset is to set the correct value in input1 and re-enter the error.

If at first you 'touch' input and then put the wrong value everything is fine

Is this a bug or a feature?

**Comment by gerjanvangeest** [comment]
I don't fully follow your question or explanation, so correct me if i'm wrong.

1. For `fieldsets` we hide the validation messages for now: https://github.com/ing-bank/lion/blob/master/packages/fieldset/src/LionFieldset.js#L204
2. On the `input-amount` we already added a `isNumberValidator` that gets triggered as you described above.

I hope this answers your question, if so please close the issue.

**Comment by lfusiara** [comment]
The `fakeValidator()` does not have hidden attribute so it should be presented. And it will be as described above but only when `input-amount` field will be at first focused then blured and after that you will put wrong number to `input-amout`

**Comment by gerjanvangeest** [comment]
I can see the error you are talking about, by setting the same validator on a normal input it was easier to see what goes wrong.

```js
  let isFakeValidator = (...factoryParams) => [
    (...params) => ({ 'isFake' : isFake(...params) }),
     ...factoryParams
  ];

  function isFake() {
    return false;
  } 

  return html`
    <lion-fieldset
      label="fieldset"
      name="fieldset1"
      .errorValidators=${[isFakeValidator()]}
    >
      <lion-input 
        label="input"
        name="input1"
        .errorValidators=${[isFakeValidator()]}
      ></lion-input>
    </lion-fieldset>
  `;
```

I can see the error is somewhere in the `ValidationMixin` which is currently being refactored. I'll keep this issue open for now and once the refactoring is done we can check if this issue still occurs.

**Comment by jorenbroekema** [comment]
We are currently busy doing lots of work to get fieldset validation working properly, which has proved challenging.

For now, I would like to provide you with a quick hotfix you can try on your end to at least manually force the validation message to show. You can do this by setting `.errorShow = true;` on the fieldset.

You could fire that for example on blur on a specific field 
```js
myField.addEventListener('blur', () => { myFieldset.errorShow = true; })
```

Admittedly a "hacky workaround" but hopefully enough to unblock you guys for the short-term.

**Comment by gerjanvangeest** [comment]
Issue is solved in https://github.com/ing-bank/lion/pull/357 please reopen if you still have questions.
