### ISSUE TITLE
[button] always submit the form 

### ISSUE THREAD

**Issue by igomezal** [ing-bank/lion#316]
With the new change in lion-button, it always submits the form even if you try to catch the event and prevent the default behavior of it (with `ev.preventDefault()`).

It seems to be caused by https://github.com/ing-bank/lion/blob/master/packages/button/src/LionButton.js#L177

```javascript
  __clickDelegationHandler() {
    if (this.type === 'submit' && this._nativeButtonNode && this._nativeButtonNode.form) {
      this._nativeButtonNode.form.dispatchEvent(new Event('submit'));
      this._nativeButtonNode.form.submit();
    }
  }
```

Although it tries to replicate the behavior of a native form, it is not working correctly.

Here you have an example of two forms using lion-button and another two using a native button, each example is listening to different events to show how `ev.preventDefault()` should work.

https://stackblitz.com/edit/submit-lion-button?file=index.js

**Comment by igomezal** [comment]
It seems tests are not really checking the functionality correctly, as they are overwriting the submit method from the form HTMLElement: https://github.com/ing-bank/lion/blob/master/packages/button/test/lion-button.test.js#L236

It shouldn't be needed if you are already doing the standard event.preventDefault in the submit or click event: https://github.com/ing-bank/lion/blob/master/packages/button/test/lion-button.test.js#L229

For example:
```javascript
it('behaves like native `button` when clicked', async () => {
      const formSubmitSpy = sinon.spy(e => e.preventDefault()); // You should only need to do this
      const form = await fixture(html`
        <form @submit="${formSubmitSpy}">
          <lion-button type="submit">foo</lion-button>
        </form>
      `);
      // Prevent page refresh
      form.submit = () => {}; // You shouldn't need to do this

      const button = form.querySelector('lion-button');
      getTopElement(button).click();

      expect(formSubmitSpy.called).to.be.true;
    });
```

Instead this test should be something like:

```javascript
it('behaves like native `button` when clicked', async () => {
      const formSubmitSpy = sinon.spy(e => e.preventDefault());
      const form = await fixture(html`
        <form @submit="${formSubmitSpy}">
          <lion-button type="submit">foo</lion-button>
        </form>
      `);

      const button = form.querySelector('lion-button');
      getTopElement(button).click();

      expect(formSubmitSpy.called).to.be.true;
    });
```

**Comment by jorenbroekema** [comment]
Did you try if that test runs now that the page refresh is not explicitly prevented by setting the submit method to an empty function? 

Because that line of code definitely looks like it was added because the `preventDefault()` wasn't enough. If so, question would then be why it isn't enough, because I agree with you that we shouldn't need to do that 😅.

We're looking into this as pretty high prio by the way, just to give an update on it

**Comment by igomezal** [comment]
No, they are failing right now because the page is being reloaded and with `form.submit = () => {}`, it is just hiding the bug.

That's why in the pull request I added new tests and removed the overwriting of the submit function so that we will have tests with what a button should do.

**Comment by gerjanvangeest** [comment]
I believe I have it fixed here: https://github.com/ing-bank/lion/pull/328

**Comment by igomezal** [comment]
I just tested it in my component and the default behaviour of the form is not working, I think we have to add more tests which check if we don't prevent the default behaviour of the form it also works.

**Comment by gerjanvangeest** [comment]
Yes, indeed. We changed our approach and updated the merge request.

**Comment by jorenbroekema** [comment]
https://github.com/ing-bank/lion/pull/328 this should fix the issue. It took quite a lot of time to fix for all use cases properly, and have it working in all browsers properly. Sorry for the inconveniences caused by this introduced bug.

I have added some documentation that explains some of the considerations.

Will merge it next Monday, since it's time for weekend now. So if anyone wants to take a looksy before we merge, feel free :)!

**Comment by igomezal** [comment]
I just tested it in my component and it seems to work although the use case of preventing the click button does not work. But I think with the clarification in https://github.com/ing-bank/lion/blob/3d95ab22ddcbd7caf0c35a0ebf6f9ecbf937e23f/packages/button/stories/index.stories.js#L82 and maybe also adding it to the README of lion-button should enough.
