### ISSUE TITLE
lion-step enter event is dispatched before current step is changed 

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#324]
LionStep enter event is dispatched before current step is changed when using LionSteps functions,  but when using LionStep.enter(true)  current step of LionSteps is changed before event is dispatched

**Comment by gerjanvangeest** [comment]
Do you also expect the `leave` event to be dispatched after the changed event?

**Comment by lfusiara** [comment]
I think that leave event should be dispatched as it is right now before change

**Comment by daKmoR** [comment]
fixed via https://github.com/ing-bank/lion/pull/346
