### ISSUE TITLE
lion/validators.js isNumberValidator dose not use factoryParams

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#329]
`isNumberValidator` from [validators.js#L41](https://github.com/ing-bank/lion/blob/e60b819188d582e4208b50e0393d5e88dfb51444/packages/validate/src/validators.js#L41) dose not use factoryParams it should use it as rest of validators:

```
export const isNumberValidator = (...factoryParams) => [
  (...params) => ({isNumber: isNumber(...params)}),
  ...factoryParams
];

```

**Comment by daKmoR** [comment]
care to create a PR? 🤗

**Comment by devcer** [comment]
Can I take this up?

**Comment by daKmoR** [comment]
@devcer sure 🤗 feel free to open a PR 🤗

**Comment by devcer** [comment]
Submitted a PR. Thanks. :)

**Comment by gerjanvangeest** [comment]
https://github.com/ing-bank/lion/pull/334 is merged, so closing this issue
