### ISSUE TITLE
[LionTextarea] dose not support readonly attribute

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#333]
`LionTextarea `dose not support `readonly` attribute, After adding readonly attribute `textarea `is still editable.
Example:

`<lion-textarea readonly></lion-textarea>`

**Comment by gerjanvangeest** [comment]
Take a look at [input](https://github.com/ing-bank/lion/blob/master/packages/input/src/LionInput.js)  what is needed to fix this.

**Comment by ktnl97** [comment]
Hi @lfusiara, Can I pick this up?

**Comment by lfusiara** [comment]
Thanks, PR seems ok

**Comment by jorenbroekema** [comment]
Fixed here: https://github.com/ing-bank/lion/pull/348
