### ISSUE TITLE
Elements don't support self closing tags

### ISSUE THREAD

**Issue by jlengrand** [ing-bank/lion#35]
Heyo, 

Not sure this is something that can/should be fixed, but I just banged my head against it so I thought it was worth mentioning. 

I'm converting an existing form using generic HTML tags into `lion`. 

I was using lots of self-closing tags : 

```
<input 
        id="accessToken" 
        name="accessToken" 
        placeholder="accessToken">
```

converted it to : 

```
<lion-input 
        label="Personal Access Token" 
        id="accessToken" 
        type="password" 
        name="accessToken" 
        placeholder="accessToken">
```

Nothing to be seen on my page. 

I looked into imports and all, searching for a generic web-components related imports error, but the issue was simply that I was missing the closing tag `</lion-input>`.
Consequence was that I got nested elements, breaking the page :).

**Comment by jlengrand** [comment]
Understand if you close without action. I am mainly writing this in case someone else runs into the same thing converting forms in the future

**Comment by thepassle** [comment]
Web components can not be self-closing (its part of the spec)

**Comment by jlengrand** [comment]
Yeah I figured. Thanks for pointing it out :).
