### ISSUE TITLE
[LionStep] after fixing #323 if initial-step is the first step enter event is not dispatched

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#361]
After fixing bug #323 if `initial-step` is the first step enter event is not dispatched

The same situation like in bug #323 but now first step is `initial-step`

```
 return html`
      <lion-steps>
        <lion-step initial-step @enter=${e => console.log('1', e)}>
          <div>test1</div>
        </lion-step>
        <lion-step  @enter=${e => console.log('2', e)}>
          <div>test2</div>
        </lion-step>
      </lion-steps>
    `;
```
Result
Event from first step won't be dispatched anymore

**Comment by daKmoR** [comment]
this is no longer the case as far as I can tell 🤗  feel free to reopen if the bug still persists 🤗
