### ISSUE TITLE
[input-datepicker] Calendar does not show current selected date when re-opened after navigating

### ISSUE THREAD

**Issue by SantiEspada** [ing-bank/lion#364]
## Describe the bug

If the user has navigated the calendar but decided to close it without choosing a new date, when the calendar is opened again it stays in the same position (it does not navigate back to the current input value) but the day itself is focused, even though the month/year is different.

## To Reproduce

1. Go to input-datepicker story in Lion Storybook (https://lion-web-components.netlify.com/?path=/story/forms-input-datepicker--default)
2. Click on the input button to open the calendar
3. Navigate to a different month
4. Close the calendar **without** selecting any new date
5. Open the calendar again, the month you've navigated to is still shown instead of the one corresponding to the input value. Note also that the day corresponding to the input value is focused even though that is not the selected day.

## Expected behavior

The calendar should always show the current day/month/year combination of the input value when opened.

## Screenshots

![captured](https://user-images.githubusercontent.com/8306111/67945856-40356d00-fbe0-11e9-8de6-bb57fad67c17.gif)

**Comment by ovidiu1** [comment]
New Issue: Even if  you change the day/month/year in  the input  is not reflected in the pop-up.

**Comment by ovidiu1** [comment]
https://github.com/ing-bank/lion/pull/375

**Comment by gerjanvangeest** [comment]
fixed in https://github.com/ing-bank/lion/pull/475
