### ISSUE TITLE
[lion-steps] Option to Restart flow

### ISSUE THREAD

**Issue by palash2601** [ing-bank/lion#377]
Lion steps provide `previous()` and `next()` functions to navigate. One of our usecase is that  while user is on a certain step, there should be option to restart the flow from initial step.

**Proposed solutions**

Option 1
I as user of lion-steps can set `current` property to `0`. But this property is not documented. Is is a public property?

Option 2
Add `restart` function in `lion-steps` which will restart the flow and take user to `initial-step`

Which option will you suggest?

**Comment by maxevilmind** [comment]
Could somebody give an update on this one?

**Comment by daKmoR** [comment]
yes `current` is a public property and can be used to go back/forth steps programmatically.

using
```
mySteps.current = 0;
```
to go to the first step is fine 🤗 

feel free to reopen this issue or create a new one if there are still questions 🤗

**Comment by maxevilmind** [comment]
great, thank you 🙂
