### ISSUE TITLE
[ChoiceInputMixin] Name attribute for radio/checkbox children

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#390]
A cool feature would be that you don't have to do this:

```html
<lion-checkbox-group name="dinosGroup">
  <lion-checkbox name="dinos[]"></lion-checkbox>
  <lion-checkbox name="dinos[]"></lion-checkbox>
</lion-checkbox-group>
```

But you just do this:

```html
<lion-checkbox-group name="dinos">
  <lion-checkbox></lion-checkbox>
  <lion-checkbox></lion-checkbox>
</lion-checkbox-group>
```

It will set the name attribute of the checkbox (or radio) under the hood (probably on connectedCallback) by just checking if it has a checkbox|radio-group parent, querying its name attribute and appending the string with `[]`. Much more user-friendly :)

Potential problem to consider: if connectedCallback of radio/checkbox happens before group parent name attribute is resolved (e.g. if it is async for some reason). You could argue it is then the user's responsibility though, and we should not do anything for it.

**Comment by daKmoR** [comment]
this has been implemented
