### ISSUE TITLE
[form] unexpected serialization of groups

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#391]
For grouped form elements, like radios and checkboxes, the serialized result is a large result with all child element values.

I created a reproduction: https://jsbin.com/vimisivawa/edit?html,output but `unpkg` has issues loading `https://unpkg.com/@lion/validate@0.4.0/src/loadDefaultFeedbackMessages.js?module` right now. It's easy to set this up locally though, or to serialize the groups in the storybook manually since I just copied stories into one form.

For the checkbox and radio group, it serialized to:

```json
  "dinosGroup": {
    "dinos[]": [
      {
        "value": "allosaurus",
        "checked": false
      },
      {
        "value": "brontosaurus",
        "checked": false
      },
      {
        "value": "diplodocus",
        "checked": true
      }
    ]
  },
  "scientistsGroup": {
    "scientists[]": [
      {
        "value": "Archimedes",
        "checked": false
      },
      {
        "value": "Francis Bacon",
        "checked": true
      },
      {
        "value": "Marie Curie",
        "checked": true
      }
    ]
  },
```

As a form author, I would expect this to be:
```json
{
  "dinosGroup": "diplodocus",
  "scientistsGroup": ["Francis Bacon", "Marie Curie"] 
}
```

Otherwise I have to write quite a lot of transformation code to go from a serialized from to an actual form I can use in the rest of my code, or send to the back-end.

I also expect to be able to deserialize this again easily, for example with:

```json
this.shadowRoot.querySelector('lion-form').modelValue = {
  "dinosGroup": "diplodocus",
  "scientistsGroup": ["Francis Bacon", "Marie Curie"] 
};
```

or

```js
this.shadowRoot.querySelector('lion-form').deserializeGroup({
  "dinosGroup": "diplodocus",
  "scientistsGroup": ["Francis Bacon", "Marie Curie"] 
});
```

All the necessary information should be available in the registered form elements, they should not need to be repeated in the serialized result. 

For `lion-select` this does work as expected. This is serialized to:

```js
{
  "color": "teal"
}
```

And it's possible to deserialize it again, with the correct option selected.

Maybe this is something we can take along with the next breaking change?

**Comment by daKmoR** [comment]
@thatianamg valuable but also super breaking 😅

**Comment by LarsDenBakker** [comment]
Could we perhaps solve this by adding a `flatten` parameter to the `serializeGroup` method? And similarly something for deserializing?

**Comment by LarsDenBakker** [comment]
After investigation, it turns out we should be using `serializedValue` rather than `serializeGroup()`. Then it works correctly for the radio group, though the checkbox group still returns the unexpected value but this seems to be an issue specifically with the radio group. Will create separate issues for that.
