### ISSUE TITLE
[form] Serialize form with name

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#399]
## Describe the bug

When I serialize a form, I expect it to respect the `name` attribute of the form since that is a fieldset in itself.

## To Reproduce

1. Go to https://lion-web-components.netlify.com/?path=/story/forms-form--form-submit-reset
2. Add a `name` attribute on the form with value `myForm`
3. Serialize the form

The form should look like:
```js
 <lion-form id="form" name="myForm" @submit="${submit}"
        ><form>
          <lion-fieldset label="Name" name="name">
            <lion-input name="firstName" label="First Name" .validators=${[new Required(), new MaxLength(15)]}>
            </lion-input>
            <lion-input name="lastName" label="Last Name" .validators=${[new Required(), new MaxLength(15)]}>
            </lion-input>
          </lion-fieldset>
          <button type="submit">Submit</button>
          <button type="button" @click=${() => document.querySelector('#form').resetGroup()}>
            Reset
          </button>
          <p>
            A reset button should never be offered to users. This button is only used here to demonstrate the
            functionality.
          </p>
        </form></lion-form
      >
```

The returned object is: 
```js
{
  name: { 
    firstName: '...', '
    lastName: '..' 
  }
}
```

## Expected behavior

The returned object is:

```js
{
  myForm: {
    name: { 
      firstName: '...', '
      lastName: '..' 
    }
  }
}
```

## Additional context

I can make a PR for this if this, but I need some guidance on what's the best place to implement this.

We could add a `serializeForm` method to the form, or respect the `name` attribute whenever you try to try to grab the `serializedValue`. This could be on `LionFieldset` too.

**Comment by gerjanvangeest** [comment]
If you get the `serializedValue` off an input or a fieldset, you wont get the name either. You don't want to pollute these.

So adding a `serializeForm` method sounds like a better solution to me.

**Comment by LarsDenBakker** [comment]
@gerjanvangeest shall I make a PR for `serializeForm` ?

I see you guys are planning on overhauling `modelValue`, what's the intended use case for `modelValue` and `serializedValue`? It seems like both may be useful in different cases, also when serializing a whole form.

**Comment by gerjanvangeest** [comment]
We are gonna work on the `serializedValue` next sprint. We will take this issue into consideration. 

Please be patient.

**Comment by tlouisse** [comment]
Please see for a proposal: https://github.com/ing-bank/lion/blob/72fcd3768f9f59bfc21cc9ba90b21ddcf600cf74/packages/fieldset/test/lion-fieldset.test.js#L804

When you call `serializeGroup({ includeSelf: true })` it includes itself in serilaization.

**Comment by LarsDenBakker** [comment]
I like `serializeForm` as a name, but this works too :)

**Comment by tlouisse** [comment]
Since we ended up in a situation where we found out `serializeGroup()` and `serializedValue` (serializedValue filters out disabled values now by default as well) were doing the same thing, we simplified the fieldset/sub form a bit by removing the `serializeGroup()`method.
We added a demo of how to wrap a `serialize` result in case of a multistep form.
