### ISSUE TITLE
[radio-group] serializedValue should be the same as checkedValue

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#400]
`LionRadioGroup` has a `serializedValue` which looks like: `{value: "brontosaurus", checked: true}`. The fact that it's checked is redundant information, and creates extra noise when you're using the serialized form information in other parts of the application.

There is a `checkedValue` which seems to be more appropriate to use here. I'd like to propose using this for the `serializedValue` of the checkbox group as well: https://github.com/ing-bank/lion/blob/master/packages/radio-group/src/LionRadioGroup.js#L28

**Comment by gerjanvangeest** [comment]
This is planned to be picked up in Q1 as part of a bigger refactoring of serialised values, as it impacts our internal web components.

**Comment by tlouisse** [comment]
@LarsDenBakker should work after https://github.com/ing-bank/lion/pull/583 is merged. Please let us know if there are any issues left
