### ISSUE TITLE
[checkbox-group] missing `serializedValue`

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#407]
`LionCheckboxGroup` is missing a `serializedValue`, while `LionRadioGroup` does have one. This causes serialization of a checkbox group to look like this:

```js
{
  'sports': {
    'sports[]': [
      { value: 'running', checked: true }, 
      { value: 'swimming', checked: true }
    ],
  }
}
```

While I expect this:

```js
{
  sports: ['running', 'swimming']
}
```

**Comment by gerjanvangeest** [comment]
This is planned to be picked up in Q1 as part of a bigger refactoring of serialised values, as it impacts our internal web components.

**Comment by tlouisse** [comment]
Will be fixed by this mr: https://github.com/ing-bank/lion/pull/583 (or might actually already have been fixed by Joren on master :))

**Comment by tlouisse** [comment]
@LarsDenBakker should work after https://github.com/ing-bank/lion/pull/583 is merged. Please let us know if there are any issues left
