### ISSUE TITLE
[localize] not possible to load namespace for a locale

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#41]
Localize has a facility to override the locale used for localizing. However, it is not possible to trigger loading a namespace for a specific locale because it is always retrieved from the `this`: https://github.com/ing-bank/lion/blob/master/packages/localize/src/LocalizeManager.js#L66

**Comment by LarsDenBakker** [comment]
This is not entirely correct, it is possible to pass a custom locale to `msg`: https://github.com/ing-bank/lion/blob/master/packages/localize/src/LocalizeManager.js#L83

The global locale should be the default, but there will be cases when a user needs to override this. For example a page might need to display a date or time in different timezones than the locale of the page.

In our specific use case we have a special page in our application where content managers can preview a piece of content they've prepared in multiple languages side by side before publishing it to production. For this we need to localize something in a different locale than the global locale.

**Comment by bashmish** [comment]
In other words we can't really use this feature of the msg without allowing to load data for it. Yep, seems valid to me now. I thought that our LocalizeMixin allows to load namespaces when a component has its own locale (we support this in multiple custom form elements), so we probably have to fix that properly as well. I think we'll start with writing some specs for it to see the entire flow.
