### ISSUE TITLE
Circular (Dev)Dependencies

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#414]
As many packages have devDependencies on each other it basically means that we release ALL packages even if only one package needs a release.

The reason for that is that lerna always updates the version of all the packages it manages.

This is bad because of
- messed up changelogs
- "useless" releases

Possible Solution:
- Put demos/tests which require other packages in a dedicated combination package
- Drop individual package releases => move to nightly releases?

**Comment by jorenbroekema** [comment]
For button and icon we can simply use a custom svg node and <button>. Would help already and makes the demo more focused on that which we wish to demo. 

Most demos dont actually hard-require other packages. 

Can you elaborate on what you mean with nightly releases? Release every lion package once per night if it has new commits?

**Comment by daKmoR** [comment]
> Can you elaborate on what you mean with nightly releases? Release every lion package once per night if it has new commits?

yes - e.g. we can do 10 commits during the day but only at 1:00 or so it will actually create a release

I think moving dependencies which are not absolutely vital would be a better solution... as it's a monorepo you can still work, demo, test everything but it considerably reduces the publish "noise"

**Comment by daKmoR** [comment]
we now did "Put demos/tests which require other packages in a dedicated combination package" and removed all not absolutely required devDependencies

should be way less releases now 💪
