### ISSUE TITLE
[lion-input-date] missing from form `serializedValue`

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#415]
lion-input-date field is missing from the serializedValue of a form.

`<lion-form id="form" @submit=${this.submitForm}>
    <form>
                    <lion-input-date
                        name="date"
                        label="Date"
                        .modelValue="${new Date()}">
                    </lion-input-date>
                    <button type="submit">Add</button>
                </form>
            </lion-form>`

-> form.serializedValue does not contain the date field

**Comment by gerjanvangeest** [comment]
I cannot reproduce this. I see nicely a `serializedValue` of: 

`date: Wed Jan 08 2020 14:26:21 GMT+0100 (Central European Standard Time)`

Please reopen if you still find this bug.
