### ISSUE TITLE
[lion-calendar] Prevent default behavior on keyboard interaction

### ISSUE THREAD

**Issue by gerjanvangeest** [ing-bank/lion#423]
## Describe the bug

When the calendar directly on a scrollable page is used, and the arrowUp, arrowDown, PageUp or PageDown are pressed to scroll through the calendar, the page also scrolls up and down. In these cases the default behaviour should be prevented.

**Comment by shawab1ceh** [comment]
Hello, im working on this. im a beginner, would you please tell me how do i test my changes ? thank you

**Comment by shawab1ceh** [comment]
Hello, im working on this. im a begginer. would you please tell me how do i test my changes ?

**Comment by shawab1ceh** [comment]
Hi, i can't reproduce the issue it seems its working to me as expected. what i am missing here ?

**Comment by ovidiu1** [comment]
https://github.com/ing-bank/lion/pull/440

**Comment by gerjanvangeest** [comment]
Thanks @ovidiu1 for the fix
