### ISSUE TITLE
Analyse TODOs in code

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#433]
**ajax**
- [ ] TODO: rename to 'config', because of conflict with options() request method on axios
- [ ] TODO: consider reenable after rename of options to config
  => because of this users can NOT use the http type options
  => useful yes/no if we may prefer the http package instead?

**general**
- [ ] TODO: improve coverage
  => we have certain code which is not tested (all should be above 93%)
  => needs multi-browsers to test the code we write specifically for those browsers
  => IE11 should be enough
  Statements   : 91.45% ( 4641/5075 )
  Branches     : 81.58% ( 1802/2209 ) => ~400 untested conditions
  Functions    : 93.79% ( 1420/1514 ) => ~100 untested functions
  Lines        : 91.67% ( 4512/4922 )
- [ ] TODO: find best naming convention: https://en.bem.info/methodology/naming-convention/ (react style would align better with JSS)
  => style documentation
- [ ] 3x TODO: this method has to be removed when EventTarget polyfill is available on IE11
  => do a proper solution for EventTarget (write polyfill for IE11???)

**calendar**
- [x] TODO: remove as much logic as possible from this template and move to processor
  => move logic out of templates to improve maintainability
- [x] TODO: add more tests, e.g. for: weekdays, weekday abbreviations, month names
  => test translations everywhere

**field**
- [ ] TODO: - [`FormControlMixin`]
- [ ] TODO: - [`LionField`]
- [ ] TODO: - [`FocusMixin`]
  => missing documentation
- [ ] TODO: In a breaking refactor of the Validation System, this behavior can be corrected. (Ideally, modelValue should be undefined for empty strings.)
  => we didn't do it yet as it's a breaking - MUST have
- [ ] TODO: change ev.target to original registering element
  => PortalMixin requires CustomEvent - would be nice to use just Event without custom data  
- [ ] TODO: Add submitted prop to InteractionStateMixin
- [ ] TODO: add pointerEvents test for disabled
- [ ] TODO: put this test on FormControlMixin test once there

**fielset**
- [ ] TODO: add submitted prop to InteractionStateMixin

**input-amount**
- [ ] TODO: input and change events both trigger parsing therefore we need to handle the second parse
  => see issue #404 
- [ ] TODO: Document that maximumFractionDigits >= minimumFractionDigits else a RangeError is thrown by Intl

**Datepicker**
- [ ] TODO: add performance optimization to only render the calendar if needed
- [ ] TODO: refactor CalendarObject to this approach (only methods when arguments are needed)
  => improve maintainability 
- [ ] TODO: should this be part of globalOverlayController as option? (activates full screen mode on mobile screens)
- [ ] TODO: fix the Overlay system, so that the backdrop/body cannot be focused
- [ ] TODO: consider making this (delegation to interactive child nodes) generic functionality (Relies on delegation of disabled property to invoker)

**localize**
- [ ] TODO: consider using a database with information for the `firstDayOfWeek`?
- [ ] TODO: formatNumber for en-AU is broken for currency sign
  => see https://github.com/ing-bank/lion/issues/432

---------- still open to look at the TODOs of -----
- packages/overlays
- packages/select-rich
- packages/switch
- packages/validate

**Comment by ovidiu1** [comment]
#499 - calendar

**Comment by daKmoR** [comment]
we use a TODO Link now
https://www.tickgit.com/browse?repo=github.com/ing-bank/lion
