### ISSUE TITLE
[lion-radio-group] setting serializedValue in a new form fails

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#435]
`LionRadioGroup` serialized value is an object: `{ value: 'something', checked: true }`. 

To select fields, object comparison is used at: https://github.com/ing-bank/lion/blob/master/packages/radio-group/src/LionRadioGroup.js#L43 this works within the same instance of the form, but if you recreate a completely new form and try to set the `serializedValue` it fails because the objects are no longer the same. 

Instead it should select checkboxes using the `value` property, or when/if https://github.com/ing-bank/lion/pull/401 is merged it will always use the value anyway.

**Comment by tlouisse** [comment]
@LarsDenBakker should work after https://github.com/ing-bank/lion/pull/583 is merged. Please let us know if there are any issues left
