### ISSUE TITLE
Snapshot file won't update

### ISSUE THREAD

**Issue by ovidiu1** [ing-bank/lion#466]
## Describe the bug

Snapshot file won't update with new changes from the DOM tree.

## To Reproduce

Add a new element (or  new property to an element) in the DOM and  Run ` npm run test:update-snapshots ` and check in the snapshot file.

## Expected behavior

Update snapshot file with the new changes made in the DOM tree.

## Screenshots

![Annotation 2019-12-30 234559](https://user-images.githubusercontent.com/9486182/71601974-98480b80-2b5e-11ea-9276-67adcd37db28.png)
![Annotation 2019-12-30 235458](https://user-images.githubusercontent.com/9486182/71602292-60da5e80-2b60-11ea-87a6-6512acd05fb6.png)

## Additional context

I think should be something with the karma.config regarding to warning.
`31 12 2019 00:01:16.891:WARN [filelist]: Pattern "D:/dev/lab/lion/__snapshots__/**/*.md" does not match any file.`

**Comment by jorenbroekema** [comment]
I'm not sure if we're using karma snapshots currently, so the warning seems appropriate.

I get the feeling that the snapshot in calendar is our internal snapshot but they are maybe not the same thing?

@daKmoR  you're our testing guru, can you maybe explain :P?

**Comment by ovidiu1** [comment]
They are the same think. I think karma snapshot should also be in lion, this will make contributor life more easy.

**Comment by ovidiu1** [comment]
I will make a PR for this.

**Comment by jorenbroekema** [comment]
Not sure if I understand the problem, or the solution you're proposing, but I guess I will see it in your PR 🤗

**Comment by daKmoR** [comment]
we don't have an automated snapshot system and most likely will not have it... this is a manually maintained file... maybe snapshot is a bad name here 😅

it is in a separate file so we can get code highlighting - as we have a dedicated `html` template literal to convert to plain string

closing this as we are not going to automate it - we would however accept a pull request to rename the file/folder
