### ISSUE TITLE
model-value-changed lacks consistency

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#505]
## Describe the bug

`model-value-changed` event is fired when the modelValue of a field changes. There are a few problems. It has `composed: true` which is pretty overkill, since we don't have a `render` method with a template for most of our fields. They usually spawn native elements in the LightDOM, and I don't think we usually recommend having shadow boundaries if you extend our (simple) fields.

Another issue is the bubbling. Usually this is useful, because if a field changes model-value, the parent fieldsets all change model-value as well, so to make it bubble makes a lot of sense.

However, there's a few fields where we get a weird number of `model-value-changed` when listening to it on the wrapping form:

- If you have a `checkbox-group` or `radio-group`, you do not get any `model-value-changed` on initialization. For all other fields in the umbrella form, you do get it.
- If you have a `select-rich`, you get `model-value-changed` multiple times. I tested it with 3 choices, and got it 3 times, then another 2 times, on init. Probably has to do with the options  nodes being moved?
- In both `radio-group` and `select-rich`, if an option is selected, and you then change the selection, you get a `model-value-changed` from both the option that was checked, and from the option that was unchecked as a result (because it's only single-select). 

Reproduce it by listening to `model-value-changed` on a form that has radio-group, checkbox-group, rich-select in it.

## Expected behavior

- A single model-value-changed event to reach the form when we change the selection in a field that has options.
- Either 1 model-value-changed event on init for all fields, or none. Right now it is 0, 1 or .. 5
- model-value-changed to not go through shadow boundaries

**Comment by gerjanvangeest** [comment]
Fixed in: https://github.com/ing-bank/lion/pull/647
