### ISSUE TITLE
[storybook] Font usage not aligned

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#524]
## Describe the bug

There are multiple fonts in the documentation. Even in a single code block, there are 2 different monospace fonts used. The colored text font differs from the black text font.
Demos also have different fonts. The guiding text has a different font than input labels in the components, which also differs from the text (you type) inside the inputs.

It would be great if this could be reduced to maybe 2 fonts? One monospace for code blocks. And another for docs and components.

This would improve consistency and improves the readability of our documentation.

**Comment by yashagarwal9** [comment]
Hi @erikkroes 
I would like to work on this issue. Can you please guide me with this?

**Comment by gerjanvangeest** [comment]
Hi @yashagarwal9, 

Erik is sadly already for some time ill at home, and i'm not fully sure what he wanted to change.
At the moment we have 4 fonts in use:

- Nunito Sant (storybook default & body test)
- Courier (monospace (code snippets)
- Times (demos)
- SF NS text (e.g. buttons & input fields)

The last 2 ones are native default fonts, which fit our "vanilla" styling.

If you have any suggestions to make our demos better or more consistent, please help us. Be aware that we will move to [mdjs](https://github.com/ing-bank/lion/pull/665) in the near future. I don't think it will impact the look and feel, but if you are working on a MR, then that branch should be your starting point.

**Comment by yashagarwal9** [comment]
Hi @gerjanvangeest 
The branch has some issue. I'll branch from it and make the required changes. After going through the code I found that for most of the packages the fonts are not defined explicitly. Either they are using the default fonts or the ones defined in SbActionLogger. What do you think about this?

**Comment by gerjanvangeest** [comment]
The SbActionLogger, uses the same font definition as [storybook](https://github.com/storybookjs/storybook/blob/next/lib/theming/src/base.ts), we could just import that one, to be sure we stay aligned.

I'm still not sure this upgrade is needed, the default fonts are fine with me.

**Comment by erikkroes** [comment]
Docs had quite some changes. I can imagine the previously mentioned situation doesn't occur anymore.

**Comment by daKmoR** [comment]
I don't think that is an issue anymore - feel free to reopen or create a new issue if still valide 🤗
