### ISSUE TITLE
[button] space bar scrolls the page

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#525]
## Describe the bug

When using the spacebar to click a `lion-button`, the page scrolls down. When using spacebar on a native `button` the page does not scroll down. This happens because in `lion-button` we're not interacting with the native button.

## To Reproduce

- Go the storybook
- Use spacebar on a button
- See the page scrolled down

## Expected behavior

The page was not scrolled down

## Additional context

I'm not sure if it's possible to cancel this browser behavior. 

This could be solved by making the native button inside `lion-button` the interactable node, and not the `lion-button` node itself. The main reason I think this wasn't done is because of the automagic 40px click area. Perhaps it's possible to solve this in a different way, like an absolute positioned element or something using `::before` or `::after`. Or let go of this requirement. Given the amount of cross-browser bugs with the button setup, this might be a better approach. It will avoid a lot of headaches in the future.

**Comment by erikkroes** [comment]
Scrolling is on keydown. Button activation is on key up. Maybe we can preventdefault on keydown?
