### ISSUE TITLE
Fix: Storybook doesn't work in IE 11

### ISSUE THREAD

**Issue by thatianamg** [ing-bank/lion#530]
## Describe the bug
When I access https://lion-web-components.netlify.com/?path=/story/intro-lion-web-components--page in IE 11 it doesn't load. 

## To Reproduce
I open IE 11 (version 11.1246.17134.0) and access storybook (link above)
Page keeps loading and never finishes

**Comment by ovidiu1** [comment]
[Live Storybook](https://lion-web-components.netlify.com/?path=/story/intro-lion-web-components--page), works fine for me. 
![Annotation 2020-02-08 152914](https://user-images.githubusercontent.com/9486182/74086160-f387ea80-4a88-11ea-936a-ffa4d7bdccbd.png)
Also localhost. 
![local](https://user-images.githubusercontent.com/9486182/74086384-026f9c80-4a8b-11ea-9b6c-87bc7ad9c9e3.png)
Can you check again?

**Comment by AymenBenAmor** [comment]
I check on IE as well and it's working fine. (see screenshot)
<img width="1676" alt="Screen Shot 2020-03-12 at 14 30 00" src="https://user-images.githubusercontent.com/2727439/76537666-67e5ed00-647e-11ea-9497-ff6aae15631a.png">

**Comment by AymenBenAmor** [comment]
I'm closing this issue as it works fine on IE as you can see on the screenshot above
