### ISSUE TITLE
Possibility to know when to show a focus ring

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#535]
## Describe the bug

In the wild many users disable the outline because it is "ugly" and effects "mouse users".

By using something like [:focus-visible](https://github.com/WICG/focus-visible) this can be prevented and we can explicitly only disable it for mouse users.

As this feature is currently only available within Firefox probably a good solution would be to have a `FocusVisibleMixin` which set's an appropriate attribute. I don't think we should relay on a polyfill for that.

Usage:
```css
/* hide outline for mouse users */
:host(:focus:not([focus-visible])) {
  outline: 0;
}
```

Related Video https://www.youtube.com/watch?v=ilj2P5-5CjI

## To Reproduce

Prominently shown when navigating the Tabs.
But basically every Focusable element is effected and extending users should have a straight forward way of disabling outlines for mouse users if they want.

**Comment by LarsDenBakker** [comment]
Ive written a small FocusVisibleMixin internally, based on https://github.com/WICG/focus-visible you could look at it for inspiration

**Comment by gerjanvangeest** [comment]
Hi,

We are closing this issue because that's the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to vote and show interest. It will be reopened when this feature gets picked up.

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by erikkroes** [comment]
So what's the actual issue here? And why would this be part of Lion? It sounds like styling to me.

**Comment by daKmoR** [comment]
jup it's styling but currently, browsers do not offer a way of styling only for mouse users... so that's why it needs a custom solution.

Why it would be needed? to give those extending the lion component to the possibility to style in an accessible way. (and not just disable the outline always because their Design System says no outline for mouse users)

**Comment by daKmoR** [comment]
let's do this as a progressive enhancement as it's going to be supported in the next version of chrome besides firefox.

So superseded by https://github.com/ing-bank/lion/issues/917
