### ISSUE TITLE
(calendar) test fails on master branch

### ISSUE THREAD

**Issue by panczer** [ing-bank/lion#54]
One of the test for lion-calendar is failing because it depends on actual day but is compared to constant day.

Test name: `is on day closest to today, if today (and surrounding dates) is/are disabled`

AssertionError: expected 21 to equal 17

**Comment by tmsns** [comment]
Apparently, the clock hasn't been faked for that test. So, the real day is used.

Can be fixed by using:
```javascript
const clock = sinon.useFakeTimers({ now: new Date('2000/12/15').getTime() });
```
And restoring the clock afterwards.

**Comment by tlouisse** [comment]
Good catch 👍  You could make a pr if you want or else our hero could pick it up

**Comment by bashmish** [comment]
I'll fix it.
