### ISSUE TITLE
[validate] getMessage config value should throw error if value not of type 'function'

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#544]
## Describe the bug

When passing a custom getMessage config value to a validator constructor, he should throw an error if it is not of type 'function'.

## To Reproduce

Pass for example a string to the validator's constructor:
`<lion-input .validators=${[new Required({},{ getMessage: 'test' })]}></lion-input>`

Expected: an error is thrown saying the value of getMessage should be of type function.

Actual behavior: he ignores the configuration value.

**Comment by daKmoR** [comment]
solved via https://github.com/ing-bank/lion/pull/545
