### ISSUE TITLE
[button] executes regexp on each render

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#546]
## Describe the bug

`LionButton` executes a regexp on the user agent string on each render: https://github.com/ing-bank/lion/blob/master/packages/button/src/LionButton.js#L30 this is unnecessary work, executing regexp can be expensive

This should just be constant on top of the file.

**Comment by daKmoR** [comment]
I am reserving this issue 🤗

**Comment by daKmoR** [comment]
solved via https://github.com/ing-bank/lion/pull/550
