### ISSUE TITLE
[form] how to check if form changed after prefill

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#547]
## Describe the bug

When prefilling a form, there isn't any way to know whether the form has changed after prefilling. The form dirty value is true, while the prefilled value is false.

## To Reproduce

See this reproduction: https://webcomponents.dev/edit/HgFCAaNA1jyOhkpWYiei

In `firstUpdated` I'm logging `dirty` and `prefilled`

## Additional context

Is there another value that can be used for this?

**Comment by daKmoR** [comment]
that prefilled value looks definitely wrong 🙈 

something strange is going on there... in the firstUpdated the value even of the input is wrong (e.g. it's prefilled false)
whereas if I select `<lion-input name="firstName">` in the developer tools and do `$0.prefilled` it correctly says `true`
🙈 

the idea is that if any of the form elements are prefilled that then the form/fieldset becomes prefilled... but it seems the fieldset is not prefilled... 

definitely something wrong here... will need to investigate 😅

**Comment by tlouisse** [comment]
@LarsDenBakker There is an initInteractionState() that runs on connectedCallback. 
This runs too early, since it only has the right values on `registrationReady`.

I have a fix fo this in a branch.
