### ISSUE TITLE
[validate] dynamically adding/removing validators does not reset validation results

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#556]
A property is attached to the lion input's validators property.

`this.validators = [new Required()];`

`<lion-input .validators=${this.validators}></lion-input>`

`this.validators = [];`
When a validator is removed from "this.validators" array, the results of the previous validation should be reset.
Right now the validation is removed, but the result of the validation is kept.

**Comment by daKmoR** [comment]
fixed by https://github.com/ing-bank/lion/pull/565
