### ISSUE TITLE
[validate] disabled input elements should not be validated

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#557]
When an input element is disabled, the validation should not run for this input element.

`<lion-input .validators=${new Required()} disabled></lion-input`

--> Required validation should not run for this disabled field.

**Comment by daKmoR** [comment]
there is even a spec for that

> Constraint validation: If an element is disabled, it is barred from constraint validation.

https://www.w3.org/TR/html50/forms.html#attr-fe-disabled

**Comment by AymenBenAmor** [comment]
I created a pull request for this issue : https://github.com/ing-bank/lion/pull/586

**Comment by daKmoR** [comment]
fixed via #586
