### ISSUE TITLE
[select-rich] does not work on IE11

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#560]
## Describe the bug

`lion-select-rich` does not work on IE11. It throws an error: `Failed to construct lion-select-invoker`: The constructed element must not have any attributes.

## To Reproduce

1. Go to https://lion-web-components.netlify.com/?path=/story/forms-select-rich--default-story on IE11

## Expected behavior

The selector works

**Comment by daKmoR** [comment]
I guess the reason for it is https://github.com/ing-bank/lion/issues/533

**Comment by daKmoR** [comment]
as a solution to #533 was merged - this seems to be solved as well - please reopen if the issue persists
