### ISSUE TITLE
Q&A on Lion release

### ISSUE THREAD

**Issue by brucou** [ing-bank/lion#570]
@daKmoR Hi Thomas. I followed with interest the release post for Lion, and would like to do and publish on Infoq a Q&A session with you if you would have the time. A previous Q&A with Gatsby's Kyle Mathews we published you might find interesting: https://www.infoq.com/news/2017/07/gatsby-kyle-mathews-interview/. I believe a Lion's Q&A would be of great value to our readers. Congratulations for Lion's beta release!

**Comment by daKmoR** [comment]
@brucou sounds good - can you write me a message on twitter with more details?
https://twitter.com/daKmoR

**Comment by brucou** [comment]
Thomas, thanks! Can you write me instead here: bcouriol@sparks.network, and I write you all about it? It will be more practical by far.
