### ISSUE TITLE
[Storybook] Invalid path to Localize System Overview

### ISSUE THREAD

**Issue by israelfloresdga** [ing-bank/lion#575]
## Describe the bug

 Invalid path to **Localize System Overview** from **Localize / Translate Text** story

## To Reproduce

1. Go to [Localize / Translate Text](https://lion-web-components.netlify.com/?path=/docs/localize-translate-text--function-story)
2. Click on link [Localize System Overview](https://lion-web-components.netlify.com/iframe.html?path=/docs/localize-system-overview--page)
3. See error `Invalid path '/docs/localize-system-overview--page', must start with '/story/'`

## Expected behavior

Being able to see the information at `https://lion-web-components.netlify.com/?path=/docs/localize-system-overview--page`

## Screenshots

![image](https://user-images.githubusercontent.com/12726076/74450838-55a76d80-4e44-11ea-976a-ca0249c0983d.png)

**Comment by daKmoR** [comment]
hey,

I assume you used "open in a new tab" unfortunately it seems storybook currently requires you to click on the link within a storybook... e.g .you can not open it in a new tab 🤔 

could you maybe create an issue on [storybook](https://github.com/storybookjs/storybook) itself?

I don't think we can solve this on our side 🙈
