### ISSUE TITLE
Consistent naming convention: changedProps vs changedProperties

### ISSUE THREAD

**Issue by amielucha** [ing-bank/lion#580]
It would be beneficial for consistency and ease of comparison between components' code, to refactor the update methods to use the same variable naming convention for properties.

- `changedProps` is being used in 7 files
- `changedProperties` is being used in 11 files

Is there a strong preference towards one or the other?

**Comment by daKmoR** [comment]
`changedProperties` seems like a more descriptive name 👍

**Comment by jorenbroekema** [comment]
We also use `c` in some places I think so you may want to search for `update(c` and maybe even , for me both proposed names are fine. Also maybe check `firstUpdated(c` , same thing in that lifecycle method
