### ISSUE TITLE
Enhance field mdx documentation 

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#594]
Currently, we miss elaborate information on why accessibility works the way it works inside the form system. Address questions like:
- why do we put controls in light dom?
- why is it not allowed to wrap form controls inside shadow boundaries?
- how is all of this forwards compatible with upcoming a11y specs: https://wicg.github.io/aom/explainer.html?

Also: 
- Cleanup field md documentation (put everything in mdx)
- Add docs for FocusMixin, FormControlMixin (would mainly be tyhe a11y part described above, also dom structure etc and fact that it is the core mixin everything inside the system inherits from)
and LionField

**Comment by jorenbroekema** [comment]
Closing as enhancements with votes needed. Our workflow with enhancements is that we close them and have people vote on them, then we sort our enhancements by most votes to see which ones should be prioritized: https://github.com/ing-bank/lion/issues?q=is%3Aissue+is%3Aclosed+label%3Aenhancement+sort%3Areactions-%2B1-desc
