### ISSUE TITLE
[validate] when using a mangler the default error message becomes useless

### ISSUE THREAD

**Issue by daKmoR** [ing-bank/lion#597]
## Describe the bug

The default error message is using the `static name` of a class however it class names are mangled to optimize performance the error message becomes gibberish like.

```
Please configure an error message for "Ot" by overriding "static async getMessage()"
```
while it is a "Required" Validator.

## To Reproduce

1. Open demo [Form Features Overview](https://lion-web-components.netlify.com/?path=/story/forms-features-overview--example)
2. Fill in something into for example the textarea
3. The gibberish error message will appear

## Additional context

The reason for that is that we use `this.name` in a static function... which can not access the `this.name` in the constructor

```js
export class Validator {
  constructor(param, config) {
    fakeExtendsEventTarget(this);

    this.name = '';
    // ...
  }
  static async getMessage(/* data */) {
    return `Please configure an error message for "${this.name}" by overriding "static async getMessage()"`;
  }
```
https://github.com/ing-bank/lion/blob/master/packages/validate/src/Validator.js#L82

**Possible solution**:

Use `static get validatorName() { return 'Required'; }` to set the name... e.g. to make it available statically as well.

A validator probably should never change it's name... hence static should work perfectly...

**Comment by tlouisse** [comment]
Yeah, makes sense. Is indeed good  to be unable to change the name of an instance

**Comment by daKmoR** [comment]
So let's make these "static" settings like name, async actually static...

```js
// from
constructor(param, config) {
  this.name = 'Required';
  this.async = true;
}

// to
static get validatorName() { return 'Required'; }
static get async() { return true; }
```

**Comment by daKmoR** [comment]
fixed via https://github.com/ing-bank/lion/pull/600
