### ISSUE TITLE
Question regarding cross browser compatibility (IE11)

### ISSUE THREAD

**Issue by christianboyle** [ing-bank/lion#604]
Lion is a fantastic offering, really excited to see such a refined library being open-sourced!

I'm not seeing any mention of browser compatibility in the [Medium article](https://medium.com/ing-blog/ing-open-sources-lion-a-library-for-performant-accessible-flexible-web-components-22ad165b1d3d) (aside from the note about native support for Web Components in modern browsers), but I do see [issues reported in IE11 being resolved](https://github.com/ing-bank/lion/issues?q=is%3Aissue+IE11+is%3Aclosed). Is it safe to assume IE11 support is being targeted?

**Comment by LarsDenBakker** [comment]
All of lion is being used in production on IE11 on many of ING's own website/apps :)

**Comment by christianboyle** [comment]
Wonderful, thank you!

**Comment by LarsDenBakker** [comment]
@daKmoR good to mention browser support in the readme :)
