### ISSUE TITLE
lion-input-datepicker is broken

### ISSUE THREAD

**Issue by darkkinght07** [ing-bank/lion#616]
I get Uncaught TypeError: Cannot read property 'hide' of undefined. My first guess is that the issue is in OverlayMixin.js.
To reproduce the issue: 
html`...
<lion-input-datepicker label="test"></lion-input-datepicker>
..`

package.json
"@lion/input-datepicker": "^0.8.1", (latest)
"@lion/input": "^0.5.14", (latest)

Can someone have a look?

Thanks.

**Comment by jorenbroekema** [comment]
I could not reproduce this on the latest:

```js
import { html, LitElement } from '@lion/core';
import '@lion/input-datepicker/lion-input-datepicker.js';

class MyDemo extends LitElement {
  render() {
    return html`
      <lion-input-datepicker label="Test"></lion-input-datepicker>
    `;
  }
}
customElements.define('my-demo', MyDemo);
```

```json
{
  "name": "lion-datepicker-bug",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "es-dev-server --watch --open --node-resolve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@lion/core": "^0.4.4",
    "@lion/input-datepicker": "^0.9.1"
  },
  "devDependencies": {
    "es-dev-server": "^1.42.0"
  }
}
```

Can you verify if it's still broken, and if so, how you are producing the error?
