### ISSUE TITLE
Not able to run or build the project

### ISSUE THREAD

**Issue by rajkeshwar** [ing-bank/lion#62]
Not able to run the project after `git clone` and `npm install`. `npm run start` failing for many dependencies. Tried building by running `npm run storybook:build` that too failing.

Please see the screenshot for `npm run start`

<img width="1206" alt="Screenshot 2019-05-22 at 10 46 19 PM" src="https://user-images.githubusercontent.com/5517744/58208384-e94c7300-7ce4-11e9-880c-bc186afbb2f1.png">

For `npm run storybook:build`

<img width="1086" alt="Screenshot 2019-05-22 at 10 53 39 PM" src="https://user-images.githubusercontent.com/5517744/58208417-f79a8f00-7ce4-11e9-826a-f12427b56731.png">

Node :v8.9.4
npm : 6.7.0

**Comment by daKmoR** [comment]
We are using `yarn workspaces` so you will need to install via `yarn` 🤗 

We sort of have it in our [contribution guide](https://github.com/ing-bank/lion/blob/master/CONTRIBUTING.md#existing-components-we-love-pull-requests-)... apparently, it's not obvious enough 🙈 

Where would you expect such info?

**Comment by rajkeshwar** [comment]
I also tried `yarn install` but no luck. Is there any higher version of `node` and `npm` is needed?

**Comment by bashmish** [comment]
@rajkeshwar I've been using these version since we switched to a lerna monorepo and yarn workspaces:

```
→ node --version
v10.9.0
→ yarn --version
1.13.0
```

Before using yarn I would recommend you to remove all node_modules in your local copy and do a fresh install with yarn, maybe you somehow got nested node_modules which yarn just does not clean up.

**Comment by bashmish** [comment]
@rajkeshwar did you manage to run the start script?

**Comment by bashmish** [comment]
Please try yarn on a clean clone of `ing-bank/lion`. Feel free to reopen if that does not help.
