### ISSUE TITLE
[lion-input] State attribute filled only update in onblur event

### ISSUE THREAD

**Issue by carlosesteban55** [ing-bank/lion#645]
## Describe the bug

lion input don´t update the state "filled" attribute when the user is typing . Only when user throws onblur event.

https://github.com/ing-bank/lion/blob/master/packages/field/src/LionField.js#L187 this is the line that toggles the filled attribute and onValueChanged gets triggered by the value setter which gets triggered by FormatMixin.. so in FormatMixin may lie the root cause

when the user is typing (focused inside the input), the formatted value is not reflected back to the user yet, so the value setter isn't called, as a consequence, the filled attribute is only toggled when the formatted value is reflected back to the user.

> _reflectBackFormattedValueToUser() {
>   if (this._reflectBackOn()) {
>     // Text 'undefined' should not end up in <input>
>     this.value = typeof this.formattedValue !== 'undefined' ? this.formattedValue : '';
>   }
> }
> ​
> _reflectBackOn() {
>   return !this.__isHandlingUserInput;
> }

## To Reproduce

1. type on the lion input. If you have the filled attribute active then delete all characters and see that filled attribute don´t update

2. If the input is empty, type some characters and see that not update filled attribute.

## Expected behavior

Filled attribute updates during user types.

## Screenshots

![image](https://user-images.githubusercontent.com/49064780/76963964-2cd23680-6922-11ea-80aa-1f5ef2021284.png)

**Comment by jorenbroekema** [comment]
Yeah can confirm, flow is indeed:
- modelValue is formatted (only when user is not handling the input, e.g. on blur)
- formatted value changed and therefore has to be reflected back to the user
- value setter is invoked by setting `this.value`
- value setter in LionField calls the method that toggles the `filled` attribute

I have opened a PR to change this behavior to be dependent on the modelValue (and onModelValueChanged event), this will ensure `filled` is toggled also when the model value is non-empty during user input, but hasn't been reflected back as a formatted version to the user.

**Comment by jorenbroekema** [comment]
https://github.com/ing-bank/lion/pull/646 fixed here
