### ISSUE TITLE
New Stackblitz (Turbo-resolver) projects broken

### ISSUE THREAD

**Issue by tmsns** [ing-bank/lion#65]
Using `@lion/core` in new projects on Stackblitz is not working anymore. Here is a fork of a project posted 8 days ago in one of the other issues: https://stackblitz.com/edit/lion-form-9r5wtq The only thing I changed is reinstalling the dependencies. Now, the app doesn't seem to be running anymore.

When looking in the sources of the example we see files of 2 versions of `lit-html` being loaded (1.0.0 and 1.1.0):

![image](https://user-images.githubusercontent.com/17364880/58287992-b375c000-7db2-11e9-88c7-95915bbcf72d.png)

After some investigation this is happening because of 3 separate things coming together:
- Stackblitz's module resolver (Turbo) is fetching the dependencies for every module on the fly from unpkg.com. To know which version to download, Turbo will only look at the module's own package.json. (npm and yarn will look at all dependencies and subdependencies)
- `@lion/core` is depending on a fixed version of `lit-html`: `1.0.0`
- `lit-element 2.1.0` is depending on `lit-html: "^1.0.0"`, which is resolving to `1.1.0` [since Tuesday (21/5)](https://github.com/Polymer/lit-html/blob/master/CHANGELOG.md#110---2019-05-20), as a new version has been released.

All of this affects the internal wiring of `LitElement`, preventing the `TemplateResult` to be rendered in the `renderRoot`.

As lion is a library I think the best solution here is to have `@lion/core` be dependent on ranges of `lit-element` and `lit-html` instead of fixed versions.

**Comment by daKmoR** [comment]
I opened an issue on lit-element https://github.com/Polymer/lit-element/issues/682

we want to pin the version of `lit-element` as we had problems in the past with fix/feature versions breaking our code 🙈 but yeah probably good to at least allowing patch releases...

I think depending on a range for `lit-html` should fix it for now 🤗 

made a PR for it 👍

**Comment by tmsns** [comment]
It's funny to see that we were working on the same issue in parallel.. 😁 

And it's again the eternal debate on using ranges or not. 😊 Even if everyone would stick to the rules of semver, breaking issues can still be introduced in minor or patch releases. And of course, you'll get them for free when using ranges... but, if everything goes right, you should also get the fixes for free.. 🙈 

Anyways, thanks for the PR! 👍
