### ISSUE TITLE
security issue in range slider

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#686]
While browsing I noticed a small security issue, the range slider sets innerHTML using a value set by a user: https://github.com/ing-bank/lion/blob/master/packages/input-range/src/LionInputRange.js#L121

I think you can use textContent or cssText or something like that instead, to avoid script injection.

**Comment by tlouisse** [comment]
Thanks for noticing 👍 `textContent` seems to work fine indeed.
