### ISSUE TITLE
clearGroup for form

### ISSUE THREAD

**Issue by realfighter92** [ing-bank/lion#706]
Hi,

We have resetGroup to reset form values to initial state and  we have clear function to clear field value.But cant see any option to clear form ,like set all fields values to blank instead of initial value, something like clearGroup.

**Comment by gerjanvangeest** [comment]
Hi, sounds like a good idea. Do you feel like contributing it?

**Comment by realfighter92** [comment]
Yeah , sure...Do we have to update the storybook with clearGroup same like reset for the Formt.

**Comment by gerjanvangeest** [comment]
Yes, it's a good practice to show all features in Storybook.
