### ISSUE TITLE
[storybook]: Radio group validation message is not matched with actual validation

### ISSUE THREAD

**Issue by SuryaSJ** [ing-bank/lion#709]
## Describe the bug

In the Radio Group stories for validating single option, the message is not matched with validation it meant to be. This may lead to misconception.
The message says "You need to select brontosaurus", when I select brontosaurus. But no error on selecting other two options.

## To Fix

class IsBrontosaurus extends Validator {
  constructor() {
    super();
    this.name = 'IsBrontosaurus';
  }
  execute(value) {
    return  `value !== 'brontosaurus';`
  }
  static async getMessage() {
    return 'You need to select "brontosaurus"';
  }
}
const validate = () => {
  const radioGroup = document.querySelector('#dinosGroupTwo');
  radioGroup.submitted = !radioGroup.submitted;
};

**Comment by jorenbroekema** [comment]
Huh, I can't find this demo, can you share the link to it @SuryaSJ

**Comment by SuryaSJ** [comment]
Hi,
Here is the link for you https://lion-web-components.netlify.app/?path=/docs/forms-radio-group--validate-item

**Comment by gerjanvangeest** [comment]
I see this is fixed in latest version
