### ISSUE TITLE
[icon] icon loading system

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#71]
I proposed this system already internally, moving it to github now.

The current icon system is a potential footgun for performance. I'd like to propose a change which improves performance and maintains a good developer experience.

In the current system the easiest way to use icons is by importing them synchronously. This method is also the default promoted/documented method. Sync imports will include the icons with the initial bundle of the application which for large applications can really add up to quite an amount.

Applications often have areas which are dynamic where it is not known beforehand what kind of content and icons will be shown. For example a user might be able to choose a profile picture from a set of icons, or the application might display a list of items where each item might have an icon based on some data from an API. In these case the list of possible icons is basically 'everything', resulting in all icons having to be imported and increasing the bundle size.

It is possible to use dynamic imports to load the icons, but this requires quite some extra boilerplate and specific knowledge. Also different teams might work on different areas of the application, and end up rewriting the same dynamic loading logic for the same icons.

Because lazy loading is not the default promoted and documented method most people will end up with the synchronous icon system anyway and (hopefully) only later find out that they need to refactor this to improve performance.

I propose a system similar to the localization system, and similar to the way [iron-icon](https://github.com/PolymerElements/iron-icon) works. Developers use the icon element and specify a specific `icon-id`:
```html
<lion-icon icon-id="lion:space:meteor"></lion-icon>
```

The icon id is made up of a specific set of parts: `<namespace>:<collection>:<icon>`. For each namespace a loader is defined which then lazily loads the icons on demand. For example:
```javascript
icons.addIconResolver('lion', async (collection, iconName) => {
  switch (collection) {
    case 'bugs':
      return (await import('./icons/bugs-collection.js'))[iconName];
    case 'space':
      return (await import('./icons/space-collection.js'))[iconName];
    default:
      throw new Error(`Unknown collection: ${collection}`);
  }
});
```

In the example above a space icon is requested, so the space collection is imported and the meteor icon is returned. When another space icon is requested, the space collection was already imported so it won't be loaded again. It's better to bundle a set of icons together and import it, instead of doing separate imports for each icon.

Benefits:
- Icons are always lazy loaded and never end up in the main bundle.
- Icons are always loaded on demand
  - For example if you display icons in a menu, the menu isn't rendered until it is opened so the icons are not imported until the menu is opened as well.
- There isn't any special syntax to learn, so people get performance for free.
- Icon ids can be defined from any arbitrary source, so you can pass icon names from an API or a CMS system directly to the icon component.
- Icons behave just like images. 
- Icons can potentially be loaded only when in view using `IntersectionObserver`

I implemented this already in my own application, with an extension on `lion-icon`, and it works very well for us.

**Comment by bashmish** [comment]
> I propose a system similar to the localization system, and similar to the way iron-icon works.

I wanted to propose the opposite to the localisation system with a reference to the icons implementation.

> It is possible to use dynamic imports to load the icons, but this requires quite some extra boilerplate and specific knowledge.

While you need to write a little bit more code, it becomes more straightforward what exactly you are loading and from where. Boilerplate is not a problem up until it does not contain any logic and does not break encapsulation, and in this case I believe it does not. Also, it is a super small boilerplate, basically just one operator.

> Also different teams might work on different areas of the application, and end up rewriting the same dynamic loading logic for the same icons.

I miss the point here. I see that the more teams work on the same app, the more problems you create with global icon namespaces, because then isolated teams will have to reuse the same bundle with same names by creating unnecessary coupling. While with dynamic imports you just use paths as unique keys and they get automatically deduped by the browser/bundler for you, no matter how many people import from those paths from different parts of the app code. Can you elaborate with specific examples where things get out of control?

**Comment by bashmish** [comment]
My concern is that we will just create more ways to load the same thing, while the DX improvement is very subjective. Because of more ways to load icons the average DX will become worse since you give people more options to choose from without a particular way to select one option and ensure all teams are following it. Or we'll have to delete the dynamic imports and regular imports support then to keep only one way of doing things.

**Comment by LarsDenBakker** [comment]
I agree there should be one way to load it, and that way should be performant by default.

> When I compare this to the amount of code you need to write and maintain to load icon bundles like you showed above, I see a lot more problems there. Especially when I think like multiple teams will have to agree on where that thing should be loaded from. I guess to keep things independent they'll have to do this is every isolated component, which is terrible. We already see a similar problem happening with reusable translations, I don't want people to face same issues with icons too.

Component libraries also define the icon sets and thus set up the icon loading logic once, and all the teams uses the namespaces from that component library.

> I miss the point here. I see that the more teams work on the same app, the more problems you create with global icon namespaces, because then isolated teams will have to reuse the same bundle with same names by creating unnecessary coupling. While with dynamic imports you just use paths as unique keys and they get automatically deduped by the browser/bundler for you, no matter how many people import from those paths from different parts of the app code. Can you elaborate with specific examples where things get out of control?

For many different teams the input for icons to display comes from some external source like an API or a CMS. With images these systems can just give you a URL or a path. With the Polymer iconset they give us the icon ID, but for ing-web there is no equivalent. They cannot give the dynamic import path, as the application has been bundled by then.

This is the main problem with the current system. In order to make it work, these teams will end up writing some kind of switch statement and make dynamic imports. This is what I mean with duplicate work.

**Comment by bashmish** [comment]
> They cannot give the dynamic import path, as the application has been bundled by then.

This is a good reason to support your proposal :+1:

Do you only want to lazy load an icon once new id is encountered? Or you want to also preload the entire iconset sometimes?

**Comment by LarsDenBakker** [comment]
Yes and no. As far as `lion-icon` is concerned, it just loads it when it encounters it. Applications could preload an iconset by importing the iconset. Because it's still backed by the module loader system, the icon's won't be redownloaded.

Although I think preloading is a pretty bad practice, I don't see why anyone would not want their content to show up before their icons.

**Comment by LarsDenBakker** [comment]
We discussed this in-person. Decided that the best approach is to advocate using dynamic imports intead of static imports, and look into a build plugin to optimize icon bundling. This way we keep the icons in the module graph as well as optimize for performance.

In a future breaking change, the icon can require an explicit opt-in to using static imports / sync icons.
