### ISSUE TITLE
Documentation on field validation states

### ISSUE THREAD

**Issue by j--w** [ing-bank/lion#714]
## Describe the bug

There currently seems to be a gap in the documentation for checking the validity of a field. From a conversation on the polymer slack it seems that using hasFeedbackFor/showsFeedbackFor are what should be used.

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/docs/forms-validation-overview--page

## Expected behavior
I would expect a section showing how to get these states for a field

An example given in the slack group was `el.hasFeedbackFor.includes('error')` to get whether or not a field is valid. 

##Additional Context
https://polymer.slack.com/archives/CJGFWJN9J/p1589539615208400

**Comment by gerjanvangeest** [comment]
@j--w Thanks for posting it here as well. Are you willing to contribute it?

**Comment by j--w** [comment]
@gerjanvangeest I can, I was meaning to come back to it  actually. Do you think there's anything beyond hasFeedbackFor/showsFeedbackFor that should be included?

**Comment by gerjanvangeest** [comment]
No, try to keep MRs as small as possible. So if we find another missing feature/demo, we could fix it in a next iteraction.
