### ISSUE TITLE
[select-rich] missing preventDefault on ArrowUp and ArrowDown

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#724]
## Describe the bug

When using up and down keys on a select-rich element focused, the page is scrolling.

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/docs/forms-select-rich--default-story
2. Focus on the first select-rich element
3. Change value with down key
4. The value is changed and the page is scrolled

## Expected behavior

Page should not scroll

## Screenshots

![2020-05-21_18-21-41](https://user-images.githubusercontent.com/9367152/82612126-1b124700-9b90-11ea-9d08-d76e8fb5aefd.gif)

## Additional context

On windows 10 Chrome Version 81.0.4044.138

**Comment by jorenbroekema** [comment]
Ah great catch! We do have it set for arrow up and down when you're focusing the listbox (the dropdown), but not when you are focusing the invokerNode. 

I verified that in lion rich select we can just do inside `__setupInvokerNodeEventListener`:

```js
this.__invokerOnKeydown = ev => {
  if (ev.key === 'ArrowUp' || ev.key === 'ArrowDown') {
    ev.preventDefault();
  }
};
this._invokerNode.addEventListener('keydown', this.__invokerOnKeydown);
```

Would you be willing to do a PR for it? I don't think a test for this is strictly necessary, I don't think we have body scroll assert tests for the other arrow preventDefaults to prevent this behaviour.. But if you can think of a test that works properly for this, it's definitely welcome 🤗 the tricky part is that you will need to make some wrapper div that's scrollable, and measure the amount of scroll after doing .focus on the invoker and simulating the keydown arrow press.

**Comment by MathieuPuech** [comment]
I will do a PR for this

**Comment by MathieuPuech** [comment]
It is not possible to do a test because KeyboardEvent dispatched programmatically are not trusted by browser and they do not scroll the page (see https://developer.mozilla.org/fr/docs/Web/API/Event/isTrusted).

To do this test, it may need something like puppeteer to control the browser directly instead of faking events.

**Comment by jorenbroekema** [comment]
Yeah don't worry about the test then I guess :) we can look into generic ways to test keyboard events at a later stage.
