### ISSUE TITLE
[input] can't change name dynamically

### ISSUE THREAD

**Issue by tescuderoSopra** [ing-bank/lion#730]
## Describe the bug

Changing a name dynamically keeps the original name.

## To Reproduce

```javascript
render() {
  // add option (Boolean) to properties to re-render correctly
  const name = this.option ? 'two' : 'one';
  const value = `${name}value`;
  return html`
    <ing-form @submit=${ev => {ev.preventDefault(); console.log(this.shadowRoot.getElementById('group').serializedValue);}}>
      <form action="/">
        <ing-fieldset name="group" id="group">
          <ing-input .name=${name} .modelValue=${value} id="input"></ing-input>
          <ing-button @click=${() => {this.option = !this.option;}}>toggle and serialize</ing-button>
        </ing-fieldset>
      </form>
    </ing-form>
  `;
}
// {one: "onevalue"}
// {one: "twovalue"}
// {one: "onevalue"}
// {one: "twovalue"}
```
## Expected behavior

Changing input names dynamically should work.

## Additional context

We don't have a fix, we just saw in the code what was the most likely cause. We first noticed this in ing-web 1. The code has changed somewhat so in ing-web 2 but the issue is basically the same: in FormRegistrarMixin (lion) this.formElements is only modified in add/removeFormElement. If an element's name changes this.formElements isn't updated and the form serializes incorrectly.

**Comment by jorenbroekema** [comment]
As mentioned in our extension layer, we should probably listen for changes to name attribute and unregister + register the field if it has changed, so that it's updated with the correct name.

PRs / failing tests are welcome :)

**Comment by nikhilgupta2001** [comment]
can you provide screen shot of the issue please

**Comment by sposh** [comment]
Not really a visual bug. We are currently looking (finally) at implementing a fix to send you a MR. Cheers

**Comment by sposh** [comment]
Trying to submit MR (https://github.com/ing-bank/lion/pull/934) but getting a "license/cla Pending — Contributor License Agreement is not signed yet.". Try to sign but it doesn't update.
