### ISSUE TITLE
Documentation link broken in storybook

### ISSUE THREAD

**Issue by remcovaes** [ing-bank/lion#735]
On https://lion-web-components.netlify.app/?path=/docs/overlays-system-overview--default-story > Configuration there is a link 'here', which is not working. It links to https://lion-web-components.netlify.app/?path=/docs/overlays-system-configuration.

**Comment by jorenbroekema** [comment]
Ah yeah true, it should link to https://lion-web-components.netlify.app/?path=/docs/overlays-system-configuration instead of https://lion-web-components.netlify.app/iframe.html?path=/docs/overlays-system-configuration--placement-mode-local

**Comment by jorenbroekema** [comment]
I can't really figure out why it's broken for the deployed storybooks. Locally these relative URLs work fine for me. Might be something with Storybook's internal router..

**Comment by MathieuPuech** [comment]
I don't know if it can fix it but there is a links add-on for storybook https://github.com/storybookjs/storybook/tree/master/addons/links

**Comment by gerjanvangeest** [comment]
We moved to md files, and the link is working now :)
