### ISSUE TITLE
Overlay demos

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#739]
## Describe the bug

It seems that overlays demos are not working

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/docs/overlays-system-configuration--placement-local
2. Try an overlay demo

## Screenshots

![chrome_2020-06-01_16-12-54](https://user-images.githubusercontent.com/9367152/83450163-c50c9180-a422-11ea-9486-7cd85c75fcb9.png)

**Comment by jorenbroekema** [comment]
The demo-overlay-system custom element is not defined in the demos, will need to look into that, thanks for reporting

**Comment by daKmoR** [comment]
thx for reporting 🤗

solved via https://github.com/ing-bank/lion/pull/742
