### ISSUE TITLE
[button] page is scrolling when space key is pressed

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#740]
## Describe the bug

I don't know if it is a desired behavior but the button does not prevent the scrolling in a page when you are focused on it and you keep the space key pressed

## To Reproduce

1. Go to Storybook button documentation page https://lion-web-components.netlify.app/?path=/docs/buttons-button--main
2. Click on the first button on page to focus it (or focus it with tab key)
3. Press space bar and keep it pressed
4. The page is scrolled

## Expected behavior

Page does not scroll

## Additional context

It seems that native button prevent the scroll when pressing space bar event when you keep it pressed.

**Comment by jorenbroekema** [comment]
I didn't even know holding space scrolls the page, good find!
