### ISSUE TITLE
[overlays] focusable elements in slots

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#741]
## Describe the bug

I try to use the dialog and in my content, I use slots for actions.

When slots have default value, the buttons inside it can't be focusable.

## To Reproduce

I created a branch on my fork showing this behavior
https://github.com/MathieuPuech/lion/tree/fix/overlays-focusable-slotted

1. Go to storybook dialog > Slots content on the fork
2. Click on button to open the dialog
3. Use tab key to focus buttons
4. Only shadow button is focusable

## Expected behavior

All dialog button are focusable

## Possible fix

I searched in the code and I found in [get-focusable-elements.js](https://github.com/ing-bank/lion/blob/master/packages/overlays/src/utils/get-focusable-elements.js#L45) this line

```javascript
slot.assignedNodes();
```
If you change it to `slot.assignedNodes({ flatten: true });`, it seems to work.

I don't know if it's the good way to do it.

**Comment by jorenbroekema** [comment]
Thanks for investigating, @tlouisse  I think you'll know whether the possible fix is the correct one, you added the assignedNodes() thing recently iirc?

**Comment by tlouisse** [comment]
Not in this part of code :) I think @LarsDenBakker wrote this originally.
Seems like a good fix to me, although I have to dive a bit deeper into that code to be 100% sure.
