### ISSUE TITLE
[overlays] When a dialog is opened, the body moved

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#745]
## Describe the bug

There is a movement in body when opening a dialog because scrollbars are not here when the dialog is opened (overflow of body is hidden).

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/docs/overlays-dialog--main
2. Open a dialog

## Expected behavior

Body size should not change

## Screenshots

![2020-06-02_10-34-50](https://user-images.githubusercontent.com/9367152/83568638-58ac9380-a4f1-11ea-94cb-e74c1243e1b0.gif)

## Additional context

The bug is not visible on OSX because scrollbars does not take width on OSX.

**Comment by daKmoR** [comment]
closed via https://github.com/ing-bank/lion/pull/746
