### ISSUE TITLE
[overlays] extract arrow markup/config into Mixin

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#755]
Currently the arrow markup and config (Popper configuration) is hardcoded in  the LionTooltip.
Popovers/dropdowns/menus also need arrows (and tooltips can also go without), so it might be a good idea to extract the arrow in a mixin that can be used in conjunction with `OverlayMixin`.

Also see: https://polymer.slack.com/archives/CJGFWJN9J/p1591364876249800

**Comment by jorenbroekema** [comment]
Closing this ArrowMixin proposal as enhancement with votes needed.

**Comment by daKmoR** [comment]
has been implemented
