### ISSUE TITLE
Resizing of overlay in select-rich

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#756]
## Describe the bug

When using keyboard to change the value of a selection in "windows/linux" interaction mode, the value changed making the invoker size changed. The overlay width should be reized too.

## To Reproduce

1. Go to storybook demo https://lion-web-components.netlify.app/?path=/story/forms-select-rich--main
2. expand the select-rich options
3. use keyboard (up and down) to change values

## Expected behavior

When invoker size changed, the width of the overlay should be resized too

## Screenshots

![2020-06-05_20-06-27](https://user-images.githubusercontent.com/9367152/83931148-2dcc7480-a769-11ea-8885-e434e9a25e22.gif)

## Possible Fix

`__syncInvokerElement` of LionSelectRich

```javascript
  __syncInvokerElement() {
    // sync to invoker
    if (this._invokerNode) {
      this._invokerNode.selectedElement = this.formElements[this.checkedIndex];
      await this._invokerNode.updateComplete;
      this._overlayCtrl._handleInheritsReferenceWidth();
    }
  }
```

But this will fix only for select-rich, the issue is maybe same for other components using the local placement overlay

**Comment by MathieuPuech** [comment]
I've seen another small issue on _handleInheritsReferenceWidth, It takes the clientWidth instead of getBoundingClientRect().width. The second width can be a float number (when zooming for example).

You can see the bug when zooming and adding borders on invoker and the first option for example

![chrome_2020-06-05_21-02-40](https://user-images.githubusercontent.com/9367152/83932373-04631700-a770-11ea-87eb-33879fdee74a.png)

But even if you have the good value of width, I don't know how you can apply it to the element.

**Comment by jorenbroekema** [comment]
Hmmm I wonder how much of a bug the first one is. I think if you implement an extension of the rich select, you need to provide some fixed width on your slotted content to get consistent width across items and also inside the invoker. I'm doubting a bit whether we should do something here, or if it should be left up to the user 🤔  and if we do something, how hard/annoying will it be for the user to then override that behaviour?

For the second one with the `clientWidth` vs `getBoundingClientRect().width`, I agree it's a small bug 👍

**Comment by daKmoR** [comment]
when we look at the native select... it's width will always be the width of the longest option... so it's size never changes... (at least on mac)

![Kapture 2020-08-03 at 16 03 15](https://user-images.githubusercontent.com/24378/89191214-e57fd600-d5a2-11ea-9c0b-f47a53e8dedd.gif)

so how about we do the same? e.g. get the option value with the biggest width and use that width also for the invoker?

**Comment by MathieuPuech** [comment]
It's the same behavior on windows. I suppose it's better to have a width taking the longest option.
