### ISSUE TITLE
[select-rich] click on label does not focus the input

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#757]
## Describe the bug

When clicking on label, it should focus the input (it's like that for native select)

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/story/forms-select-rich--main
2. Click on "Favorite color" label

## Expected behavior

The select invoker should be focused

**Comment by tlouisse** [comment]
Very well pointed out (as always 😉).
More generically speaking, this should be fixed for all FormControls that don't build upon platform primitives (think of `<input>`, `<textarea>`, `<select>`).

For instance, the `lion-switch` has the same problem, as pointed out here: https://polymer.slack.com/archives/CJGFWJN9J/p1587928939142400

So basically, when `._inputNode` is not a platform primitive, we should build some logic into `FormControlMixin` that places focus on it when the label is clicked.

**Comment by tlouisse** [comment]
This could be solved by adding this as to `FormControlMixin.prototype. _enhanceLightDomA11y`:

```
      _focusInputOnLabelClick() {
        const platformInputs = ['INPUT', 'TEXTAREA', 'SELECT'];
        if (platformInputs.includes(this._inputNode.tagName)) {
          // We rely on the platform via: `<label for="my-input"><input id="my-input">`
          return;
        }
        this._labelNode.addEventListener('click', () => {
          this._inputNode.focus();
        });
      }
```
See: https://github.com/ing-bank/lion/blob/feat/form-enhancements/packages/field/src/FormControlMixin.js#L189

**Comment by daKmoR** [comment]
for a select it's focus but for a switch it's a toggle of the checked state... I don't thin we can generalize it... I will add it to rich-select and switch directly for now 👍
