### ISSUE TITLE
[select-rich] focus after collapsing

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#759]
## Describe the bug

When a select-rich is blurred, it closes and after closing, it focus it. It's an issue when you open another select-rich.

## To Reproduce

1. Go to [Select-rich storybook demo](https://lion-web-components.netlify.app/?path=/docs/forms-select-rich--main)
2. Click on first select-rich to opened it
3. Scroll down to next select-rich
4. click on it to open

## Expected behavior

Should not scroll to the first select-rich opened and should focus the new select-rich.

## Screenshots

![2020-06-07_14-14-51](https://user-images.githubusercontent.com/9367152/83976758-04772a00-a8ca-11ea-9b25-75398fca0ddf.gif)

## Additional context

The issue is the same if you scroll and click on anything else on screen.

**Comment by tlouisse** [comment]
It would probably be fixed if line 492 would be enabled again:
https://github.com/ing-bank/lion/blob/master/packages/overlays/src/OverlayController.js#L493
```
      // We only are allowed to move focus if we (still) 'own' it.
      // Otherwise we assume the 'outside world' has, purposefully, taken over
=>    // if (this._contentWrapperNode.activeElement) {
```
@daKmoR or @jorenbroekema: do you know if this was purposefully commented out and if it's safe to enable again?

**Comment by jorenbroekema** [comment]
I'm not aware of why it's commented out, maybe git blame it :P? If it was me, then I'd say uncomment it to fix this

**Comment by daKmoR** [comment]
that is really an interesting one... and possible 2 fold...

the native input
1) prevents scrolling when a select is open 😱  (never thought about that 🙈)
2) it closes before you can open another one

Note: once I open the select I try to scroll with my mouse wheel but nothing happens
![NativeSelectBlocksScrolling](https://user-images.githubusercontent.com/24378/84036075-052cc080-a99d-11ea-9cb2-1917a74b033f.gif)

probably better to align with the native browser behaviour in that case right? 🤔
opinions?

**Comment by MathieuPuech** [comment]
It's not the same behavior on Mac or on Windows. On windows, scrolling is closing the select

**Comment by MathieuPuech** [comment]
![2020-06-08_10-02-04](https://user-images.githubusercontent.com/9367152/84039361-237bc780-a96f-11ea-935d-7bbf1aa2c25a.gif)

**Comment by daKmoR** [comment]
oh boy 😅

so what shall we do? we already have Operating System specific behaviour regarding keyboard navigation... should we mimic mouse behaviour based on OS as well? 🤔

**Comment by MathieuPuech** [comment]
I suppose it will be better, I didn't checked on mobile, it's maybe different. The is a different behavior for tab key: on mac, tab key is doing nothing when the select is opened.

**Comment by tlouisse** [comment]
Looks like there's 3/4 problems described in this issue:

1. we should not focus an element after hide when an external context controls focus (opening post)
2. no scrolling of page when overlay open (could be OverlayController option `preventsPageScroll`)
3. when clicking outside on an interactive element (like a button), the click action should be ignored for that element
4. overlay should close on scroll(?)

The original issue (1) will be fixed by https://github.com/ing-bank/lion/pull/1331

For the rest, we could open DIscussions
