### ISSUE TITLE
Lion dialog not working correctly on Iphone Safari with VoiceOver on

### ISSUE THREAD

**Issue by remcovaes** [ing-bank/lion#763]
## Describe the bug

When opening the lion dialog, the focus is not moved to the dialog, but stays at the invoker button.

## To Reproduce

Reproduced on:
iPhone SE iOS version: 13.5.1
iPhone 11 iOS verions: 13.3.? and 13.5.1

Recipe:
1. Go to the storybook example of lion dialog.
2. Turn on VoiceOver
3. Open the popup via the invoker.

## Actual behavior

Focus stays on the invoker button.

## Expected behavior

Expecting the focus to go to the dialog.

## Screenshots

The red arrow is pointing to the current focus.

![lion-dialog-bug](https://user-images.githubusercontent.com/20537012/84261313-d9841480-ab1b-11ea-9c5a-0b66cabfd33e.PNG)

## Additional context

It works correctly on Android with Talkback on.

**Comment by remcovaes** [comment]
I have just tested it with iOS 14.4 with VoiceOver and the current live td-dialog(v0.10.0). It is fixed.

**Comment by erikkroes** [comment]
Thanks for letting us know Remco. Glad it got better!

Safari and VO never cease to surprise us.
