### ISSUE TITLE
[core][proposal] DelegateMixin improvement

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#77]
## DelegatesMixin 
_(improvement proposal for to be deprecated DelegateMixin)_

Composition is a very common pattern for our UI components, especially since it is not possible to extend native elements.
Often we do want to (partly) keep the original api, and therefore we need the delegation pattern.

### Goal of the mixin: 
- have a declarative notation that shows me what properties/methods and events will be delegated, and what added api host offers on top.
- Reduce all the boilerplate (property syncing via templates/and or imperative boilerplate) and focus on the added functionality

### Problems with the current mixin (DelegateMixin)
- Getters and setters defined override those defined by UpdatingElement. Hooking into sync or async observers for delegated properties is thus not possible, since  `this.requestUpdate()` is never called for them. Currently, only integrates with ObserverMixin (which should be opt-in mixin)
- No support for documentation/Intellisense tools -> we should place properties in `static get properties`
- Attribute delegation leads to problems and is not needed
    - Attributes are reflected to dom and affect a11y (especially if delegation target is light dom). Having two attributes `aria-label` or `id` breaks functionality (as an example, since those props/attrs should never be delegated in the first place)
    - Currently, attributes are read initially, deleted and put on delegation target. This is a non solution and leads to a confusing developer experience -> `<lion-input name=“myField”></lion-input>` -> it’s horrible DX that querySelector(‘[name=“myField”]’) now gives back the delegation target.
    - Delegation of attributes will be done indirectly (since the delegation target decides whether the prop should be reflected to attribute)
- No state at host level: the host element is the SSOT interaction point for the Application Developer. Regardless of whether its child delegation targets are available, it should maintain state. 
- Supports only one delegation target. When a host holds multiple interactive targets and it becomes `disabled`, all its interactive children should become as well
- Event delegation currently leads to weird behaviour. We should hide implementation details from Application Developer. Currently, we get the delegation target as the event.target. AD should not even know about the existence of delegation target. Plus, he/she just expects the host element here.
- In some cases it turns out delegation targets (when put in light dom) are not reliably present at firstUpdated. When a delegationTarget becomes available, host should sync. DelegatesMixin should expose a method to resynchronise, so that slot-changed events that arrive lazily or something will be captured.

### New mixin requirements:
- Plays nicely with UpdateMixin (hooks into requestUpdate instead of overriding and aligns with `static get properties`)
- Delegates props (and methods) via declarative config:
    - Methods can be put on property list as type Function
- Exposes helper function for events:
    - A static config object doesn’t play well with docs/Intellisense. We should imperatively trigger with helper fn and annotate with `@event` jdsoc.
    - For events, we expose a function `DelegatesMixin._delegateEvent(‘target-event’, targetNodeKey)`. This will listen for the event on target, cancel it and retrigger it under the same name on the host(will keep same characteristics, but sets target to host, since that is what is expected by AD).
- Exposes helper function for syncing to (lazy) targets: `DelegatesMixin._syncDelegationTarget(targetNodeKey)` (also scheduled events are synced)
- Supports multiple delegation targets: when I have a `<field-listbox-dropdown>`, I want to disable all interactive elements (button and listbox) whenever my hosts becomes disabled

**Comment by tlouisse** [comment]
@daKmoR : could you please have a quick look?
The sooner we can pick this up, the better. Allows us to solve tech debt, solve bugs and start with 'select-rich' without tech debt from the start.

I will post a working code example on Stackblitz later

**Comment by bashmish** [comment]
I was thinking if we can be one step ahead and consider the future without IE11. Can we design smth that would be replaced by ES Proxy in the future? So a made a quick test:

```js
customElements.define('my-component', class MyComponent extends HTMLElement {
  constructor() {
    super();
    return new Proxy(this, {
      get(target, prop, receiver) {
        // implement delegation logic for reading
        return Reflect.get(...arguments);
      },
      set(obj, prop, value) {
        // implement delegation logic for writing
        return Reflect.set(...arguments);
      },
    });
  }
});

document.createElement('my-component');
// Uncaught TypeError: Failed to construct 'CustomElement': The result must implement HTMLElement interface
```

Am I missing smth? Very disappointing future if not :( I was under impression that Proxy was introduced for this sort of things. Not to say about using it in LitElement to implement properties instead of creating tons of getters/setters.

**Comment by tlouisse** [comment]
Seems like a cool future solution, although:
- would not really meet SSOT goal, which plays nice with observers (`_requestUpdate` and `updated`. Think this was also suggested by @dakmor)
- Not polyfillable for IE I believe?

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
I think this already got implemented.

"closing" this feature request - feel free to create a new one if something is still missing 🤗
