### ISSUE TITLE
2 Tests are failing depending the environment

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#776]
## Describe the bug

2 tests are failing on certain environments.

```
FAILED TESTS:
  Form Integrations
    × ".serializedValue" returns all non disabled fields based on form structure
      HeadlessChrome 83.0.4103 (Windows 10.0.0)
    AssertionError: expected { Object (full_name, date, ...) } to deeply equal { Object (bio, checkers[], ...) }
      + expected - actual
         "checkers[]": [
           []
         ]
         "comments": ""
      -  "date": "2000-12-11"
      -  "datepicker": "2020-12-11"
      +  "date": "2000-12-12"
      +  "datepicker": "2020-12-12"
         "dinosaurs": ""
         "email": ""
         "favoriteColor": "hotpink"
         "full_name": {
    at Context.<anonymous> (packages/form-integrations/test/form-integrations.test.js:9:39)
  parseAmount()
    × parseAmount with locale set and length is more than four
      HeadlessChrome 83.0.4103 (Windows 10.0.0)
    AssertionError: expected 6 to equal 6000
      + expected - actual
      -6
      +6000
    at Context.<anonymous> (packages/input-amount/test/parsers.test.js:158:10)
    at Test.Runnable.run (node_modules/karma-mocha-snapshot/lib/adapter.js:14:17)
```

## To Reproduce

It's hard to know how to reproduce it, it seems that my local environment is making the tests failing. It could be something about timezone and locale settings.

## Additional context

My current locale is canadian french and my timezone is Eastern Daylight Time (GMT-4).

**Comment by MathieuPuech** [comment]
I found that test on parseAmount is failing on chromium for are working on chrome

Chromium Version 85.0.4181.0 (Build de développement) (64 bits) ❌ 
Chrome Version 85.0.4173.0 (Official Build) dev (64-bit) ✔️ 

After more investigations, I saw that my chromium get the wrong separator.

On chromium:
```javascript
Intl.NumberFormat('gb-GB', {
    style: 'decimal',
    minimumFractionDigits: 1,
  }).format('1')[1];
// output: ,
```

On Chrome:
```javascript
Intl.NumberFormat('gb-GB', {
    style: 'decimal',
    minimumFractionDigits: 1,
  }).format('1')[1];
// output: .
```

It seems to be a browser bug. I investigate on the other test bug

**Comment by MathieuPuech** [comment]
for the second test, I've added a PR fixing it

**Comment by gerjanvangeest** [comment]
Which language & locale is `gb-GB`, shouldn't you try `en-GB`?

**Comment by MathieuPuech** [comment]
Yes, it seems that when the locale is incorrect, chromium gives a different response.

I will fix the test to use a correct locale

https://github.com/ing-bank/lion/blob/47cadb1696c7d1637b899702988e176e4ca74a1b/packages/input-amount/test/parsers.test.js#L156
