### ISSUE TITLE
Fix web-test-runner uncaught errors

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#793]
## Describe the bug

WTR throws 'uncaught errors'. 
My guess is that we can fix those by guarding/rejecting 'outstanding Promises' on disconnectedCallback...

**Comment by tlouisse** [comment]
Most of them are fixed by Joren and me (those inside component files), we have a few leftovers in test files/suites.

**Comment by jorenbroekema** [comment]
I prefer this as a bug, because quite likely uncaught errors are bugs. We should catch them or prevent them :)

**Comment by daKmoR** [comment]
only two are remaining and there are dedicated issues for it
https://github.com/ing-bank/lion/issues/832
https://github.com/ing-bank/lion/issues/826
