### ISSUE TITLE
[dialog] using tooltip in a dialog

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#813]
## Describe the bug

When a tooltip is used in a dialog, the dialog content is merged in the tooltip

## To Reproduce

https://webcomponents.dev/edit/Zl8XlJbzU7JUZ6QFhwUD

## Expected behavior

Dialog content not merged with tooltip content

**Comment by tlouisse** [comment]
I think this works as expected. The tooltip content is currently not styled, so it looks like if it merges with the overlay backdrop. If I add some inline styles in the demo, the tooltip content will be painted on top.

**Comment by MathieuPuech** [comment]
I'v added some style to see the situation. The dialog with black background and the tooltip with red background.
The dialog content is in the red background box (tooltip). Only the tooltip invoker is in the dialog content

**Comment by MathieuPuech** [comment]
![image](https://user-images.githubusercontent.com/9367152/87309397-8de1d380-c4ea-11ea-916d-04de4354876d.png)

**Comment by tlouisse** [comment]
Ah, the `<div slot="content">` inside tootlip wasn't closed correctly, so `<div>...<div>` -> `<div>...</div>`.
You scared me for a moment :)

**Comment by MathieuPuech** [comment]
you're right, sorry for scaring you!
