### ISSUE TITLE
[overlays] Dialog not closed on ESC after clicking outside

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#818]
##  Expected Behavior

Dialog is closed on ESC after clicking outside

## Current Behavior

Dialog does not close on ESC after clicking outside

## Steps to Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/story/overlays-dialog--main
2. Click on the overlay
3. Press ESC

Additional information:

* Browser: Chrome

(original bug report in our extension layer by Lars den Bakker)

**Comment by tlouisse** [comment]
Best solution (imo) would be to solve this in https://github.com/ing-bank/lion/blob/master/packages/overlays/src/utils/contain-focus.js

A modal dialog should make sure activeElement can never be outside of the dialog. Since this currently happens, the [esc] keypress will not be registered. (configuring `closeOnOutsideEsc` is not an option, since it will close a full chain of nested overlays by default) 

Maintaining activeElement could be done via:
- listen for outside click
- if (!rootElement.activeElement) -> put focus on rootElement

**Comment by erikkroes** [comment]
I think this has been mentioned before and also discussed with UX. 

- Close on ESC and clicking outside should be a default for dialogs (they're kinda equivalent).
- Opening a dialog should put the focus on the entire dialog (not the first interactive element) for consistency
- Closing a dialog should put the focus on the invoker

**Comment by tlouisse** [comment]
I agree about the default, but allowing configuration with `hidesOnOutsideClick:false` and `hidesOnEsc` will also make a lot of sense.
If you would display a multistep form in your dialog, it might be annoying that you close your dialog with an accidental click outside of it. This used to be the reason in the past in our extension layer for disabling outside clicks (but allowing esc).
