### ISSUE TITLE
[form-core][docs] update Validator import paths

### ISSUE THREAD

**Issue by jdvivar** [ing-bank/lion#819]
## Describe the bug

A JS console error is thrown `Validators array only accepts class instances of Validator. Type "object" found.` when using `Required` validator from `@lion/validate` on textarea and checkboxes (at least, that I know of), it makes validation non-functional

## To Reproduce

Check this Glitch I created to reproduce:
https://glitch.com/edit/#!/validator-bug-lion-form

## Expected behavior

No error should be thrown, and validation should be functional

## Screenshots

Please check Glitch demo

## Additional context

All packages using latest available versions via Snowpack

**Comment by jdvivar** [comment]
Solved by importing `Required` validator from `@lion/form-core` instead of `@lion/validate`.

Can you please update package docs to reflect this? (I guess it might not be possible since you already have no package with that name, right?)

**Comment by daKmoR** [comment]
Added a deprecation notice to npm.
You can see it here https://www.npmjs.com/package/@lion/validate

Going to close - if you think more should be done please let us know 🤗

**Comment by jdvivar** [comment]
That's perfect. I'm sure it would help other developers new to lion forms. Thanks!
