### ISSUE TITLE
add Typescript definitions

### ISSUE THREAD

**Issue by ben8p** [ing-bank/lion#82]
Since lit-element is the base of Lion webcomponents and since lit-element support (pretty nicely) typescript, it would be great to have definitions files shipped with lion too.

As a kickstart, here is the one I started creating:
```
declare module '@lion/ajax' {
    import { AxiosRequestConfig, AxiosPromise, AxiosError } from 'axios';

    namespace ajax {
        export type Promise<T> = AxiosPromise<T>;
        export type Configuration = AxiosRequestConfig;
        export type Error = AxiosError;
        export type Data = Record<string, unknown>;
        export function get<T>(url: string, configuration?: AxiosRequestConfig): Promise<T>;
        function del<T>(url: string, configuration?: AxiosRequestConfig): Promise<T>;
        export { del as delete };
        export function patch<T>(url: string, data: Data, configuration?: AxiosRequestConfig): Promise<T>;
        export function post<T>(url: string, data: Data, configuration?: AxiosRequestConfig): Promise<T>;
        export function put<T>(url: string, data: Data, configuration?: AxiosRequestConfig): Promise<T>;
    }
}

declare module '@lion/core' {
    export * from 'lit-element';
    export * from 'lit-html/directives/if-defined';
}

declare module '@lion/localize' {
    import { LitElement } from 'lit-element';

    namespace localize {
        export function loadNamespace(namespace: Record<string, (locale: string) => Promise<unknown>>): void;
        export function addEventListener(eventName: 'localeChanged', callback: () => void): void;
        export function msg(key: string, variables: Record<string, unknown>): string;
        export let locale: string;
    }

    class LocalizeClassMixin extends LitElement {
        public static waitForLocalizeNamespaces: boolean;

        public static localizeNamespaces: (Record<string, (locale: string) => Promise<unknown>>)[];

        public performUpdate(): Promise<unknown> | void;

        public connectedCallback(): void;

        public disconnectedCallback(): void

        public msgLit(key: string, variables?: Record<string, unknown>, options?: Record<string, unknown>): void | string;

        public onLocaleReady(): void;

        public onLocaleChanged(): void;

        public onLocaleUpdated(): void
    }

    export function LocalizeMixin(superClass: typeof LitElement): typeof LocalizeClassMixin;
}

```

**Comment by bashmish** [comment]
We certainly want type-safety in our code and this is on our roadmap already 👍 

There was a meeting where we discussed possible solutions:

1. Rewrite everything in TypeScript
2. Provide type definition files (basically your proposal)
3. Use JSDoc driven types (@daKmoR advocates for it and he explained the approach [here](https://dev.to/dakmor/type-safe-web-components-with-jsdoc-4icf)).

I think for now the conclusion is that we want the source code in JavaScript to stay native and allow easier contributions from people who don't know TypeScript well. So the choice was more between 2 and 3. And 3 won thanks to the closer integration between types, code and documentation (read @daKmoR [article](https://dev.to/dakmor/type-safe-web-components-with-jsdoc-4icf) for more information). But I think 3 is also very limiting and does not allow to describe complex types, so we need to investigate it further.

I'm not sure though when we gonna work on improving our existing code to include type information.

**Comment by devcer** [comment]
I would like to work on this? Can someone help me to get started with this?

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by daKmoR** [comment]
superseded by https://github.com/ing-bank/lion/issues/795

and we are almost there 🤗

"closing" this feature request
