### ISSUE TITLE
[form-registration] Serialized value set on re-render before it rendered

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#828]
## Describe the bug

Since the registrationReady promise is resolved in firstUpdated, and the formatted/model/serialized-Value setters all wait for registrationReady, usually we only set these values after the element has rendered (because we await for registrationReady).

However, if you re-render part of a form with such elements inside it, and they get fully re-rendered, they get reconnected to the DOM. If serializedValue setter is then triggered, it doesn't wait for updateComplete, because it only waits for registrationReady which already resolved in the firstUpdated.

Moving this logic https://github.com/ing-bank/lion/blob/master/packages/form-core/src/registration/FormRegistrarMixin.js#L78 to updated instead of firstUpdated should solve that problem.

## Steps to Reproduce

Reproduction is still needed in order to create a regression test for this. Moving the logic works and results in 0 failing tests, but we should have a regression for sure.

**Comment by daKmoR** [comment]
As we reworked the form registration system to be sync - I don't think this will be an issue anymore.

If it still is please reopen with additional information 🤗
