### ISSUE TITLE
[ChoiceGroupMixin]: the serializedValue setter is not applied to lion select rich from the ChoiceGroupMixin

### ISSUE THREAD

**Issue by onkar75** [ing-bank/lion#836]
## Describe the bug

The serializedValue setter is not applied to lion select rich from the ChoiceGroupMixin

## To Reproduce

1. Go to internal ING demos
2. Click on 'select an account'
3. 
- Then go into dev tools console, select ing-form in elements, and save the serialized value of the form into a variable const prev = $0.serializedValue. 
- Then go to Wide Right Form where no account is selected yet --> dev tools, select ing-form in elements, and set the serialized value $0.serializedValue = prev; 

## Expected behavior

the serializedValue setter should applied to lion select rich from the ChoiceGroupMixin

**Comment by jorenbroekema** [comment]
https://github.com/ing-bank/lion/pull/829 fixed
