### ISSUE TITLE
[form] setting serialized value on form throws error

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#838]
Setting serializedValue on lion-form throws an error in the code that is setting the serialized value on the field.

`<lion-form name="test" id="test" .serializedValue=${{firstName: 'Foo'}}>
<form>
<lion-input name="firstName" id="firstName"></lion-input>
</form>
</lion-form>`

Unhandled rejection: TypeError: Cannot set property 'serializedValue' of undefined
   at http://localhost:9648/packages/form-core/src/form-group/FormGroupMixin.js:339:47

**Comment by daKmoR** [comment]
@T-Motion hey, so the problem was a missing import to lion-input.js 😅  besides that everything works as expected and all tests are green 💪

I'm going to close as it seem to be not an issue

feel free to break the test again and reopen if needed 🤗
