### ISSUE TITLE
[providence] Does not search distribution files

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#850]
## Describe the bug

Providence does not analyze my target project properly. I publish my library to NPM with the following config, where I build the `dist` on prepublish:
```json
{
  "files": [
    "dist"
  ]
}
```

This means that the `dist` folder ends up in the `keepFilter` here: https://github.com/ing-bank/lion/blob/master/packages/providence-analytics/src/program/services/InputDataService.js#L297

However, since it's an auto-generated folder, it also ends up in the `removeFilter` because I put `/dist/` in my `.gitignore` file.

Therefore, neither my `src` nor my `dist` gets searched, and I end up with an empty `providence-extend-docs-data.json`.

## To Reproduce

1. Create a project with `/dist/` in .gitignore, but with `dist` inside the files property in `package.json`
2. Install `@lion/dialog` for example, so we have a reference project
3. Install providence `yarn add --dev providence-analytics`
4. `yarn providence extend-docs -r 'node_modules/@lion/*' --prefix-from lion --prefix-to pre`

## Expected behavior

A non-empty providence-extend-docs-data.json, because I have some components that extend LionDialog in both my 'src' and 'dist'.

## Screenshots

```
No files found for path '<localPath>'
```
Where localPath is your root folder of your project.

## Potential Solution

It definitely needs to analyze either your source code or your published code. For the purpose of extending lion docs, I would prefer if it analyzed and rewrote paths to my `src` folder, because that makes my docs/demos easier to debug if something goes wrong there. Furthermore, I don't want my docs/demos to be reliant on my build-process that creates the `/dist` folder that I publish to NPM.

So, question is then, what should the solution be? Should the `keepFilter` be empty if the user hasn't supplied one themselves? That way it searches (`anymatch`es) everything that's not in the `removeFilter`, which means that it will search `src` unless otherwise specified by the user. In my opinion, relying on the `package.json` `files` entry, is a bad idea, since so many projects publish a built folder (e.g. `dist`) that does not get committed to git.

And if the keepFilter is not prepopulated with the NPM files field, how should the user specify one?

Some ideas (which involves an empty / unused keepFilter if not used):

- Use the already available whitelist CLI flags
- providence external config only solution, `keepFilter`
- A new CLI flag `--keep-filter <glob>` but this is a bit harder if you want to allow an array of globs or more complex things which `anymatch` accepts. Alternatively, could make it a boolean flag: `--scan-published-files-only`?

Happy to create a fix but I wanna hear from you first @tlouisse  :)

**Comment by tlouisse** [comment]
Yeah, tricky situation. Currently a bit too eager.

Should we be able to say we are either in 'published' (dist) or in 'local'(git/src) mode?
- A) if `.gitignore` found: set 'git' mode and don't pay attention to package.json "files" entry
- B) if `.gitignore` not found, set 'published' mode (only pay attention to package.json "files" entry)

But in situation A, it should be possible to override (switch to build mode). Then you need a flag like you proposed indeed.
Maybe `--whitelist-published`?

**Comment by jorenbroekema** [comment]
Maybe a boolean flag for A) --> `--scan-published`? Which switches from gitignore-mode to package.json-files-mode?

**Comment by tlouisse** [comment]
Yes, that was what I meant indeed (instead of 'build mode' I meant 'published mode').   
And I put whitelist in the name to make clear that it has a relation to the oher whitelist param.
We could also do `--whitelist-mode 'published'` (to allow for more flexibility might this be needed later)

**Comment by jorenbroekema** [comment]
Sounds alright with me 👍  I'll try to pick it up tomorrow

**Comment by MathieuPuech** [comment]
I've created 2 repositories to test the extension of documentation with the lea-tabs example:

Single repo:

https://github.com/MathieuPuech/lea-tabs/tree/feat/extendLionDocumentation

Mono repo:

https://github.com/MathieuPuech/lea/tree/feat/extendLionDocumentation

It's not working with version 0.3.0. When I try with version 0.1.0, generation of analytics seems to work in my Mac but not on windows. And it's not working in the monorepo, I don't understand how it can be setup to work.

In the documentation, there is some parts for monorepo and some other for singlerepo.
