### ISSUE TITLE
[providence] Extend docs config is empty for found dependencies

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#851]
## Describe the bug

When I create a new project and try to use some lion dependency, providence does not output the query results properly, or does not find the matches.

providence-extend-docs-data.json
```js
["[no-dependency]","[no-dependency]","[no-dependency]"]
```

When using `@lion/input`. The no-dependency ones make sense because `@lion/input` installs `localize`, `form-core` and `core`, upon which there is no direct dependency.

## To Reproduce

1, Create a new project/folder
2. `git init && npm init -y`
3. `yarn add lit-element @lion/input && yarn add --dev providence-analytics
4. Create a .gitignore
```
/dist/
/node_modules/
```
5. Create a custom input --> `/src/CustomInput.js`
```js
import { LionInput } from '@lion/input';
  
export class CustomInput extends LionInput {}
```
6. Create an element definition file --> `/custom-input.js`
```js
import { CustomInput } from './src/custom-input/CustomInput.js';

customElements.define('custom-input', CustomInput);
```
7. Add these two files to `package.json` --> `files` property (optional, does not make a difference for the result)
8. `yarn providence extend-docs -r 'node_modules/@lion/*'  --prefix-from lion --prefix-to custom`

## Expected behavior

A `providence-extend-docs-data.json` file with some meaningful output but I get:

providence-extend-docs-data.json
```js
["[no-dependency]","[no-dependency]","[no-dependency]"]
```

instead.

**Comment by jorenbroekema** [comment]
Note: it works properly in `0.1.0` but is then broken from `0.2.0` onwards

**Comment by tlouisse** [comment]
Somehow it draws the conclusion that there is no dependency (for instance` @lion/input`) present: https://github.com/ing-bank/lion/blob/master/packages/providence-analytics/src/program/analyzers/helpers/Analyzer.js#L118
This should be based on all data package jsons ref and target (name, dependencies, devDependencies)

**Comment by jorenbroekema** [comment]
Yes that conclusion is correct. But apart from the three times no-dependency, it should also push a sibling with the data for the one that does have a direct dependency.
- @lion/input, dependency --> missing data :(
- @lion/localize, no dependency --> correct
- @lion/form-core, no dependency --> correct
- @lion/core, no dependency --> correct

**Comment by tlouisse** [comment]
Ah. Seems related to anymatch/ 'auto whitelist' introduction as well (v0.2.0).
Most likely will be fixed by: https://github.com/ing-bank/lion/issues/850.
Maybe we can still get rid of `"[no-dependency]"` somehow

**Comment by jorenbroekema** [comment]
Actually when I monkey patched the whitelisting, I still didn't get any data :\ so I doubt it will be fixed by #850

**Comment by tlouisse** [comment]
@jorenbroekema @MathieuPuech 

With latest branch(https://github.com/ing-bank/lion/issues/850) it seems to work. 
At least, when run on https://github.com/MathieuPuech/lea-tabs/tree/feat/extendLionDocumentation, I get :

```js
[
  {
    "name": "LionTabs",
    "variable": {
      "from": "LionTabs",
      "to": "LeaTabs",
      "paths": [
        { "from": "./index.js", "to": "./index.js" },
        { "from": "./src/LionTabs.js", "to": "./index.js" },
        { "from": "@lion/tabs/index.js", "to": "./index.js" },
        { "from": "@lion/tabs/src/LionTabs.js", "to": "./index.js" }
      ]
    },
    "tag": {
      "from": "lion-tabs",
      "to": "lea-tabs",
      "paths": [
        { "from": "./lion-tabs.js", "to": "./lea-tabs.js" },
        { "from": "@lion/tabs/lion-tabs.js", "to": "./lea-tabs.js" }
      ]
    }
  }
]

```

**Comment by MathieuPuech** [comment]
@tlouisse Are you talking about this branch https://github.com/ing-bank/lion/tree/feat/providenceWhitelistMode ?

With this branch, I have a fatal error `JavaScript heap out of memory`. It seems to search in all the node_modules folders

**Comment by tlouisse** [comment]
Yes, I checked out https://github.com/MathieuPuech/lea-tabs/tree/feat/extendLionDocumentation. I ran it based on providence-analytics#0.3.0 and got an empty output.
Then I put the contents of branch https://github.com/ing-bank/lion/tree/feat/providenceWhitelistMode 
in `node_modules` and got the result as pasted above.
Task was performed relatively quickly, so no indication of memory problems...  (on a Mac, node v12)

**Comment by MathieuPuech** [comment]
I tested it on windows node v12 only yet, I will test on my Mac to validate to see if there is no issues.

On windows, it seems to go through all dependencies of node_modules, that's why it's stopping with a fatal error.

**Comment by MathieuPuech** [comment]
@tlouisse I confirm that it's working on my Mac, I suppose it's a windows path issue

**Comment by tlouisse** [comment]
> I tested it on windows node v12 only yet, I will test on my Mac to validate to see if there is no issues.
> 
> On windows, it seems to go through all dependencies of node_modules, that's why it's stopping with a fatal error.

Thanks for testing 💪  We will look into the windows issues later.
