### ISSUE TITLE
[button] event delegation doesn't work as expected

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#89]
When I add a `click` event listener on a parent element of a `lion-button`, it should give me back the `lion-button` as `target` on the event.

See: https://stackblitz.com/edit/lion-button-delegation?file=index.html

**Comment by bashmish** [comment]
I guess if we fix this, we automatically break [this](https://github.com/ing-bank/lion/blob/%40lion/button%400.1.22/packages/button/test/lion-button.test.js) which was the general idea behind the current button design.

So we need to make a decision:

1. do we want to keep a simple form integration and accept the existence of bugs like this
2. or we want to make a custom `lion-button` logic to submit parent forms

I tend more and more to the second option now.

**Comment by tlouisse** [comment]
I tend towards 2 as well. Maybe it would work if we do something like (pseudo code):

```js
// no 'hostClickEvent.stopPropagagtion()' and no '$$slot('button').click()';
if (this.type === 'submit') {
  this.$$slot('button').form.submit();
}
```

Need to check uic-form history again if it would cover all use cases.

**Comment by tlouisse** [comment]
With 'all use cases' I meant (implicit form submission)[https://www.w3.org/TR/html5/sec-forms.html#implicit-submission]. 
With my suggested approach, this functionality will most likely still work.

**Comment by bashmish** [comment]
@tlouisse I managed to fix it using this [approach](https://github.com/ing-bank/lion/pull/157/commits/59e456e11f9dce5ca8b83f3b0849f286788d0ffb) and it does not break integration with forms.
