### ISSUE TITLE
do the examples require a babel workflow or similar?

### ISSUE THREAD

**Issue by staabm** [ing-bank/lion#905]
## Describe the bug

when looking at examples, e.g. https://lion-web-components.netlify.app/?path=/docs/forms-form-overview--main

it is mentioned to use imports of the form `@...`.
![grafik](https://user-images.githubusercontent.com/120441/91276795-4bb2df80-e782-11ea-81dd-b6b49f5d378e.png)

As far as I understand it, these imports only work in a environment, where babel workflow etc. are configured?
is there a doc somewhere, which describes all prerequisites I need to fullfill to use the components?

In a real 'existing' project there might be no such bundler/loader configured and therefore the example code won't work?

it might be obvious for someone living in a preact/react/babel world, but for someone using native javascript/native webcomponents this does not look like, as it would work.

thanks for this great lib with awesome docs. looking forward to understand and use it :-)

**Comment by staabm** [comment]
other examples use some notations, which I am not able to interpret.

example https://lion-web-components.netlify.app/?path=/docs/forms-input-amount--main

![grafik](https://user-images.githubusercontent.com/120441/91277533-3e4a2500-e783-11ea-8646-1faeb6e61a0f.png)

are these `${{` and `${..}` things, native javascript syntax?
why do some attributes have a `.` prefix?

if these questions ara anwered elsewere, maybe you could just link to a introducing article/doc?

**Comment by thepassle** [comment]
What you see here is a tagged template literal. Javascript has _template literals_ that allow you to embed expressions inside a string, e.g.: 

```js
console.log(`1+1=${1+1}`); // "1+1=2"
```

The example you're seeing uses _tagged_ template literals (more specifically [lit-html](https://lit-html.polymer-project.org/)). Lit-html works as-is in the browser, and doesnt require any buildstep by default. The `.` prefix is lit-html's way of setting a property on an element. You can find more information on lit-html's syntax [here](https://lit-html.polymer-project.org/guide/writing-templates#bind-to-attributes).

The `${{` syntax may be confusing, but its simply a js object inside a template literal expression. 

Regarding imports such as `import '@lion/form/lion-form.js'`, these are called _bare module specifiers_. You are correct in saying that browsers don't support this syntax. So you'll need a way to transform these imports somehow, for example you can use [es-dev-server](https://open-wc.org/developing/es-dev-server.html#node-resolve) which resolves these bare module specifiers on the fly for you.

Hope that helps :)

**Comment by staabm** [comment]
thx for this great anwsers. makes a lot of sense.

what do you think about adding such kind of information to the story books' introduction?

**Comment by gerjanvangeest** [comment]
We already have a link to `lit-html` under [Technologies](https://lion-web-components.netlify.app/?path=/story/intro-lion-web-components--page#technologies) but if feel there is a need to place those links in a more prominent section , please feel free to create a Pull Request.
