### ISSUE TITLE
[feature request] lion/input-stepper component

### ISSUE THREAD

**Issue by hardikpthv** [ing-bank/lion#914]
The basic version of the input-stepper component would be a nice addition to the Lion. I will start working on it and will soon create the MR. 😄

**Comment by MathieuPuech** [comment]
What are the differences with `<lion-input-amount>`?

Is it a `input-amount-rich` (like `select-rich` for `select`)

**Comment by daKmoR** [comment]
yes it's basically a nicer `input type="number"` and will look something like this

```
[-][     12 ][+]
```

e.g. have a +/- button so you can increase and reduce with a click/space
