### ISSUE TITLE
Support focus-visible

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#917]
Chrome 86 will support focus visible: 
- https://www.chromestatus.com/features/schedule
- https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

It would be great to support this in the lion components as a progressive enhancement for browsers that support it.

**Comment by MathieuPuech** [comment]
I suppose something like [@vaadin/focus-visible-mixin](https://www.npmjs.com/package/@vaadin/focus-visible-mixin) could be done?

**Comment by LarsDenBakker** [comment]
Interesting, I didn't know that existed. However I was thinking of just doing the CSS and have it be a progressive enhancement on browsers that support it.

**Comment by tlouisse** [comment]
Nice spec 👍 
I think this comes pretty close to `[focused]` we currently have.
We use that attribute to style Lion FormControls (lion-input/lion-textarea/lion-select/lion-combobox etc etc.) when 
a child (usually a native input node) gets focus.
See: https://github.com/ing-bank/lion/blob/master/packages/form-core/src/FocusMixin.js#L14
It works for all browsers, although only for FormControls at the moment.

@LarsDenBakker Wrt the progressive enhancement part, I think Subclassers could use this in their extension layer styles already, right?
Or do we need to change something in Lion for this?
