### ISSUE TITLE
[select-rich] changing options dynamically from single option to more options

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#919]
## Describe the bug

When options are changed dynamically, the render is not updated

## To Reproduce

1. Go to https://codesandbox.io/s/lion-select-rich-dz3ce?file=/src/index.js
2. Click on Add an option
3. You can see with inspect that options are in slot

## Expected behavior

select-rich updated like done with [tabs](https://lion-web-components.netlify.app/?path=/docs/navigation-tabs--distribute-new-element)

**Comment by tlouisse** [comment]
I think it works. You need to make sure that the reference to `this.options` changes (pushing to the array doesn't trigger the render). See:
```
  addOption() {
    this.options.push(`Option ${this.options.length + 1}`);
    this.options = [...this.options];
    this.requestUpdate();
  }
```

**Comment by MathieuPuech** [comment]
I've updated my code sandbox with this and it's not working.

**Comment by tlouisse** [comment]
You're right. I did thus before without really noticing:
```
  constructor() {
    super();
    this.options = ["Option 1", "Option 2"];
}
```
There is an actual bug then with singleOption: https://github.com/ing-bank/lion/issues/677
