### ISSUE TITLE
[dialog] overlay closed on mouseup

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#920]
## Describe the bug

When you release the mouse click outside the dialog with the option to hide on outside click, the dialog is closing.

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/story/overlays-dialog--styling-content
2. Click on Button
3. Click to select text but release the mouse click outside the dialog
4. Dialog is closed

## Expected behavior

Dialog should not close when the click was initiated in the dialog

## Screenshots

![2020-09-04_14-12-02](https://user-images.githubusercontent.com/9367152/92273054-b23da900-eeb8-11ea-9207-632739d2f0a9.gif)

**Comment by daKmoR** [comment]
you are really good and finding all these edge cases 💪

keep them coming 🤗

not sure how fast we will be in resolving those 🙈
but knowing about them is the first step 👌

**Comment by MathieuPuech** [comment]
It’s ok if it’s not fixed fast. I just document issues I found when using the components. If I have time to fix them I will do of course.

**Comment by tlouisse** [comment]
> you are really good and finding all these edge cases 
> 
> keep them coming 

Amen. Well spotted :muscle: 

So what should be the behavior, you think? Only close the dialog if both mousedown and mouseup are catched outside?

**Comment by MathieuPuech** [comment]
We have 2 choices:
- close on mousedown
- close on mouseup but with the position of the mouse on mousedown

I've no idea what is best, is there any issue to close on mousedown directly?

**Comment by tlouisse** [comment]
I thought that was not default platform behavior, apparently it is :) (tested `<select>` and `<datalist>` on Chrome Linux)
Then it probably will be a matter of swapping the current click handler in OverlayController with a mousedown handler :+1:

**Comment by jorenbroekema** [comment]
Yeah I agree, mousedown seems like the most practical choice 👍
