### ISSUE TITLE
[combobox] Escape (re)opens the listbox

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#951]
## Expected behavior

When a listbox is open and a combobox has focus, I expect escape to close the listbox.
When a listbox is not open and a combobox has focus, I expect escape to do nothing.

## Actual Behavior

Escape (re)opens the listbox. When it is already open, it closes and opens again. When it is closed, it opens.

This does not happen with "Autocomplete 'list'" , but it does happen with 'inline' and 'none'.

**Comment by erikkroes** [comment]
Probably related, escape also clears the value of the textfield.

**Comment by tlouisse** [comment]
The latter is according to specs. 
The reopening occurs only on certain configurations of autocomplete I noticed before. No clue why :)

Another annoying bug: we can't press space inside textbox right now

**Comment by tlouisse** [comment]
Should be fixed in feat/combobox2 branch
