### ISSUE TITLE
[combobox] Unclear what enter/return does.

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#952]
## Expected behavior

Autocomplete shows the same option inline as it does in the listbox. Autocomplete updates after more characters are typed.

## Actual Behavior

<img width="1040" alt="Screenshot 2020-09-28 at 10 13 51" src="https://user-images.githubusercontent.com/10405024/94407139-58589800-0173-11eb-810c-fed713319608.png">

Typing 'a' opens a listbox with Apple at the top. Typing an 'r' changes the inline suggestion to Artichoke, but not the listbox. Pressig enter/return autocompletes the "ar" to "Apple".

**Comment by tlouisse** [comment]
Should be fixed in feat/combobox2 branch. Not sure if I saw this issue myself before... could also be that it was fixed along with some other changes

**Comment by tlouisse** [comment]
Fixed here: https://github.com/ing-bank/lion/pull/972
