### ISSUE TITLE
[combobox] On focusout without match --> restores previous checkedIndex value

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#968]
## Expected behavior

In lion-combobox, typing a gibberish value that has no valid matches, and then blurring the field, makes it go back to the previous checked value.

## Actual Behavior

Typing a gibberish value that has no valid matches should remain as the gibberish value, at least for the view value of the field. The modelValue could be undefined or empty string maybe so that a required validator would still pick it up as "not filled in properly".

## Reproduce

1. Type "Beets" and select it
2. Type 'eawjeajwea', now blur it
3. Value is "Beets" instead of 'eawjeajwea' with modelValue undefined/empty string

## Additional

Maybe we should have a demo to show how someone could create a serializer and special required validator for combobox, that allows for modelValue being undefined or empty string, and then it takes the viewValue instead. This would allow people to type values that don't exist in the options, but still be considered "valid" input.

**Comment by tlouisse** [comment]
Should be fixed by https://github.com/ing-bank/lion/pull/972
