### ISSUE TITLE
[combobox] userIsAddingChars false when going from 'Beets' --> 'A'

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#969]
## Expected behavior

When having 'Beets' typed, and then doing CTRL+A --> 'A', I would expect that it autocompletes to Apple for at least autocomplete 'inline' and 'both'.

## Actual Behavior

Does not autocomplete because `'Beets'.length < 'A'.length` --> `false`. This specifically only happens if you instantly replace for example 'Beets' with a character, without first using backspace as an intermediate step.

## Additional context

`const userIsAddingChars = prevValue.length < curValue.length;` in LionCombobox seems to be the problem.

**Comment by tlouisse** [comment]
Should be fixed by https://github.com/ing-bank/lion/pull/972
