### ISSUE TITLE
[combobox]: _inputNode value gets overrided with modelValue

### ISSUE THREAD

**Issue by palash2601** [ing-bank/lion#993]
On Implementing combobox with server-side interaction, i.e options list is received from backend as implemented in `feat/comboboxDemos` branch, below issue happens

## Expected behavior

When clearing the _inputNode value, the characters should get cleared

## Actual Behavior

When clearing the inputNode value, _inputNode gets filled with previously selected modelValue.

Steps:
1. Enter text like `App` in _inputNode and select `Apple` from list
2. start clearing the text in the _inputNode and wait for update to be complete

The _inputNode gets filled with previously selected modelValue which is `Apple`. Expected behaviour would be that the inputNode value gets cleared and updated list of options is visible

According to me it is happening as the component is getting re-rendered when new options list based on the new _inputNode node is rendered. This makes the call to [this](https://github.com/ing-bank/lion/blob/master/packages/combobox/src/LionCombobox.js#L277) code which sets the _inputNode with modelValue

## Additional context

Which component and version of it are you using.
`@lion/combobox: "0.1.1"`

**Comment by tlouisse** [comment]
Interesting. So this only happens for the demo with server side interaction and not in general, right?

**Comment by palash2601** [comment]
Yes....I think this is happening because new search text in `_inputNode` results in new list i.e new `lion-option` components are rendered in listbox. This triggers `form-element-register` for new child components(options) of combobox which results in call to [this](https://github.com/ing-bank/lion/blob/master/packages/listbox/src/ListboxMixin.js#L673) code which sets the `modelValue` to `_inputNode` value

**Comment by palash2601** [comment]
I have created this PR with the change. Not 100% sure about the fix. What do you guys think?
