### ISSUE TITLE
[combobox] Pressing the down arrow cycles through a closed dropdown

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#999]
## Expected behavior

When I press the down arrow I either expect nothing to happen, or that the combobox opens like a select. This also varies within the WAI ARIA examples: https://www.w3.org/TR/wai-aria-practices-1.2/#combobox

## Actual Behavior

When I press the down arrow, the textbox cycles through the values of the dropdown.

**Comment by jorenbroekema** [comment]
Probably need to check for `this.opened` in the keydown/up handlers inside `LionCombox.js`, and return if the combobox is not opened. Then it won't cycle through while closed.

**Comment by daKmoR** [comment]
could this be different for mac/windows 🤔

e.g. like the select which moves through options while closed on windows? but opens it on mac?

however not sure what the behavior here could be 🤔

**Comment by jorenbroekema** [comment]
I thought about that as well but I don't really think it makes sense for combobox where the list of options usually is refetched from an API when the user is typing/searching. It could work if the list of finite options is statically always available but even then I still think we should not do it, or add it later if we think it makes sense for a certain use case.

**Comment by tlouisse** [comment]
@Knorgias lately showed me that this bug doesn't exist anymore in the meantime... this one however does exist: https://github.com/ing-bank/lion/issues/1345

Closing this issue, feel free to reopen when encountered again
